### ISSUE TITLE
No gradlew.bat script for Windows

### ISSUE THREAD

**Issue by ThomasRules2000** [Vazkii/Psi#1]
The gradlew.bat script for building the repo in Windows is missing. When running the build.bat script, cmd reports 'sh command not found'.

**Comment by Vazkii** [comment]
https://www.cygwin.com/

**Comment by ThomasRules2000** [comment]
Why would cygwin be better than the gradlew.bat script?

**Comment by yrsegal** [comment]
because *nix is better

**Comment by ThomasRules2000** [comment]
Any particular reason why *nix trumps windows batch scripts?

**Comment by yrsegal** [comment]
never said better than batch, said better than windows
