### ISSUE TITLE
CAD doesn't do... well, anything

### ISSUE THREAD

**Issue by gaggle331** [Vazkii/Psi#10]
I just added the beta11 version of the mod to my FTB Unstable server and client and when I craft the Iron CAD Assembly and put it in the CAD Assembler, I get a Casting Assistant Device as expected. Then, nothing I do with this CAD causes anything to happen. I never get a Psi bar and I'm unable to create Psi dust.

**Comment by yrsegal** [comment]
You get your bar by using the CAD near Redstone dust. Have you done so?

**Comment by gaggle331** [comment]
Yup. Also tried with lapis.

**Comment by yrsegal** [comment]
Does it function in creative as expected?

**Comment by gaggle331** [comment]
Welp, just tried it again and it worked this time. Maybe it doesn't work when you do it with lapis at the same time? I was just following this http://vazkii.us/psitutorial.html which says to drop lapis and redstone in a 1:1 ratio.

**Comment by Vazkii** [comment]
That's outdated and only for early demonstration. Don't use that.
