### ISSUE TITLE
Misspelling of casting in mcmod.info

### ISSUE THREAD

**Issue by ThomasRules2000** [Vazkii/Psi#100]
Casting is spelt cating in the mcmod.info

**Comment by yrsegal** [comment]
![Spellcating](http://windstoneeditions.com/sites/default/files/imagecache/product_full/cat-wizard-404-P.jpg)

**Comment by Berstarke** [comment]
Concept art for new Psi Armor.

**Comment by fingin** [comment]
ill fix it  now

**Comment by PsiGuy60** [comment]
We need a "Spawn Cat" trick that just makes an image of a cat appear there, just to keep the legacy of this typo alive.
