### ISSUE TITLE
Psi cost calculations

### ISSUE THREAD

**Issue by seblund** [Vazkii/Psi#101]
I am unsure if this is a bug or intended, but it seems somewhat buggy, the two spells do the same thing (9.5 speed goes 37 blocks up, 2x5 speed goes 38 blocks up)

The cost and the complexity of these two spells are incredibly different.
I am aware of the fact that projection goes up alot on the 2x5 spell, but having one spell cost a fourth of another with the exact same function seems somewhat unintended

![image](https://cloud.githubusercontent.com/assets/17483094/13333987/e2a87154-dc09-11e5-8541-42832f9df6d4.png)

![image](https://cloud.githubusercontent.com/assets/17483094/13333977/d84deb6c-dc09-11e5-9e3d-7e7197a48312.png)

**Comment by seblund** [comment]
(Build 18)

**Comment by NoahNMorton** [comment]
It's because add motion is exponential in it's cost, so adding more tricks is always cheaper than one big one. I suppose that's why projection exists.

**Comment by seblund** [comment]
I am aware that it is exponential, but a 3/4 psi cost reduction doesn't seem intended

**Comment by Vazkii** [comment]
Yeah, this is definitely a problem. There's really no way for the pieces to interface with one another. I might just have to do it so you can only use a single add motion in a given axis. :|

**Comment by SoulEvans07** [comment]
But than you might cut of the possibility of a good flight spell :( and that would be terrible if you know what I mean. ;)

**Comment by Vazkii** [comment]
Got any other ideas to fix this?

**Comment by yrsegal** [comment]
Make adding motion less effective the more the player is moving in that
direction?

**Comment by SoulEvans07** [comment]
Or for each of the tricks that are already in the spell you give a 0.5 multiplier to the Potency and Cost.
In this case it would be x3 so Potency: 210 and Cost: 1800, thats cheaper than the single Add Motion spell but you gain that from using more Bandwith and Projection. If it has a bad effect on other tricks you can narrow it down only to Motion type tricks, but to justify that to a player is another problem

**Comment by seblund** [comment]
Maybe doing something where you add up all of the constants pr. direction, and then doing exponential growth on that, i don't know how possible that is with the way the code is set up tho.
