### ISSUE TITLE
request: parametric loopcast/circle spell

### ISSUE THREAD

**Issue by SoulEvans07** [Vazkii/Psi#106]
I know that now with the Operator:Min + Trick:Die I can stop circle spell bullets before the 20th cast but there is no way to make a circle spell last longer, if I'm not mistaken. 
Can you make a Trick that take a Constant Number and at that loopcast index it will terminate itself and to balance it, if the constant is bigger then 20 then it Cost more, or just make it linear all the way down.

**Comment by Vazkii** [comment]
No.

**Comment by SoulEvans07** [comment]
That was quick :D
