### ISSUE TITLE
Class Cast Exception When Using Spell.

### ISSUE THREAD

**Issue by Democretes** [Vazkii/Psi#107]
Got the following crash report from casting the following spell. The spell compiled fine and I was able to put into a CAD.

![2016-02-27_18 52 58](https://cloud.githubusercontent.com/assets/6187441/13376485/5534691a-dd83-11e5-8375-be2c48860494.png)

[crash-2016-02-27_18.50.14-client.txt](https://github.com/Vazkii/Psi/files/149671/crash-2016-02-27_18.50.14-client.txt)

**Comment by yrsegal** [comment]
could you give us the spell json as well?

**Comment by Democretes** [comment]
Is the spell json the copy clipboard in teh spell programmer or is it a separate file?

**Comment by yrsegal** [comment]
copy clipboard.

**Comment by Democretes** [comment]
Here you go. I also found out that when switching the 0 from the ConstantWrapper to a greater number, the bug does not occur.
http://pastebin.com/wjx6ZUDX

**Comment by yrsegal** [comment]
https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/common/spell/constant/PieceConstantWrapper.java#L53
this line should return 0D, not 0. That's the bug.

**Comment by yrsegal** [comment]
Vazkii, to prevent future errors of this kind, could non-trick pieces take a generic?
