### ISSUE TITLE
[BUG] Cannot 'turn off' abilities on Leggings (Psi-beta-18)

### ISSUE THREAD

**Issue by Vaygrim** [Vazkii/Psi#109]
Psi beta 18, I've got a spell set in the first slot for Exo Suit Leggings (so lower right on the spell wheel) and I literally cannot turn it off. Selecting any other empty slot on the leggings using the remote doesn't seem to do anything. Even checking the tooltips directly for the leggings shows my one single spell as actively selected.

Honestly I'm not sure if this is a bug or just the quirkiness of the remote. (It is rather hard to use.)

**Comment by Wojbie** [comment]
Are you clicking on empty slot or letting go of c key with blank slot selected?
Pressing a key changes the armor slot you control and letting go sets currently selected piece of armor to use bullet in slot your mouse is over. 
In other words i can not duplicate this. Could you provide more info and attempt to use controller same way you use the gun?

I also kinda agree it takes a moment to get used to how it works. I think people are used to using mouse clicks to select stuff and when its doing something else (swapping armor pieces) it seems confusing on some level.

**Comment by yrsegal** [comment]
I can't reproduce this at all, on 19.

**Comment by Vaygrim** [comment]
@Wojbie I've tried both methods. Hold down C, hover over the top right empty slot.. then release C. Power's still equipped by the Leggings. Hold down c, hover over top right empty slot, then left click to cycle to feet.. release C. Same effect.

**Comment by yrsegal** [comment]
huh. Modlist? And does beta 19 fix it?

**Comment by Vaygrim** [comment]
This is on **ForgeCraft 1** so I have zero control over updating. The mod list is as follows:

Bagginses
BiomesOPlenty
BloodMagic
Buildcraft
Charset
ChiselsandBits
ComputerCraft
DeepResonance
ElecCore
ExtraUtils2
Factorization
FlatColorBlocks
Graves
In Game Wiki
Immersive Engineering
Intangible
Inventory Sorter
iron Chests
JEI
JEI Addons
JourneyMap
Just Enough Resources
Light Level Overlay
Mantle
MCJtyLib
MCMultiPart
MmmMmmMmmMmm
Morpheus
OpenModsLib
OpenPeripheralAddons
OpenPeripheralCore
OpenPeripheralIntegration
PneumaticCraft
Psi (Beta 18)
RFTools
RFTools Dimensions
Simple Retrogen
Tinkers' Construct
Thaumcraft
Thump
Waila

**Comment by yrsegal** [comment]
doesn't vazkii building a version push it to forgecraft? I thought she said something along those lines...

**Comment by Vaygrim** [comment]
Normally Forgecraft is ahead of the curve on mod version testing. For the 1.8.9 generation of mods however, we seem to have fallen BEHIND the curve because there is so much hype for new mods like Psi, Chisels & Bits, Intangible, etc. For the last month we've almost always been behind by 1 version from the public.

**Comment by yrsegal** [comment]
anyway, does anyone else on forgecraft have this bug? trying to isolate if it's something up with your instance

**Comment by Vaygrim** [comment]
Vazkii has access to the server, they could check directly. I will ask around, however, but at present I don't think anyone else is working with Psi to the same extent. Only reason this issue got posted is because @Vazkii asked me to on Twitter, heh.

**Comment by yrsegal** [comment]
Dire is working with psi, but he's nowhere near lv 21, so no exosuit.

**Comment by KirinDave** [comment]
I cannot reproduce this behavior in Psi-19.

**Comment by yrsegal** [comment]
@Vaygrim, can you reproduce this in the latest version, if it's on FC?

**Comment by Vaygrim** [comment]
Beta 19 is on FC1 riight now (if not something more up to date already), and I was still having that issue with Beta 19. I'll post a video later today showing what kind of weirdness I'm having with it.

**Comment by yrsegal** [comment]
Is there any news on this one, @Vaygrim? Can you reproduce it playing with psi alone, and can you still reproduce it on FC1?

**Comment by Vaygrim** [comment]
It's still wonky on FC1 but I can work around it finally by taking off ALL armor, the putting each piece on one at a time to 'set' which spell is active. That didn't work prior to Psi-19. I'm going to close this as it's not easily reproducable. I do honestly think the Remote Control needs to have its UI slightly adjusted. I really cannot reliably configure spells on individual armor pieces if I'm wearing the whole suit.
