### ISSUE TITLE
[Bug/May not be Bug] Circle casting Face

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [Vazkii/Psi#113]
I noticed while attempting to create a type of "Quarry" using circle casting, that spell circles don't point in the direction they were casted. For example if i attempted to cast it towards the ground, i hoped it would face in said direction when using entity look, but instead it continually faced South, which was rather strange.
i was hoping i could use the same spell to dig out larger areas with nothing more than a cast on a wall or floor, but sadly it didn't work that way.

**Comment by yrsegal** [comment]
Which build are you on? Which entity did you use for the Entity Look, you or the Circle?

**Comment by UnstableCodeScarlet** [comment]
I used the "Focal" point, build 18.
I was hoping circles would be cast facing in the direction of the block they were cast on, basically.

**Comment by yrsegal** [comment]
This was fixed in build 19.

**Comment by UnstableCodeScarlet** [comment]
Oh, sorry and thanks.

**Comment by yrsegal** [comment]
Could you close this issue as it is resolved?
