### ISSUE TITLE
World Time behaves erratically. 2x tick rate while in leggings.

### ISSUE THREAD

**Issue by KirinDave** [Vazkii/Psi#114]
The World Time parameter seems to have some very strange behavior. In a circle cast bullet, it seems to fire quite slowly compared to the world ticks. This may be intended.

However, in the leggings it appears to fire twice per every tick. This is trivially to reproduce by placing it in a debug context and then watching the output when placed in leggings. I see 2x of every number, and sometimes I skip a number.

This is very surprising, as the leggings imply they will fire the spell once per every tick.  I would expect to see one console output entry per tick with a monotonically increasing number.

**Comment by yrsegal** [comment]
can't reproduce.

**Comment by yrsegal** [comment]
Loopcasts and circles produce the expected results (casting every 5 ticks) and leggings increase by 1 every print, no skips or repeats.

**Comment by KirinDave** [comment]
Try adding a mod 10? That's my trivial reproduction. I refuse to believe that is an outcome of delayed computation. It makes no sense.

**Comment by Wojbie** [comment]
KirinDave can you provide code for spell you are using to test it? That would help.

**Comment by yrsegal** [comment]
what the hell... 
<img width="130" alt="screen shot 2016-03-12 at 10 37 12 pm" src="https://cloud.githubusercontent.com/assets/6596492/13726736/04566b12-e8a3-11e5-80c6-1b8202533668.png">

**Comment by yrsegal** [comment]
So, with mod 10, something... changes. how damned annoying.

Should the spell context contain the worldtime, and update it with the delay?
