### ISSUE TITLE
My server crashesh when I put Psi in it

### ISSUE THREAD

**Issue by FakeLook** [Vazkii/Psi#115]
I wanted to run Psi on my private machine for the sake of chunkloading, but when I put Psi in, the server crashes when starting. I've tested this with versions 17, 18 and 19.
Becouse I am still setting the server up I run it in VirtualBox on Linux Debian

here is crash report with other mods: http://pastebin.com/3ZgJWJpr
crash report without other mods: http://pastebin.com/GRAxgvN1

Forge version: 11.15.1.1758

mods I use: 
Blood Magic 0-19
Morpheus 2.0.58.
PneumaticCraft 1.13.7-11
Psi 19
Thaumcraft 5.1.6.
Waila 1.6.0-B3_1.8.8.
Chisel and Bits v1.8.11.
Ironchest 6.0.125.770.
JEI 2.28.6.173

**Comment by yrsegal** [comment]
use java 8.

**Comment by yrsegal** [comment]
This should be closed. Also, @Vazkii you should put this in the issues.md or whatever the new template format is.

**Comment by FakeLook** [comment]
thanks, upgrading to java 8 helped
