### ISSUE TITLE
Psi not install in Server [CLOSED]

### ISSUE THREAD

**Issue by Rumaruka** [Vazkii/Psi#117]
Psi 18 and 19 build not install in Server 
http://pastebin.com/5D141tFn
Sorry, i think fix problem
CLOSED

**Comment by yrsegal** [comment]
use java 8.

**Comment by yrsegal** [comment]
@Vazkii, you probably should make an issue template which tells people to use java 8. https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by Wojbie** [comment]
Duplicate of #115

**Comment by Rumaruka** [comment]
Sorry , I first put the server.
How to use java8??

**Comment by yrsegal** [comment]
You didn't actually close the issue...
