### ISSUE TITLE
Overflow can go all the way around the number line

### ISSUE THREAD

**Issue by yrsegal** [Vazkii/Psi#125]
If you put ENOUGH power into a spell, it will allow it to compile despite being stupidly over the top. In theory, I could optimize this to run on my Ivory cad. If not this, certainly an Add Motion spell.
<img width="896" alt="screen shot 2016-03-07 at 10 41 03 pm" src="https://cloud.githubusercontent.com/assets/6596492/13591432/8473fb02-e4b6-11e5-809c-242977342e15.png">

**Comment by yrsegal** [comment]
To reproduce: ```
{spellName:"Regeneration",uuidMost:-5193044951827660027L,validSpell:1b,spellList:[0:{spellPosX:3,spellData:{spellKey:"constantNumber",params:{},constantValue:"1"},spellPosY:4},1:{spellPosX:4,spellData:{spellKey:"selectorCaster",params:{}},spellPosY:2},2:{spellPosX:4,spellData:{spellKey:"trickAddMotion",params:{psi.spellparam.direction:2,psi.spellparam.speed:4,psi.spellparam.target:1}},spellPosY:3},3:{spellPosX:4,spellData:{spellKey:"operatorVectorConstruct",params:{psi.spellparam.z:0,psi.spellparam.y:3,psi.spellparam.x:0}},spellPosY:4},4:{spellPosX:4,spellData:{spellKey:"connector",params:{psi.spellparam.target:1}},spellPosY:5},5:{spellPosX:4,spellData:{spellKey:"connector",params:{psi.spellparam.target:1}},spellPosY:6},6:{spellPosX:5,spellData:{spellKey:"constantNumber",params:{},constantValue:"99999"},spellPosY:3},7:{spellPosX:5,spellData:{spellKey:"trickAddMotion",params:{psi.spellparam.direction:3,psi.spellparam.speed:1,psi.spellparam.target:4}},spellPosY:4},8:{spellPosX:5,spellData:{spellKey:"constantNumber",params:{},constantValue:"1"},spellPosY:5},9:{spellPosX:5,spellData:{spellKey:"trickAddMotion",params:{psi.spellparam.direction:3,psi.spellparam.speed:1,psi.spellparam.target:4}},spellPosY:6},10:{spellPosX:6,spellData:{spellKey:"selectorCaster",params:{}},spellPosY:4},11:{spellPosX:6,spellData:{spellKey:"selectorCaster",params:{}},spellPosY:6}],uuidLeast:-4621408322499274939L}
```

**Comment by yrsegal** [comment]
i'm still falling.

**Comment by yrsegal** [comment]
Not yet fully fixed. With calculation it is still possible to do.

**Comment by Vazkii** [comment]
Get me an export that can do it and I'll look into it.

**Comment by yrsegal** [comment]
Welp, time to calculate some add motion when i get home
