### ISSUE TITLE
Operator: Subtract wierdness.

### ISSUE THREAD

**Issue by Wojbie** [Vazkii/Psi#126]
I am guessing its floating point number problem but its better to report it then not.
1-0.9 = 0,09999999999999998

Spell:
{spellName:"Debug",uuidMost:7424138079555699406L,validSpell:1b,spellList:[0:{spellPosX:0,spellData:{spellKey:"constantNumber",params:{},constantValue:"1"},spellPosY:0},1:{spellPosX:0,spellData:{spellKey:"constantNumber",params:{},constantValue:"1"},spellPosY:2},2:{spellPosX:1,spellData:{spellKey:"operatorSum",params:{psi.spellparam.number2:2,psi.spellparam.number3:0,psi.spellparam.number1:3}},spellPosY:0},3:{spellPosX:1,spellData:{spellKey:"constantNumber",params:{},constantValue:"0.99"},spellPosY:1},4:{spellPosX:1,spellData:{spellKey:"operatorSubtract",params:{psi.spellparam.number2:2,psi.spellparam.number3:0,psi.spellparam.number1:3}},spellPosY:2},5:{spellPosX:1,spellData:{spellKey:"constantNumber",params:{},constantValue:"0.9"},spellPosY:3},6:{spellPosX:2,spellData:{spellKey:"trickDebug",params:{psi.spellparam.number:4,psi.spellparam.target:3}},spellPosY:0},7:{spellPosX:2,spellData:{spellKey:"trickDebug",params:{psi.spellparam.number:4,psi.spellparam.target:3}},spellPosY:2},8:{spellPosX:3,spellData:{spellKey:"constantNumber",params:{},constantValue:"1"},spellPosY:0},9:{spellPosX:3,spellData:{spellKey:"constantNumber",params:{},constantValue:"2"},spellPosY:2}],uuidLeast:-7953289267634702304L}

**Comment by Vazkii** [comment]
Yeah, floating point numbers are like that.
