### ISSUE TITLE
smart moving armor render issue

### ISSUE THREAD

**Issue by ZEROX7** [Vazkii/Psi#128]
hey
wehn installe smart moving and the apis for it your armor does not hook to the player anymore.
looks like that: http://puu.sh/nDK9k/5029dbba1c.jpg
i hope you can make a fix for it, and to help you a littel thats waht i found:
"This is a Divisor instruction for Render Player api, wich also works without Render Player Api:

" To solve this specific problem you need your mod's armor model class inherit from "api.player.model.ModelPlayer" instead of"net.minecraft.client.model.ModelBiped".

In case you want your mod to also work without Render Player API, you are going to need two identical armor model classes:

• one inheriting from "net.minecraft.client.model.ModelBiped" and
• the other one inheriting from "api.player.model.ModelPlayer".

Then create an instance of one of them depending on whether Render Player API is present or not."

**Comment by Vazkii** [comment]
Nope.
