### ISSUE TITLE
CAD resets GUI size

### ISSUE THREAD

**Issue by laz2727** [Vazkii/Psi#129]
CAD somehow randomly resets my GUI size back to "normal" and doesn't let me change it back until i put CAD in a chest. And it doesn't render PSI bar either unless it's "normal". My window size is 1280x1024. It really sounds like some weird corner-case.

**Comment by Vazkii** [comment]
Can't reproduce. Try deleting your config.

**Comment by laz2727** [comment]
Nope.

https://youtu.be/MDuZ9JD9r0o

**Comment by yrsegal** [comment]
Perhaps it's better to just do the ScaledResolution calculations yourself, or have a class which extends it?

**Comment by Vazkii** [comment]
Your window size is not 1280x1024, it's smaller because of the windows bars. Can you go to the snooper settings and tell me how large it is there?

**Comment by laz2727** [comment]
There isn't anything about it in snooper settings, debug shows it's 1280x975.

**Comment by Vazkii** [comment]
That works as well.

**Comment by laz2727** [comment]
Psi bar is still invisible, though.
