### ISSUE TITLE
Add motion requires Number Constant instead of Number.

### ISSUE THREAD

**Issue by Zobody** [Vazkii/Psi#13]
This means that if you want to add to numbers, and then send the result to Add Motion trick, it wont work.
![What I'm trying to do.](https://cloud.githubusercontent.com/assets/16544117/13002104/893832a2-d174-11e5-85f5-c3fe635b0c8c.png)
![What works for now.](https://cloud.githubusercontent.com/assets/16544117/13002112/8cd10f7e-d174-11e5-9e47-2ca60bf53a29.png)

**Comment by KeddoXZ** [comment]
It literrally says it needs a number constant instead of number so it is not a bug. This could be nice ferature but I really myself wouldn't find any sense for it being a ferature as you would literrally die with high enough numbers. http://puu.sh/n5373/cc0e5a656a.jpg

**Comment by yrsegal** [comment]
It's intentional because that constant determines cost.
