### ISSUE TITLE
Crash upon interaction between Vector: Construct and Operator: Round

### ISSUE THREAD

**Issue by Carloslionheart** [Vazkii/Psi#131]
I attempted to create a spell that would take the number constant 0.2, then I would use Operator: Round to turn it to 0, and then made a Vector Constructor that would take the resulting number from the Round Operator and set it as the 'Z' of the construct. On casting, the client crashes. 

FML Log: http://pastebin.com/jvNLjFQG

**Comment by yrsegal** [comment]
a... long? wat

**Comment by Wojbie** [comment]
Can you provide code for actuall spell you are using that crashes. Also i suggest adding question about spell code to issue template.

**Comment by yrsegal** [comment]
no, this makes sense. round probably returns a long from a double, and v didn't convert it.

**Comment by yrsegal** [comment]
Math.round to be specific.

**Comment by Carloslionheart** [comment]
@Wojbie  Here is the screenshot of the spell: http://i.imgur.com/tZ4bYNq.png?1

Here is the code as well:

{spellName:"Debug",uuidMost:6465599538374266121L,validSpell:1b,spellList:[0:{data:{params:{_x:4,_y:0,_z:0},key:"operatorVectorConstruct"},x:0,y:0},1:{data:{params:{_number:0,_target:1},key:"trickDebug"},x:0,y:1},2:{data:{params:{_number:4},key:"operatorRound"},x:1,y:0},3:{data:{key:"constantNumber",constantValue:"0.2"},x:2,y:0}],uuidLeast:-8349855173244799935L}
