### ISSUE TITLE
Trick: Explode throws stuff up with force disproportionate to explosion size

### ISSUE THREAD

**Issue by Wojbie** [Vazkii/Psi#138]
Explode damage applies upwards force that is disproportionate to explosion side. Small explosions (0.2 per example) propel things 10 or 15 blocks up. Provided spell will cause 20 explosion a second on nearby living things in 32 block range to explode and fly up and up and up. And its free. I mean small explosion being free is nice cause it causes no damage and look cool but upward momentum part is broken.

[Spell in action](https://i.imgur.com/OdKkBbG.webm) (I am bad at recording stuff)

![Image of spell.t](https://i.imgur.com/fXGKkb3.png)

{spellName:"Explode",uuidMost:-7680952855489459661L,validSpell:1b,spellList:[0:{data:{key:"errorSuppressor"},x:3,y:2},1:{data:{key:"selectorCaster"},x:3,y:3},2:{data:{params:{_target:1},key:"operatorEntityPosition"},x:3,y:4},3:{data:{key:"constantNumber",constantValue:"0.001"},x:4,y:2},4:{data:{key:"constantNumber",constantValue:"32"},x:4,y:3},5:{data:{params:{_position:3,_radius:1},key:"selectorNearbyLiving"},x:4,y:4},6:{data:{params:{_power:3,_position:2},key:"trickExplode"},x:5,y:2},7:{data:{params:{_target:2},key:"operatorEntityPosition"},x:5,y:3},8:{data:{params:{_target:3},key:"operatorRandomEntity"},x:5,y:4}],uuidLeast:-8943107816660231076L}

**Comment by yrsegal** [comment]
so... we could use this and add motion to achieve flight? :o

**Comment by Wojbie** [comment]
No Trick:Explode don't work on caster himself. You can fly other people or mobs with timed explosions.

**Comment by yrsegal** [comment]
ride a horse.

**Comment by Wojbie** [comment]
I keep forgething those exist. That could work. You could fly a horse/pig with timed explosions.

**Comment by NoahNMorton** [comment]
And they said pigs couldn't fly...

**Comment by yrsegal** [comment]
Fairly sure this is a vanilla bug, actually.

**Comment by yrsegal** [comment]
Explosion size zero is still an explosion, albeit one that produces no block damage. It will certainly do knockback.
