### ISSUE TITLE
Add motion doesn't actually negate fall damage

### ISSUE THREAD

**Issue by yrsegal** [Vazkii/Psi#139]
tested with https://imgur.com/im3YH0V

**Comment by Lanrik** [comment]
Confirm, but actually fall damage reduction depend on time, when "add motion" used. If it used in beginig falling, trick reduce damage, else if it used in end, closer to ground, it dont reduce damage.
By the way it doesnt increase damage if used in opposite vector.

**Comment by Vazkii** [comment]
Add motion only negates fall damage if the resulting Y motion is above 0.
