### ISSUE TITLE
Client-Side NPE with CAD + Blink Spell

### ISSUE THREAD

**Issue by oitsjustjose** [Vazkii/Psi#141]
Before we start, here's a checklist of things that may be helpful:

- [x] Make sure you're not reporting something that was just fixed
- [x] Make sure you're not using an old version of Psi.
- [ ] Make sure you're not using Optifine or GLSL Shaders, if it's a rendering issue. **<-- I am using BetterFPS; that is all - no Optifine nor GLSL Shaders. Removing BetterFPS does not resolve the persistent crash**
- [x] Make sure you're using Java 8. Psi will not function in older versions.

I've had this issue occur various times, and for a while I thought I could blame Intangible's arm rendering override for this crash - but I just finished removing it and this still happened, so I believe it may have been Psi all along. In using a Blink spell I created (blinks the player 5 blocks forward), sometimes when blinking to a position that makes me take damage (be it from suffocation specifically), my client crashes. A re-log does not resolve the fix; only resetting my player's coordinates using an NBT Editor.

I will grant you this, the crash-log (and event the FML-Client log) is relatively useless. I _am_ holding a CAD each time this crash occurs, so maybe it's an issue with the renderer? None of the logs trace far enough back to figure out really what's happening if you ask me, but I could be wrong.

[FML Crash-Log](http://puu.sh/nKhp6/d7dcffcbeb.txt)

**Comment by KingDGrizzle** [comment]
Well, I dont seem to have this issue AT ALL.. I'll just check the log really quick

**Comment by KingDGrizzle** [comment]
Told you to update mods

**Comment by oitsjustjose** [comment]
At the time of the bug report I _**had**_ updated all of my mods. I don't understand why you're being so defensive (and rude) about a mod that isn't even your responsibility..
