### ISSUE TITLE
Client Crash when clicking on Psi Tab in Creative Menu

### ISSUE THREAD

**Issue by Galaxy2Alex** [Vazkii/Psi#143]
Pretty straight forward, the client crashes for me when I click on the Psi Creative Tab.

Crash: https://gist.github.com/Galaxy2Alex/5c28eb39de5e6387a488

**Comment by Vazkii** [comment]
Oh right, I forgot ForgeGradle mangles lambdas, gah.

**Comment by williewillus** [comment]
Does it still not work? 0.o
