### ISSUE TITLE
Creative Tab Crash 1.9

### ISSUE THREAD

**Issue by miguelviegas26** [Vazkii/Psi#144]
I started minecraft with only Psi Beta-25 on 1.9 and when I go to PSI creative tab it instantly crashes.

I am using JRE 1.8.0 Update 74 
Tried with both forge 12.16.0.1766 and 12.16.0.1767. Both crashes

FML Log: http://pastebin.com/LSvRcQY3

**Comment by Vazkii** [comment]
Still? wtf

**Comment by miguelviegas26** [comment]
I'll be waiting for you to update the mod once again and will check if it works then
Good job with updating it 1.9

**Comment by Vazkii** [comment]
Try 26

**Comment by miguelviegas26** [comment]
ok it seems to work now
Not crashed yet YEAH
