### ISSUE TITLE
CAD not rendering in 1st person properly

### ISSUE THREAD

**Issue by TheChronomancer** [Vazkii/Psi#146]
when i hold a CAD in first person it  doesn't render in the right position and sometimes the CAD derps (meaning it thinks it's being used when it's not
![2016-03-18_10 48 56](https://cloud.githubusercontent.com/assets/8211402/13887176/9536fe78-ecf7-11e5-8727-1cdcdd8b6e28.png)

**Comment by TheChronomancer** [comment]
never mind it fixed itself

**Comment by Vazkii** [comment]
Forge bug.
