### ISSUE TITLE
transparent hand

### ISSUE THREAD

**Issue by loordgek** [Vazkii/Psi#147]
https://paste.ee/p/x7Kqi
forge only
![2016-03-18_22 57 03](https://cloud.githubusercontent.com/assets/4789835/13893236/06553d94-ed5d-11e5-9515-4c75030aa9a7.png)
w/ psi
![2016-03-18_22 56 24](https://cloud.githubusercontent.com/assets/4789835/13893244/10607182-ed5d-11e5-842d-c20a42151c54.png)

offtopic
https://github.com/mezz/JustEnoughItems/issues/213#issuecomment-198556771
- [ ] Make sure you're not using an old version of Psi.
oops

**Comment by yrsegal** [comment]
forge only? seems you have psi in there...

**Comment by Vazkii** [comment]
This is a forge bug. I've encountered it before even adding in Psi.
