### ISSUE TITLE
Overgrowth uses Psi energy when out of range

### ISSUE THREAD

**Issue by ewanm89** [Vazkii/Psi#149]
Overgrowth takes psi energy when it can't cast when out of range. This makes it impossible to make a sustained loopcast overgrowth spell.

Here is the spell I was trying to create.
{spellName:"Overgrowth loop",uuidMost:-1453567624766602620L,validSpell:1b,spellList:[0:{data:{params:{_target:2},key:"operatorEntityLook"},x:2,y:2},1:{data:{key:"selectorCaster"},x:2,y:3},2:{data:{key:"constantNumber",constantValue:"4"},x:3,y:1},3:{data:{params:{_ray:3,_max:0,_position:2},key:"operatorVectorRaycast"},x:3,y:2},4:{data:{params:{_target:3},key:"operatorEntityPosition"},x:3,y:3},5:{data:{key:"selectorLoopcastIndex"},x:4,y:0},6:{data:{params:{_number2:3,_number1:1},key:"operatorModulus"},x:4,y:1},7:{data:{params:{_number2:4,_vector1:3},key:"operatorVectorMultiply"},x:4,y:2},8:{data:{params:{_position:1},key:"trickOvergrow"},x:4,y:3},9:{data:{key:"constantNumber",constantValue:"500"},x:5,y:0},10:{data:{params:{_number2:3,_number3:0,_number1:1},key:"operatorMultiply"},x:5,y:1},11:{data:{params:{_number2:2,_number3:0,_number1:1},key:"operatorSum"},x:5,y:2},12:{data:{key:"constantNumber",constantValue:"1"},x:5,y:3}],uuidLeast:-5924740881825878499L}

Left most constant controls number of iterations out of range, I've removed the error suppressor to double check the casts were out of range.

**Comment by yrsegal** [comment]
Spell Cost is calculated based on the spell program, not the actions taken during a cast. This is intended behavior.
