### ISSUE TITLE
Trick: Move block

### ISSUE THREAD

**Issue by Lanrik** [Vazkii/Psi#151]
Trick: Move block dont move such block as leaves and furnances, chest etc.
Also, if apply this trick to push block up too frequently items on it doesnt move up.

**Comment by AlterAkima** [comment]
It only moves blocks that a Piston can move.

**Comment by Lanrik** [comment]
@AlterAkima its mod policy?

**Comment by AlterAkima** [comment]
Moving a tile entity doesn't ends well most of the times.

**Comment by Lanrik** [comment]
Wand foci dislocation from thaumcraft can transfer any blocks. Then it seems to be possible. But i dont know how hard it is code.

**Comment by yrsegal** [comment]
That's from Thaumic Tinkerer. And it is possible, but the focus acts like a piston.

**Comment by yrsegal** [comment]
Also, @AlterAkima, moving a TE is simple. It's whether you want to allow someone to move one that's the question.
