### ISSUE TITLE
Single Cad bug

### ISSUE THREAD

**Issue by Lanrik** [Vazkii/Psi#152]
If player have only one cad in inventory, then this cad have a render bug, and it cannot break any blocks. Forge 1770. In 3th person mode render okey.
Gif: http://i.imgur.com/RjgY4Gl.gifv

**Comment by yrsegal** [comment]
so, it's constantly refreshing the animation. Fun.

**Comment by yrsegal** [comment]
https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/common/item/ItemCAD.java#L377 not working anymore?

**Comment by williewillus** [comment]
Forge bug
