### ISSUE TITLE
Getting a method doesn't exist error when loading the deobfuscated version in dev env.

### ISSUE THREAD

**Issue by ProfessorProspector** [Vazkii/Psi#155]
net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: vazkii.psi.common.block.BlockCADAssembler.setStepSound(Lnet/minecraft/block/SoundType;)Lnet/minecraft/block/Block;

**Comment by JRoffel** [comment]
Makes sense, as the method is indeed not there...
However, is it needed?

**Comment by ProfessorProspector** [comment]
Apparently it is according to the crash. Here's the full [log](http://pastebin.com/2EnfqbAE) and here's the [crash report](http://pastebin.com/N4yvb0bn)
