### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by seblund** [Vazkii/Psi#157]
I know this will probably require a slight revamp of the spell system. However, I do feel that this is a neccesary evil. Can we make it so Psi-energy is only taken once an actual Trick is fired, so you can make passive spells with leggings and loopcast bullets. I do not think that this feature would be so-called OP in any way, i just think it would make us be more creative in spell creation and make actual useful spells in leggings and such

**Comment by yrsegal** [comment]
I think it's intended that spell cost is by the program, not the trick.

**Comment by seblund** [comment]
I know it is intended, but it limits creativity, and it could be fixed, the Psi cost on the side in the spell programmer could instead be the max cost of the spell

**Comment by yrsegal** [comment]
balance > player freedom

**Comment by seblund** [comment]
reduced cost atleast, that would add some balance

**Comment by yrsegal** [comment]
that... removes balance..? do you know what balance is?

**Comment by seblund** [comment]
balance is subjective, in this case i don't think it would remove balance

**Comment by yrsegal** [comment]
@Vazkii can you close this before @seblund makes more of a fool of themselves

**Comment by seblund** [comment]
I guess this falls under the "Any sort of automation" thing you wont see in Psi, i reside

**Comment by yrsegal** [comment]
what? no it doesn't

it's a blatant unbalancing act, and would require hours of work (at least, for me it would) to do. not worth it.

**Comment by seblund** [comment]
My only point was that it feels unsatisfying to cast a spell that does nothing, and still have to pay for it. I do not know if it is balanceable. To me Psi is about creativity and fun, and this "feature" removes some of that.

**Comment by yrsegal** [comment]
yeah, you have to design around the restrictions you have. Do you complain about getting tired from sitting around in real life?

**Comment by seblund** [comment]
Who gets tired from sitting around? :)

**Comment by yrsegal** [comment]
humans.

**Comment by JRoffel** [comment]
Yrsegal: 1
Seblund: 0

**Comment by williewillus** [comment]
also....requests don't go on github I thought :P

**Comment by yrsegal** [comment]
never explicitly specified for Psi.
