### ISSUE TITLE
Trick:Explode Discrepancy between bullets.

### ISSUE THREAD

**Issue by NolanSyKinsley** [Vazkii/Psi#158]
MC 1.9 forge build #1804
I don't know if this is a bug exactly but there is a discrepancy between normal bullets and projectile bullets with Trick:Explode. 

With normal bullets when a mob is killed with trick explode it counts as a player kill with better drops and experience. With projectile bullets the mobs killed by the explode trick drop base loot and no XP.

**Comment by yrsegal** [comment]
That's because the projectile casts the spell as itself, and therefore makes the explosion as itself.

**Comment by NolanSyKinsley** [comment]
I figured as much, but it should still count as a player kill for XP and loot drops. If I set up a dispenser to drop potions, even though the dispenser is doing the killing it is still counted as a player kill because they are being killed by a construct of the player, or they are taking damage that can only be applied by a player.

**Comment by yrsegal** [comment]
Dispensers don't give XP.

**Comment by NolanSyKinsley** [comment]
I can disprove that, I have been using a dispenser shooting out splash potion of instant health II into my grinder to clear out the built up zombies, I get a shower of good loot and experience orbs to the point my game lags.


Regardless of dispensers, shouldn't the bullets be considered a player action? Or rather, shouldn't the bullet impacting just be giving the coordinates for the location of MY spell? It is using my "willpower" to perform the action after all.

**Comment by yrsegal** [comment]
Yes, I am. Only args are --username and --password.

**Comment by NolanSyKinsley** [comment]
@yrsegal I think you may have gotten a response mixed up somewhere. I am racking my brain but your reply just doesn't make sense in this context.

**Comment by yrsegal** [comment]
oh, yeah. definitely. .-.

**Comment by yrsegal** [comment]
You're creating the bullet from your willpower, but then it is separate.

If you throw a single splash potion and then throw the potions via dispenser, you will get XP. that may be how you did it.

**Comment by NolanSyKinsley** [comment]
"creating a bullet from your willpower" Even if the bullet is separate from me, it is still a force of my will...

**Comment by yrsegal** [comment]
It is created from your will, but no longer yours.
