### ISSUE TITLE
Can't get Psidust

### ISSUE THREAD

**Issue by tkdberger** [Vazkii/Psi#16]
I can't seem to obtain Psidust using an Iron CAD as per the tutorial. Not sure if the fact that I'm changing gamemodes is the problem, but if it is then it would be nice to see that fixed.

Anyway, the issue is that _I can't start in the mod._

**Comment by yrsegal** [comment]
You're using the CAD with redstone dust, no lapis, on the ground around you?

**Comment by tkdberger** [comment]
Yes.

**Comment by tkdberger** [comment]
Figured it out.

Multiple CADs.
PLEASE put some sort of indication that you can't do that.
