### ISSUE TITLE
Crash on Playerdata cleanup (ConcurrentModificationException)

### ISSUE THREAD

**Issue by Robijnvogel** [Vazkii/Psi#163]
[This](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mod-packs/2646343) was just posted on the Minecraft Forums.

No other mods besides this one were showing up in the stacktrace, so I thought I'd file an issue here.

**Comment by yrsegal** [comment]
looks like an old version of Psi. The bug is fixed in later versions.

**Comment by Robijnvogel** [comment]
Oki, sorry to bother you then!

**Comment by Robijnvogel** [comment]
This is the latest build for Minecraft 1.8.9 though, so don't you support that version anymore?

**Comment by yrsegal** [comment]
I think 1.9 is the only supported version at this point.

**Comment by Robijnvogel** [comment]
But why? Forge for 1.9 isn't even stable yet!

**Comment by JRoffel** [comment]
Well, first of all, psi is only in beta, so not fully stable yet either, also, just because something isn't stable yet, doesn't mean we can't say "we'll not support older versions of this mod"

**Comment by Robijnvogel** [comment]
And because this mod is beta, it would be very practical to develop it on the version where its greatest player base is situated, because the version has quite some other mods as well. a.k.a. MC 1.8.9

I'm not telling you what you can and can't say or do. I'm just arguing what would be wise to say and do. Do with my argument(s) whatever you want.
