### ISSUE TITLE
0% on world loading

### ISSUE THREAD

**Issue by aolko** [Vazkii/Psi#167]
![fig 1](http://i.imgur.com/NaxKPMK.png)
[logs](http://paste.ee/p/yg1ur)

**Comment by williewillus** [comment]
vanilla 1.9 thing

**Comment by williewillus** [comment]
Actually on closer look at the log, looks like a Forge issue? but not related to the 0% screen, it's just a crash

**Comment by aolko** [comment]
Yup, it actually works fine w/o Psi

**Comment by JRoffel** [comment]
Side note: your version of Java is outdated
