### ISSUE TITLE
1.9-beta-30 crashes dedicated forge server 1.9 build 1821 on startup

### ISSUE THREAD

**Issue by kreezxil** [Vazkii/Psi#169]
Issue: psi-1.9-beta-30 crashes dedicated forge server 1.9 build 1821 on startup

crash report:
https://gist.github.com/3d07b333d744fe46cdfeabd3322fc43d

fml server latest:
https://gist.github.com/cc9290708d811a06cc70e40e8073e5a4

**Comment by williewillus** [comment]
forge just did another refactor
