### ISSUE TITLE
Crash when using closest to focal point. (Psi-beta-11, FTB unstable 3.0.27)

### ISSUE THREAD

**Issue by ewanm89** [Vazkii/Psi#17]
Crash with use of a spell that smites the closest enemy from where projectile is fired with ~3 mobs equidistant from where I fired.

Spell:     {spellName:"Total Smiting",uuidMost:-8077247943535867938L,validSpell:1b,spellList: [0:{spellPosX:2,spellData:{spellKey:"selectorFocalPoint",params:{}},spellPosY:2},1:{spellPosX:3,spellData:{spellKey:"connector",params:{psi.spellparam.target:2}},spellPosY:1},2:{spellPosX:3,spellData:{spellKey:"operatorEntityPosition",params:{psi.spellparam.target:3}},spellPosY:2},3:{spellPosX:3,spellData:{spellKey:"trickBlaze",params:{psi.spellparam.position:4}},spellPosY:3},4:{spellPosX:4,spellData:{spellKey:"selectorNearbyEnemies",params:{psi.spellparam.radius:4,psi.spellparam.position:3}},spellPosY:1},5:{spellPosX:4,spellData:{spellKey:"operatorClosestToPoint",params:{psi.spellparam.position:3,psi.spellparam.target:1}},spellPosY:2},6:{spellPosX:4,spellData:{spellKey:"operatorEntityPosition",params:{psi.spellparam.target:1}},spellPosY:3},7:{spellPosX:4,spellData:{spellKey:"trickSmite",params:{psi.spellparam.position:1}},spellPosY:4},8:{spellPosX:5,spellData:{spellKey:"constantNumber",params:{},constantValue:"32"},spellPosY:1},9:{spellPosX:5,spellData:{spellKey:"trickDebug",params:{psi.spellparam.number:0,psi.spellparam.target:3}},spellPosY:2},10:{spellPosX:5,spellData:{spellKey:"trickSmite",params:{psi.spellparam.position:3}},spellPosY:3}],uuidLeast:-7601023520482615172L}

Crash log:

---- Minecraft Crash Report ----

    WARNING: coremods are present:
      NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
      thaumicinfusion (ThaumicInfusion-1.8.9-4.78.jar)
      LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
      ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
      FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
      dsurroundcore (DynamicSurroundings-1.8.9-2.0.3.2.jar)
      LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
    Contact their authors BEFORE contacting forge

    // Everything's going to plan. No, really, that was supposed to happen.

    Time: 12/02/16 19:27
    Description: Ticking entity

    java.lang.NullPointerException: Ticking entity
        at vazkii.psi.common.spell.operator.entity.PieceOperatorClosestToPoint.execute(PieceOperatorClosestToPoint.java:48)
        at vazkii.psi.api.spell.CompiledSpell$Action.execute(CompiledSpell.java:91)
        at vazkii.psi.api.spell.CompiledSpell.execute(CompiledSpell.java:57)
        at vazkii.psi.api.spell.CompiledSpell.safeExecute(CompiledSpell.java:67)
        at vazkii.psi.common.entity.EntitySpellProjectile.cast(EntitySpellProjectile.java:189)
        at vazkii.psi.common.entity.EntitySpellProjectile.func_70184_a(EntitySpellProjectile.java:173)
        at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:204)
        at vazkii.psi.common.entity.EntitySpellProjectile.func_70071_h_(EntitySpellProjectile.java:130)
        at net.minecraft.world.World.func_72866_a(World.java:1860)
        at net.minecraft.world.World.func_72870_g(World.java:1829)
        at net.minecraft.world.World.func_72939_s(World.java:1661)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
        at net.minecraft.client.main.Main.main(SourceFile:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

    A detailed walkthrough of the error, its code path and all known details is as follows:
    ---------------------------------------------------------------------------------------

    -- Head --
    Stacktrace:
        at vazkii.psi.common.spell.operator.entity.PieceOperatorClosestToPoint.execute(PieceOperatorClosestToPoint.java:48)
        at vazkii.psi.api.spell.CompiledSpell$Action.execute(CompiledSpell.java:91)
        at vazkii.psi.api.spell.CompiledSpell.execute(CompiledSpell.java:57)
        at vazkii.psi.api.spell.CompiledSpell.safeExecute(CompiledSpell.java:67)
        at vazkii.psi.common.entity.EntitySpellProjectile.cast(EntitySpellProjectile.java:189)
        at vazkii.psi.common.entity.EntitySpellProjectile.func_70184_a(EntitySpellProjectile.java:173)
        at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:204)
        at vazkii.psi.common.entity.EntitySpellProjectile.func_70071_h_(EntitySpellProjectile.java:130)
        at net.minecraft.world.World.func_72866_a(World.java:1860)
        at net.minecraft.world.World.func_72870_g(World.java:1829)

    -- Entity being ticked --
    Details:
        Entity Type: Psi.psi:spellProjectile (vazkii.psi.common.entity.EntitySpellProjectile)
        Entity ID: 171593
        Entity Name: entity.Psi.psi:spellProjectile.name
        Entity's Exact location: -325.68, 64.62, 56.20
        Entity's Block location: -326.00,64.00,56.00 - World: (-326,64,56), Chunk: (at 10,4,8 in -21,3; contains blocks -336,0,48 to -321,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
        Entity's Momentum: 1.43, -0.87, 1.47
        Entity's Rider: ~~ERROR~~ NullPointerException: null
        Entity's Vehicle: ~~ERROR~~ NullPointerException: null
    Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1661)

    -- Affected level --
    Details:
        Level name: MpServer
        All players: 1 total; [EntityPlayerSP['ewanm89'/4021, l='MpServer', x=-327.46, y=64.00, z=54.17]]
        Chunk stats: MultiplayerChunkCache: 2025, 2025
        Level seed: 0
        Level generator: ID 00 - default, ver 1. Features enabled: false
        Level generator options: 
        Level spawn location: -132.00,64.00,256.00 - World: (-132,64,256), Chunk: (at 12,4,0 in -9,16; contains blocks -144,0,256 to -129,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
        Level time: 576988 game time, 690148 day time
        Level dimension: 0
        Level storage version: 0x00000 - Unknown?
        Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
        Forced entities: 69 total; [EntityZombie['Zombie'/165634, l='MpServer', x=-323.41, y=63.00, z=60.03], EntityAuraNode['Aura Node'/3855, l='MpServer', x=-227.50, y=29.50, z=126.50], EntityAuraNode['Aura Node'/3856, l='MpServer', x=-224.50, y=82.50, z=146.50], EntitySpider['Spider'/147992, l='MpServer', x=-305.50, y=71.00, z=98.50], EntityCreeper['Creeper'/171298, l='MpServer', x=-354.50, y=66.00, z=96.50], EntitySkeleton['Skeleton'/165664, l='MpServer', x=-303.50, y=34.00, z=98.50], EntityAuraNode['Aura Node'/4131, l='MpServer', x=-358.50, y=65.50, z=157.50], EntitySpider['Spider'/120619, l='MpServer', x=-376.22, y=69.00, z=120.44], EntitySheep['Sheep'/4147, l='MpServer', x=-405.22, y=62.63, z=123.50], EntitySquid['Squid'/134718, l='MpServer', x=-325.91, y=53.63, z=4.13], EntityZombie['Zombie'/162110, l='MpServer', x=-277.50, y=64.00, z=37.50], EntityBat['Bat'/161602, l='MpServer', x=-361.58, y=40.30, z=109.67], EntitySpider['Spider'/164171, l='MpServer', x=-322.00, y=62.69, z=60.75], EntityCreeper['Creeper'/164939, l='MpServer', x=-402.50, y=63.00, z=24.50], EntitySkeleton['Skeleton'/164937, l='MpServer', x=-334.50, y=24.00, z=78.50], EntitySpellProjectile['entity.Psi.psi:spellProjectile.name'/171593, l='MpServer', x=-325.68, y=64.62, z=56.20], EntitySquid['Squid'/134735, l='MpServer', x=-380.38, y=53.00, z=-5.66], EntitySkeleton['Skeleton'/166481, l='MpServer', x=-332.50, y=32.00, z=104.50], EntityCreeper['Creeper'/167255, l='MpServer', x=-332.50, y=53.00, z=107.50], EntityZombie['Zombie'/144471, l='MpServer', x=-402.50, y=24.00, z=93.91], EntityZombie['Zombie'/162652, l='MpServer', x=-364.09, y=61.38, z=60.38], EntitySkeleton['Skeleton'/141414, l='MpServer', x=-331.50, y=23.00, z=50.50], EntityBat['Bat'/161903, l='MpServer', x=-301.88, y=10.81, z=99.55], EntityCreeper['Creeper'/132717, l='MpServer', x=-327.56, y=65.00, z=77.25], EntitySpider['Spider'/165235, l='MpServer', x=-386.50, y=65.00, z=40.50], EntityCreeper['Creeper'/166259, l='MpServer', x=-313.50, y=28.00, z=85.50], EntityCreeper['Creeper'/165498, l='MpServer', x=-399.50, y=16.00, z=100.50], EntityCreeper['Creeper'/137083, l='MpServer', x=-365.50, y=67.00, z=111.50], EntityZombie['Zombie'/165500, l='MpServer', x=-347.22, y=67.00, z=100.69], EntityBat['Bat'/141953, l='MpServer', x=-257.97, y=19.47, z=69.19], EntitySpider['Spider'/143236, l='MpServer', x=-376.50, y=45.00, z=18.50], EntityAuraNode['Aura Node'/4234, l='MpServer', x=-443.50, y=17.50, z=103.50], EntityAuraNode['Aura Node'/4235, l='MpServer', x=-213.50, y=63.50, z=3.50], EntityZombie['Zombie'/141452, l='MpServer', x=-322.50, y=15.00, z=116.50], EntityAuraNode['Aura Node'/4251, l='MpServer', x=-196.50, y=70.50, z=22.50], EntityEnderman['Enderman'/165785, l='MpServer', x=-392.50, y=64.00, z=100.50], EntityZombie['Zombie'/171417, l='MpServer', x=-404.50, y=16.00, z=-14.50], EntityAuraNode['Aura Node'/4260, l='MpServer', x=-380.50, y=64.50, z=-86.50], EntityAuraNode['Aura Node'/4261, l='MpServer', x=-286.50, y=24.50, z=-86.50], EntitySquid['Squid'/134565, l='MpServer', x=-318.31, y=55.16, z=21.56], EntityCreeper['Creeper'/167339, l='MpServer', x=-307.50, y=32.00, z=111.50], EntityZombie['Zombie'/164520, l='MpServer', x=-381.50, y=55.00, z=126.50], EntityAuraNode['Aura Node'/4267, l='MpServer', x=-438.50, y=63.50, z=-73.50], EntitySkeleton['Skeleton'/164521, l='MpServer', x=-286.59, y=16.00, z=74.69], EntityPig['Pig'/4028, l='MpServer', x=-315.02, y=62.21, z=41.39], EntityZombie['Zombie'/143037, l='MpServer', x=-374.66, y=69.00, z=118.34], EntityZombie['Zombie'/163010, l='MpServer', x=-404.50, y=70.00, z=82.50], EntitySpider['Spider'/136384, l='MpServer', x=-323.22, y=64.00, z=58.47], EntityChicken['Chicken'/4037, l='MpServer', x=-373.63, y=65.00, z=87.69], EntitySkeleton['Skeleton'/163015, l='MpServer', x=-360.50, y=63.00, z=129.50], EntityZombie['Zombie'/131780, l='MpServer', x=-324.74, y=64.00, z=55.97], EntityBat['Bat'/141252, l='MpServer', x=-278.26, y=20.54, z=70.51], EntitySheep['Sheep'/4038, l='MpServer', x=-366.63, y=68.00, z=121.97], EntityPig['Pig'/4045, l='MpServer', x=-391.09, y=63.00, z=24.97], EntityCreeper['Creeper'/137167, l='MpServer', x=-344.50, y=64.00, z=118.50], EntitySpider['Spider'/135375, l='MpServer', x=-355.50, y=64.00, z=129.50], EntityCreeper['Creeper'/139217, l='MpServer', x=-389.50, y=64.00, z=34.50], EntityBat['Bat'/166100, l='MpServer', x=-323.69, y=15.63, z=117.25], EntityItem['item.item.egg'/121566, l='MpServer', x=-368.94, y=68.00, z=97.13], EntityBat['Bat'/165344, l='MpServer', x=-350.59, y=39.22, z=113.16], EntityBat['Bat'/169696, l='MpServer', x=-311.50, y=26.84, z=87.56], EntitySkeleton['Skeleton'/166625, l='MpServer', x=-316.50, y=25.00, z=74.50], EntityChicken['Chicken'/4071, l='MpServer', x=-402.63, y=66.00, z=65.59], EntityPig['Pig'/4072, l='MpServer', x=-391.13, y=68.00, z=82.28], EntityAuraNode['Aura Node'/4077, l='MpServer', x=-403.50, y=70.50, z=89.50], EntitySheep['Sheep'/4079, l='MpServer', x=-379.47, y=66.00, z=101.47], EntityPlayerSP['ewanm89'/4021, l='MpServer', x=-327.46, y=64.00, z=54.17], EntityCreeper['Creeper'/134897, l='MpServer', x=-330.06, y=27.00, z=85.50], EntityAuraNode['Aura Node'/3830, l='MpServer', x=-282.50, y=78.50, z=157.50]]
        Retry entities: 0 total; []
        Server brand: fml,forge
        Server type: Integrated singleplayer server
    Stacktrace:
        at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
        at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
        at net.minecraft.client.main.Main.main(SourceFile:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

    -- System Details --
    Details:
        Minecraft Version: 1.8.9
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 1.8.0_25, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 805882576 bytes (768 MB) / 3569352704 bytes (3404 MB) up to 3817865216 bytes (3641 MB)
        JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
        IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
        FML: MCP 9.19 Powered by Forge 11.15.1.1738 78 mods loaded, 78 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
        UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1738.jar) 
        UCHIJAAAA   Forge{11.15.1.1738} [Minecraft Forge] (forge-1.8.9-11.15.1.1738.jar) 
        UCHIJAAAA   Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
        UCHIJAAAA   aura{unspecified} [Aura Cascade] (AuraCascade-1.8.8-v0.2.2a.jar) 
        UCHIJAAAA   bagginses{2.1.5b} [Bagginses] (Bagginses-1.8.9-2.1.5b.jar) 
        UCHIJAAAA   BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
        UCHIJAAAA   BetterThanBunnies{1.8.9-1.0.1} [BetterThanBunnies] (BetterThanBunnies-1.8.9-1.0.1.jar) 
        UCHIJAAAA   BloodMagic{1.8.9-2.0.0-253-ss} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-253-ss.jar) 
        UCHIJAAAA   bookshelfapi{2.3.0} [Bookshelf] (Bookshelf-1.8.9-2.3.0.jar) 
        UCHIJAAAA   Botania{r1.8-249} [Botania] (Botania.r1.8-248-MC1.8-779cc76.jar) 
        UCHIJAAAA   BuildCraft|Core{7.2.0-pre10} [BuildCraft] (buildcraft-7.2.0-pre10.jar) 
        UCHIJAAAA   BuildCraft|Transport{7.2.0-pre10} [BC Transport] (buildcraft-7.2.0-pre10.jar) 
        UCHIJAAAA   BuildCraft|Factory{7.2.0-pre10} [BC Factory] (buildcraft-7.2.0-pre10.jar) 
        UCHIJAAAA   BuildCraft|Silicon{7.2.0-pre10} [BC Silicon] (buildcraft-7.2.0-pre10.jar) 
        UCHIJAAAA   BuildCraft|Robotics{7.2.0-pre10} [BC Robotics] (buildcraft-7.2.0-pre10.jar) 
        UCHIJAAAA   BuildCraft|Energy{7.2.0-pre10} [BC Energy] (buildcraft-7.2.0-pre10.jar) 
        UCHIJAAAA   BuildCraft|Builders{7.2.0-pre10} [BC Builders] (buildcraft-7.2.0-pre10.jar) 
        UCHIJAAAA   buildingbrickscompatvanilla{1.8.9-1.3.1} [Building Bricks Vanilla Compat] (BuildingBricks-1.8.9-1.3.1.jar) 
        UCHIJAAAA   buildingbricks{1.8.9-1.3.1} [Building Bricks] (BuildingBricks-1.8.9-1.3.1.jar) 
        UCHIJAAAA   Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
        UCHIJAAAA   mcmultipart{1.0.6} [MCMultiPart] (MCMultiPart-1.0.6-universal.jar) 
        UCHIJAAAA   CharsetLib{0.2.1} [‽] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
        UCHIJAAAA   CharsetTweaks{0.2.1} [*] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
        UCHIJAAAA   CharsetWires{0.2.1} [+] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
        UCHIJAAAA   CharsetAudio{0.2.1} [♫] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
        UCHIJAAAA   CharsetStorage{0.2.1} [#] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
        UCHIJAAAA   CharsetPipes{0.2.1} [|] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
        UCHIJAAAA   CharsetGates{0.2.1} [&] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
        UCHIJAAAA   chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
        UCHIJAAAA   chiselsandbits{mc1.8.9-v1.8.10} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.10.jar) 
        UCHIJAAAA   compasscoords{1.8.9-0.2.6} [Compass Co-ords] (CompassCoords-1.8.9-0.2.6.jar) 
        UCHIJAAAA   ComputerCraft{1.78} [ComputerCraft] (ComputerCraft1.78.jar) 
        UCHIJAAAA   craftingtweaks{3.0.41} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.41.jar) 
        UCHIJAAAA   crafttweaker{3.0.0} [crafttweaker] (CraftTweaker-Customized-1.8.8-3.0.1.jar) 
        UCHIJAAAA   CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
        UCHIJAAAA   dsurround{2.0.3.2} [Dynamic Surroundings] (DynamicSurroundings-1.8.9-2.0.3.2.jar) 
        UCHIJAAAA   ShetiPhianCore{3.1.0} [ShetiPhian-Core] (ShetiPhianCore-1.8.9-3.1.0.jar) 
        UCHIJAAAA   EnderTanks{1.2.1} [EnderTanks] (EnderTanks-1.8.9-1.2.1.jar) 
        UCHIJAAAA   ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.3.jar) 
        UCHIJAAAA   fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
        UCHIJAAAA   flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.6.jar) 
        UCHIJAAAA   Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
        UCHIJAAAA   FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
        UCHIJAAAA   FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
        UCHIJAAAA   furnus{1.7} [Furnus] (Furnus-1.8.9-1.7.jar) 
        UCHIJAAAA   graves{1.8.9-b38-universal} [Graves Mod] (graves-1.8.9-b38-universal.jar) 
        UCHIJAAAA   hopperducts{1.4.6} [Hopper Ducts] (hopperducts-mc1.8.8-1.4.6.jar) 
        UCHIJAAAA   k4lib{1.8.9-1.0.14} [K4Lib] (k4lib-1.8.9-1.0.14-universal.jar) 
        UCHIJAAAA   HydCraft{1.8.9-3.1.57} [Hydraulicraft] (HydCraft-1.8.9-3.1.57-universal.jar) 
        UCHIJAAAA   IGWMod{1.2.3-3} [In-Game wiki Mod] (IGW-Mod-1.8.9-1.2.3-3-universal.jar) 
        UCHIJAAAA   intangible{0.0.21} [Intangible] (intangible-1.8.9-0.0.21.jar) 
        UCHIJAAAA   inventorysorter{0.7.4+26} [Simple Inventory sorting] (inventorysorter-1.8.9-0.7.4+26.jar) 
        UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
        UCHIJAAAA   JEI{2.25.11.150} [Just Enough Items] (jei_1.8.9-2.25.11.150.jar) 
        UCHIJAAAA   Thaumcraft{5.1.6} [Thaumcraft] (Thaumcraft-1.8.9-5.1.6.jar) 
        UCHIJAAAA   JEIAddons{0.11.2.56} [Just Enough Items Addons] (JEIAddons_1.8.9-0.11.2.56.jar) 
        UCHIJAAAA   journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
        UCHIJAAAA   jeresources{0.3.1} [Just Enough Resources] (JustEnoughResources-1.8.9-0.3.1.jar) 
        UCHIJAAAA   llor{1.0.4-mc1.8.8} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.4-mc1.8.8.jar) 
        UCHIJAAAA   mantle{1.8.9-0.7.jenkins72} [Mantle] (Mantle-1.8.9-0.7.jar) 
        UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
        UCHIJAAAA   Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar) 
        UCHIJAAAA   MouseTweaks{2.6.0} [Mouse Tweaks] (MouseTweaks-2.6.0-mc1.8.9.jar) 
        UCHIJAAAA   neotech{2.3.4} [NeoTech] (NeoTech-1.8.9-2.3.4.jar) 
        UCHIJAAAA   fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
        UCHIJAAAA   playerrugs{0.0.1} [Player Rugs] (PlayerRugs-1.8.8-1.2.0.jar) 
        UCHIJAAAA   PneumaticCraft{1.13.6} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.6-universal.jar) 
        UCHIJAAAA   progressiveautomation{1.6.33} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.33.jar) 
        UCHIJAAAA   Psi{beta-11} [Psi] (Psi-beta-11.jar) 
        UCHIJAAAA   RandomThings{3.6.2} [Random Things] (RandomThings-MC1.8.9-3.6.2.jar) 
        UCHIJAAAA   ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.8-1.4.jar) 
        UCHIJAAAA   rftools{4.22beta17} [RFTools] (rftools-1.8.9-4.22beta17.jar) 
        UCHIJAAAA   simpleretrogen{2.2.2+3} [Simple Retrogen] (simpleretrogen-1.8.9-2.2.2+3.jar) 
        UCHIJAAAA   StorageDrawers{1.8.9-2.3.4} [Storage Drawers] (StorageDrawers-1.8.9-2.3.4.jar) 
        UCHIJAAAA   tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct] (TConstruct-1.8.9-2.0.2.jar) 
        UCHIJAAAA   thaumicinfusion{4.78} [Thaumic Infusion] (ThaumicInfusion-1.8.9-4.78.jar) 
        UCHIJAAAA   wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
        Loaded coremods (and transformers): 
    NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
      net.fybertech.nwr.NowWithRendering
    thaumicinfusion (ThaumicInfusion-1.8.9-4.78.jar)
      drunkmafia.thaumicinfusion.common.asm.BlockTransformer
      drunkmafia.thaumicinfusion.common.asm.WorldTransformer
    LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
      lumien.randomthings.asm.ClassTransformer
    ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
      
    FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
      com.olafski.fastleafdecay.FldTransformer
    dsurroundcore (DynamicSurroundings-1.8.9-2.0.3.2.jar)
      org.blockartistry.mod.DynSurround.asm.Transformer
    LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
      lumien.resourceloader.asm.ClassTransformer
        GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.75' Renderer: 'GeForce GTX 980/PCIe/SSE2'
        Pulsar/tconstruct loaded Pulses: 
            - TinkerCommons (Enabled/Forced)
            - TinkerWorld (Enabled/Not Forced)
            - TinkerTools (Enabled/Not Forced)
            - TinkerSmeltery (Enabled/Not Forced)
            - TinkerGadgets (Enabled/Not Forced)
            - TinkerOredict (Enabled/Forced)
            - TinkerIntegration (Enabled/Forced)
            - TinkerFluids (Enabled/Forced)
            - TinkerMaterials (Enabled/Forced)
            - chiselsandbitsIntegration (Enabled/Not Forced)
            - TinkerDebug (Enabled/Not Forced)

        Launched Version: forge-11.15.1.1738
        LWJGL: 2.9.4
        OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.5.0 NVIDIA 361.75, NVIDIA Corporation
        GL Caps: Using GL 1.3 multitexturing.
    Using GL 1.3 texture combiners.
    Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
    Shaders are available because OpenGL 2.1 is supported.
    VBOs are available because OpenGL 1.5 is supported.

        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'fml,forge'
        Type: Client (map_client.txt)
        Resource Packs: 
        Current Language: English (US)
        Profiler Position: N/A (disabled)
        CPU: 12x Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz

**Comment by ewanm89** [comment]
Also to note, the spell has 2 smite and an ignite trick on the closest entity, Could first trick have killed the mob before second trick fired causing a null pointer in the entity list?

**Comment by yrsegal** [comment]
Isn't smite damage calculation after the spell executes?

**Comment by ewanm89** [comment]
Yrsegal, from what I can tell from reading the code, the null pointer exception was during an iteration of the list to calculate the closest to the point. I don't know of any other possible reason the list might suddenly have a null entry in it? Maybe vazkii can work it out? Also the death may be from fire from a previous invocation. After all I was spamming it at the mobs chasing me at the time..,

**Comment by yrsegal** [comment]
Shouldn't any exception in checking just be a spellCompilationException,
though?

**Comment by yrsegal** [comment]
Ok, here are the two possibilities. A null entity, which Vazkii should check for, and a null position which should throw spellCompilationException.

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Psi/commit/3cc99ea30603e0955c5a96e08a1c4e06676dd371
