### ISSUE TITLE
Curse has released your latest beta-31 but not forge 1826 it needs.

### ISSUE THREAD

**Issue by SudzBud** [Vazkii/Psi#170]
I just got beta-31, but don't see a way to update the profile to forge 1826. Is there a manual way to do this?

**Comment by yrsegal** [comment]
this... isn't a Psi issue?

**Comment by SudzBud** [comment]
No it isn't. It is a curse issue. I'm sorry I thought the project might like to know as it affects the Mod...

**Comment by yrsegal** [comment]
could you close this, as this doesn't actually pertain to Psi?

**Comment by SudzBud** [comment]
Rude much

**Comment by williewillus** [comment]
That isn't being rude... the issue does not belong here and thus should be closed >.<
