### ISSUE TITLE
[Minor] The Entity Position operator does not give exact position.

### ISSUE THREAD

**Issue by Mach12** [Vazkii/Psi#173]
At least for player entities, it gives head position instead.

While this does facilitate raycasting, the position of a player is at its feet, and thus obtaining an exact height relatively to a Player is harder.

This might be just misbehavior or simply intended, but in both cases it is not stated in the in-game doc and got me to misprogram quite a few spells.

**Comment by yrsegal** [comment]
That is the intended behavior, I believe.

**Comment by Mach12** [comment]
If so, it should be mentioned in the in-game doc. C

**Comment by yrsegal** [comment]
I mean, your position is where your eyes are, though...

**Comment by Mach12** [comment]
No, it's not. I's where your feet are. The bottom of your feet.

**Comment by yrsegal** [comment]
that's not how it's internally stored for players these days.

**Comment by Mach12** [comment]
Debug info begs to differ.

**Comment by yrsegal** [comment]
internally, not in nbt...

**Comment by williewillus** [comment]
@yrsegal you're incorrect. all entities are stored using their feet position

**Comment by yrsegal** [comment]
I've gotten debug info showing the player y position as in the head in 1.9. That may have changed since the start, but that's what I remember.

**Comment by Mach12** [comment]
Actually as of 1.9 both eye level and feet level coordinates are shown

**Comment by williewillus** [comment]
it shows both feet and eye, but actual entity.posX/Y/Z is always feet

**Comment by Mach12** [comment]
And again my point still stands: if the way the Position operator works changes depending on entity type, this is misleading and definitely not documented in the mod.

**Comment by yrsegal** [comment]
It apparently does now, and it is misleading, I agree. From psi:

```java
Vector3 vec = Vector3.fromEntity(e);
if(e instanceof EntityPlayer) {
    vec.add(0.0D, (double)e.getEyeHeight(), 0.0D);
}

return vec;
```

**Comment by Mach12** [comment]
My bet is that it was to facilitate raycasting because it is unlocked early.
Easiest fix might be either to add a `Constant: Eye height` or `Operator: Entity feet`.
The latter might be mislabeled but that is more or less what it could be.
