### ISSUE TITLE
Psimetal shovel cannot create path blocks

### ISSUE THREAD

**Issue by Mach12** [Vazkii/Psi#175]
As of 1.9, path blocks can be created by right clicking grass or dirt with any shovel...

...any but the psimetal shovel. It might be an error on Forge's part regarding default shovel behavior but I don't know about that.

**Comment by AlterAkima** [comment]
ItemPsimetalShovel does not extends ItemSpade, not really an error.

**Comment by yrsegal** [comment]
It can, however, be fixed. You can add the right click behavior manually.
