### ISSUE TITLE
OutOfBounds crash when levelling up

### ISSUE THREAD

**Issue by Nova001Sol** [Vazkii/Psi#176]
My game crashed twice so far. Both times it stopped just after I gained a level. The Psi tutorial menu and CAD have been bound to my middle mouse button. I did not crash prior to rebinding. I did not crash when opening the CAD, nor when opening the tutorial menu.

Crashlog: http://pastebin.com/DY11DUKd
Forge Log: http://pastebin.com/zYyhnRvM

**Comment by yrsegal** [comment]
as a temporary fix, unbind the psi button from the middle mouse button. This is because vazkii never planned for there to be a mouse button as the Psi key.

**Comment by Nova001Sol** [comment]
Yeah, I figured. Still reported it though. After all, a crash is a crash.

**Comment by yrsegal** [comment]
yeah, it's definitely a problem, but that's just a temporary workaround so you can actually play. :P

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Psi/commit/b985d8bf66683ea908f52f9a8299c66576ec0bf4
