### ISSUE TITLE
Visual bug in 1.9

### ISSUE THREAD

**Issue by Scorpio185** [Vazkii/Psi#179]
this is just a Visual bug, When i press "F" to swap main-hand with off-hand while i have CAD in hand, it appears to be in both hands
<a href="http://imgur.com/cHpHsKZ"><img src="http://i.imgur.com/cHpHsKZ.png" title="source: imgur.com" /></a>

**Comment by littledan45** [comment]
It will also do it if you swap it with an item in your hotbar.
example you have the cad in hotbar position 2 and you swap it with a sword in position 4 with a keyboard shortcut it wont update the textures until you click on the sword
