### ISSUE TITLE
No such method found error with deobf

### ISSUE THREAD

**Issue by ProfessorProspector** [Vazkii/Psi#181]
I've reported this before, and it was closed without word. Anytime when I use the psi deobf jar in a dev environment, I get this error: `net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: vazkii.psi.common.block.BlockCADAssembler.setStepSound(Lnet/minecraft/block/SoundType;)Lnet/minecraft/block/Block;`

**Comment by JRoffel** [comment]
If it was closed without word, that most likely means we're either not fixing it, or it's not our problem

**Comment by ProfessorProspector** [comment]
There's no point in even having a developer jar if it's broken and not going to be fixed then. Was really hoping on adding some psi compat ;(

**Comment by williewillus** [comment]
update forge

**Comment by ProfessorProspector** [comment]
Actually Psi needs to update. We're 9 versions ahead

**Comment by JRoffel** [comment]
Then downgrade forge

**Comment by ProfessorProspector** [comment]
Cant, other mods like JEI need newer forge.

**Comment by williewillus** [comment]
Yeah unfortunately vaz has exams right now, so it'll have to wait a bit
