### ISSUE TITLE
Cross-mod Duplication Bug with Botania

### ISSUE THREAD

**Issue by Nova001Sol** [Vazkii/Psi#183]
I am running the most recent versions of Psi and Botania 1.9. When I break any sort of non-worldgen flower with a basic 'break block' spell I am given back two flowers instead of one. This only occurs with non-worldgen flowers, all other blocks drop the expected number of items. When broken by hand the affected flowers drop the expected number of items.

I shall post this issue on the Botania Github as well.

This is the spell I have used:

{spellName:"Demolish",uuidMost:-6237090200277201185L,validSpell:1b,spellList:[0:{data:{params:{_target:2},key:"operatorEntityPosition"},x:4,y:3},1:{data:{key:"selectorCaster"},x:4,y:4},2:{data:{params:{_ray:2,_max:0,_position:3},key:"operatorVectorRaycast"},x:5,y:3},3:{data:{params:{_target:3},key:"operatorEntityLook"},x:5,y:4},4:{data:{params:{_position:3},key:"trickBreakBlock"},x:6,y:3}],uuidLeast:-8605094596199879615L}

**Comment by williewillus** [comment]
update forge

**Comment by Nova001Sol** [comment]
I'm running the latest version, so that won't solve a thing.

**Comment by williewillus** [comment]
Actually this is a botania bug, I will fix. you can close this one

**Comment by Nova001Sol** [comment]
'kay, thanks.
