### ISSUE TITLE
Suggestion: require shift-right click on Spell Programmer to update spell in held CAD/Psimetal Tool

### ISSUE THREAD

**Issue by SoullessWaffle** [Vazkii/Psi#185]
Sometimes when I right click to try to open the Spell Programmer, I accidentally overwrite the active spell in my CAD because I don't notice I have it equipped.

If Psi were to offer an option to require shift-right clicking to update the active spell in the held CAD or Psimetal Tool, this could hopefully be avoided.

**Comment by Nova001Sol** [comment]
I'd like this as well. There's nothing more frustrating than accidentally overwriting the result of over half an hour of work with a 'place water' spell.
