### ISSUE TITLE
Feature request: Single-target Exodus trick

### ISSUE THREAD

**Issue by Nova001Sol** [Vazkii/Psi#187]
I'd basically like a single-target Exodus. You know, like Mass Exodus but without the 'Mass' part. This is mostly for when you want to seperate things. Or pull your friend out of a zombie swarm. Or off a ledge. Anyway, single-target version of Mass Exodus. Not much else to say about it, really.

Exodus: For when you want to drag one thing instead of all the things in a square mile around the lint that fills your pocket.

**Comment by Inari-Whitebear** [comment]
Isn't that called "add motion"?

**Comment by yrsegal** [comment]
yep. Add motion with a Target entity pos - Your entity pos
