### ISSUE TITLE
Feature request: Allow Infusion tricks to perform lesser infusions

### ISSUE THREAD

**Issue by Nova001Sol** [Vazkii/Psi#189]
I don't know, it just seems strange that I need three slots in my CAD to infuse what I need without swapping out bullets. Instead, I propose the following: allow Infusion to infuse redstone and gold, both for the cost of performing a gold infusion, and allow Greater Infusion to infuse all three, again for the cost of infusing diamond. The trick that turns coal and quartz to ebony and ivory can stay as it is, you don't really need that one too often. Plus, that looks more like transmutation that infusion.

**Comment by Inari-Whitebear** [comment]
I went with just having an infusion CAD for this.
