### ISSUE TITLE
Break Block and fluids

### ISSUE THREAD

**Issue by zlyfire** [Vazkii/Psi#192]
I've noticed the Trick: Break Block Sequence does not break water/lava source blocks. However, it *does* break fluid source blocks of fluids from other mods. I figure it probably shouldn't do that either; isn't there a way to get a list of registered fluids from Forge and tell the trick to not break these blocks?

**Comment by yrsegal** [comment]
check for BlockLiquid prolly

**Comment by Vazkii** [comment]
It does check for BlockLiquid.
