### ISSUE TITLE
[1.9] NullPointerException

### ISSUE THREAD

**Issue by Inari-Whitebear** [Vazkii/Psi#195]
Was not really doing anything in particular. Was a new world I did some creative stuff with charset in. Didn't even use psi at all. Then I looked into an rftools crafter when I suddenly crashed shortly after:

http://paste.ee/p/hSvXd

**Comment by DrasticDemise** [comment]
While I am unable to load your paste, this seems to be the same crash that I had. I was simply running around the world and crashed with an exception during server tick loop. http://pastebin.com/4MZLHmAX

Only lines that hint at the problem are the following:
 at vazkii.psi.common.core.handler.PlayerDataHandler.cleanup(PlayerDataHandler.java:111)
    at vazkii.psi.common.core.handler.PlayerDataHandler$EventHandler.onServerTick(PlayerDataHandler.java:140)

**Comment by Inari-Whitebear** [comment]
Yup, same crash, same versions

**Comment by homemmakako** [comment]
I had the same crash. Just uninstalled optifine to see if it has something to do with it. It might be hard to test since I don't know for certain what triggers it, but I'll post any results I may find.

**Comment by Vazkii** [comment]
Fixed by #191
