### ISSUE TITLE
Spell Bullets can't set spell from Spell Programmer

### ISSUE THREAD

**Issue by EnragedRabisu** [Vazkii/Psi#199]
Using the newest version of Psi (Psi-beta-32 on 1.9.4 using Forge version 12.17.0.1909 and Java 1.8.0_91), tested with just Psi and Forge.

I can't seem to get my spell bullets to take spells from the Spell Programmer block. Spell drives work, but spell bullets don't. CADs also make the noise for a successful spell transfer, but with no bullets, it obviously can't store it either.

It looks like you put the code that used to do it into a separate setSpell method in BlockProgrammer that never gets called, and the two that work both have onItemUse methods that call their own setSpell method themselves.

**Comment by Melakion** [comment]
On the plus side, you can shift rt-click your psi gun on it and it will make the doo-doot noise like it set the spell, even though it didn't because you can't put an empty spell bullet in.

**Comment by vongola12324** [comment]
Having same problem(can not get spell from Spell Programmer) :(
