### ISSUE TITLE
Projectile Spell Crash on Servers when using Colorizer

### ISSUE THREAD

**Issue by blazinghydra** [Vazkii/Psi#2]
First discovered on a server running a slightly modified version of FTB Unstable. Tried to reproduce in SP, worked fine and no crash or other issues. 

I then switched to a different server with a clean world running only Psi, JEI and Waila. Recreated the CAD and spell exactly the same as they were on the original, and had the same result - crash on MP, fine on SP. Attached are the settings for the CAD and spell, for your own testing. The spell was cast with a projectile bullet.

After some testing and looking through the crash log, I thought to try it on the server without the blue colorizer. No crash without colorizer installed. Re-tried with a different colorizer and crashed again. Which specific colorizer is used doesn't seem to matter so much as the fact that one is used. Also attached are the server's crash and fml-server-latest log files. If you need any different logs, please let me know.

[crash-2016-02-10_19.58.33-server.txt](https://github.com/Vazkii/Psi/files/125415/crash-2016-02-10_19.58.33-server.txt)

[fml-server-latest.txt](https://github.com/Vazkii/Psi/files/125414/fml-server-latest.txt)

![image](https://cloud.githubusercontent.com/assets/7895931/12959746/bf500a18-d02f-11e5-8b48-3b08d329d1b4.png)

![image](https://cloud.githubusercontent.com/assets/7895931/12959793/0b0b18c6-d030-11e5-9e2e-69a9848a0849.png)

**Comment by TheChronomancer** [comment]
how did you get Psi beta 12?

**Comment by blazinghydra** [comment]
Downloaded source code then compiled myself.

**Comment by TheChronomancer** [comment]
how did you compile it

**Comment by TheChronomancer** [comment]
it wasnt letting me compile it

**Comment by yrsegal** [comment]
just... with gradle?

**Comment by blazinghydra** [comment]
Gradle scripts. If you don't know how, I'm not the person to explain it, and this isn't really the place either. You'd be better looking up a tutorial. I believe Pahimar has one on the EE3 github. Though the usual disclaimers (no guarantee of stability with a dev build, etc, etc) apply.

**Comment by TheChronomancer** [comment]
it gives me an error when compiling

**Comment by blazinghydra** [comment]
Again, this isn't the right forum for troubleshooting gradle, and I'm definitely the wrong person to help with it. All I can suggest is that you make sure you've followed whatever tutorial you ended up using to the letter.

**Comment by yrsegal** [comment]
he didn't cat private.properties.example >> private.properties
