### ISSUE TITLE
Crash when mining with a Psimetal Pickaxe with a spell equipped

### ISSUE THREAD

**Issue by konals** [Vazkii/Psi#20]
[crash-2016-02-13_04.15.28-server.txt](https://github.com/Vazkii/Psi/files/129050/crash-2016-02-13_04.15.28-server.txt)

The spell mines the 8 blocks starting with the block in front of me and continuing 7 blocks East, 8 total blocks.

**Comment by Vazkii** [comment]
Pastebin the spell's export please.

**Comment by konals** [comment]
Sorry for the wait. I also had to dig into NBTExplorer to recreate the spell as exactly as possible, since I only had it in a bullet.

It doesn't crash every single time.

This should be it:

{spellName:"RowMiner2",uuidMost:7177614797163874280L,validSpell:1b,spellList:[0:{spellPosX:1,spellData:{spellKey:"constantNumber",params:{},constantValue:"0"},spellPosY:3},1:{spellPosX:2,spellData:{spellKey:"constantNumber",params:{},constantValue:"8"},spellPosY:2},2:{spellPosX:2,spellData:{spellKey:"operatorVectorConstruct",params:{psi.spellparam.z:3,psi.spellparam.y:2,psi.spellparam.x:1}},spellPosY:3},3:{spellPosX:2,spellData:{spellKey:"constantNumber",params:{},constantValue:"0"},spellPosY:4},4:{spellPosX:3,spellData:{spellKey:"trickBreakInSequence",params:{psi.spellparam.max:2,psi.spellparam.position:4,psi.spellparam.target:3}},spellPosY:3},5:{spellPosX:3,spellData:{spellKey:"constantNumber",params:{},constantValue:"8"},spellPosY:4},6:{spellPosX:4,spellData:{spellKey:"selectorBlockBroken",params:{}},spellPosY:3}],uuidLeast:-5443203206660783758L}
