### ISSUE TITLE
Persistency Not Working

### ISSUE THREAD

**Issue by Dragnier** [Vazkii/Psi#200]
I'm using the 1.9.4 Psi Beta 33 on a Macbook Pro. I see persistent data files in the proper folder. However, I do not get the levels when I start a new world/modpack. I do use separate non-default folders for each modpack I play to keep the saves separated. I am thinking that the persistent data stored in the default minecraft folder is not being accessed properly because I use a different folder for each modpack/profile. It doesn't even transfer the levels even when it is just a new world within the same modpack/profile. Is there any way to fix this?

**Comment by yrsegal** [comment]
Are you clicking c and accepting the new levels before you create psidust?

**Comment by Dragnier** [comment]
I did not see that anywhere in the documentation I could find, but it works. There was literally no listing anywhere I could find, even in the FAQ on the mod website. Perhaps that should have a prompt of some kind added to it so it triggers automatically on world creation if there is persistent data available?

**Comment by Ademius** [comment]
Sorry to bring this back up, but what happens if you didn't hit C and accept the new levels before making psidust? I made the psidust first, and now I seem to be stuck at level 1. (I am running r1.0-35 if it matters)
