### ISSUE TITLE
Conjured blocks getting "stuck."

### ISSUE THREAD

**Issue by PhantomOfAres** [Vazkii/Psi#201]
After conjuring blocks (and light sources,) the blocks seem to be half-there, half-not. The blocks do not render, and you cannot place blocks adjacent to them, or break them. You do collide with them, and they do prevent liquids from flowing. Placing a block where they "should" be seems to force them to show up. Restarting the client does not fix the issue.

Steps to reproduce:

1) Conjure a block
2) Leave the area. I don't know if the chunk needs to be unloaded, but I doubt it is, since I can reproduce by moving a hundred blocks away or so and returning.

[fml-client-latest.txt](https://github.com/Vazkii/Psi/files/283701/fml-client-latest.txt)
![beforeplacing](https://cloud.githubusercontent.com/assets/8773309/15567977/6111951e-22de-11e6-821f-fac44b47bf44.png)
![afterplacing](https://cloud.githubusercontent.com/assets/8773309/15567978/62e9a0de-22de-11e6-9462-665791220c0b.png)

**Comment by tylersuggs** [comment]
Also having this issue. Beta-33.

**Comment by Roxforbraynz** [comment]
Having this issue as well. It happens when you relog on a server (Possibly SSP as well) or leave the area to unload the chunks and come back.

**Comment by murapix** [comment]
Having the same issue here, but with the lights instead. Conjured blocks seem to fail to either load or unload correctly.

**Comment by Chaogomu** [comment]
Same issue with conjured lights.  they vanish, but still emit light. right clicking with a block gets them to show up again. if you don't right click them they vanish completely and the area becomes dark again.

this takes several chunk load/unloads 

Beta-33

**Comment by yrsegal** [comment]
This might be due to the lack of 'getUpdateTag' in TileMod.
