### ISSUE TITLE
Weirdness with exosuits [Beta-33]

### ISSUE THREAD

**Issue by Mii1128** [Vazkii/Psi#204]
Spell selection with exosuits is just completely weird and not really working

If i can pinpoint it further down i will add to this

**Comment by PhantomOfAres** [comment]
Yeah, I think I've seen this too.

So, say I have spell "Float" on my leggings, and "Jump" on my boots. I currently have those spells selected. I hold C with the Exosuit Controller in hand, and select an empty cell (this time, the upper-right.) I check my leggings, they still have "Float" selected (and, indeed, it is being cast.) I press C again, and my boots are now selected. I select "Jump" (the lower-right spell,) and it remains selected on my boots. It seems almost random - no matter what I click, it is unlikely to change, yet it does change sometimes, but not necessarily how I'd expect it to. I can't find a pattern yet, it doesn't seem like axes are flipped or the selector is selecting for the another piece of equipment or anything. Just seems... wrong.

**Comment by Mii1128** [comment]
I got it. Clicking doesnt set anything let go of c to set the spell for the current piece
