### ISSUE TITLE
[Suggestion] Don't Remove Tutorials

### ISSUE THREAD

**Issue by Peach774** [Vazkii/Psi#208]
As someone just learning this mod, it would be great if the tutorial entries were still available in the GUI after you moved on, so that if you forgot how certain mechanics worked, you could always go back to them.

**Comment by AlterAkima** [comment]
They never disappeared once you leveled up.

**Comment by Peach774** [comment]
Yes they do. I'm level 6 and the oldest entry I have is the first level 5 entry.

**Comment by AlterAkima** [comment]
Scroll down the list.

**Comment by Peach774** [comment]
Oh, they're at the bottom. Herp Derp.
