### ISSUE TITLE
Multiple add motions don't seem to work together?

### ISSUE THREAD

**Issue by Darklight-03** [Vazkii/Psi#211]
for example, I was trying to make a long jump boost for the boots, and ended up with this: http://pastebin.com/R3z2DwKW, and it only seemed to make me jump with the first add motion.

Further testing, and even with something as basic as this: http://pastebin.com/1gpqzNdz, there seems to be issues.

In this spell it should cause you to 'jump' twice, however, in single player, it causes you to jump once, and the second add motion never happens? 
in multiplayer, at least on my server, it doesn't ever add motion at all...

Also, is add motion supposed to work on other players? because also on my server, add motion doesn't seem to work on other players.

Am I wrong in that these spells should be working how i want them to?

**Comment by yrsegal** [comment]
Intended, I believe, that it only works in the same direction once. This is because it used to be exponentially cheaper to have multiple add motion tricks pushing you up with the same force as a single one.

**Comment by Darklight-03** [comment]
Should it work on other players though? 
And at least on my server, in multi-player only,  a sleep before an add motion didn't ever add motion at all.
