### ISSUE TITLE
Could not load vanilla model parent 'psi:block/conjured'

### ISSUE THREAD

**Issue by Hypsellis** [Vazkii/Psi#216]
I get this error in the log while Minecraft loading, it doesn't provocate any crash, but I don't think that it's normal. http://pastebin.com/391edp5Z

**Comment by Hypsellis** [comment]
Oh I noticed I got that too later in the log http://pastebin.com/3tQHBirD

**Comment by KingDGrizzle** [comment]
This is probably just the ItemBlock thing.. So, if you would /give yourself that block it'll look messed up, but if you placed it it looks fine.

**Comment by yrsegal** [comment]
why did this get closed? It just requires a single file to fix, and creates unnecessary log baggage.
