### ISSUE TITLE
Grenade bullet not triggering

### ISSUE THREAD

**Issue by doctorkreger** [Vazkii/Psi#219]
Using the latest version for 1.10.2, the grenade never seems to activate.  Any trick i assign to the grenade bullet never actually executes. It just shoots the projectile then it sits there until it despawns. Again, this is with any trick set up.  I was able to use charge bullets with the same spells, which worked as expected.

**Comment by Vascar** [comment]
I am having the same issue in the current build. Any spell that I put on the grenade bullet will never cast, and after about 30 seconds the spell entity despawns.
Minecraft -- 1.10.2
Forge -- 12.18.2.2105
Psi -- r1.0-41
