### ISSUE TITLE
[question] backport possible?

### ISSUE THREAD

**Issue by shadoxxhd** [Vazkii/Psi#225]
do you consider porting the mod back to 1.7.10? many mods I like are still on that version, and I don't quite want to drop them.

if you don't have time for this, how hard would you think it would be for someone with decent general programming experience and knowledge (but nothing minecraft or forge specific) to do it? are there tutorials/interface change documentations?

**Comment by yrsegal** [comment]
It would require extreme amounts of work, and rewrites to the whole system. I'd say it'll never happen, especially since most developers aren't developing for 1.7 anymore.

**Comment by williewillus** [comment]
No and if someone else tried to do it there's so many things that could go,wrong.

Just update <_<
