### ISSUE TITLE
Crash with forge 12.18.1.2027

### ISSUE THREAD

**Issue by the-creamster** [Vazkii/Psi#229]
I'm getting a crash at stage 2 of modpack initializtion http://pastie.org/10920205(PSI)
http://pastie.org/10920210(Quark). When i disabled PSI it referenced Quark instead.

**Comment by ArukaAlter** [comment]
Don't use latest Forge, try a Recommended build.

**Comment by LlubNek** [comment]
Unless this is a change the forge team is likely to revert, Psi still needs to adapt.

**Comment by williewillus** [comment]
There is nothing to "adapt". Psi is doing everything properly
Forge has been making some destabilizing/experimental changes lately

**Comment by TyreForHyre** [comment]
This has been resolved in release 37 of Psi, and consequently in Quark with it's release 49.
