### ISSUE TITLE
Psi forgetting leveling upon relog.

### ISSUE THREAD

**Issue by Insufficient-Charge** [Vazkii/Psi#231]
I am using Minecraft 1.9.4.
I am using the "Block 19, Sponge-Powered" mod pack, please let me know if this is important.
I am not using Optifine.
Judging by the "mod" list in game, I am using Psi v. 1.0 -35. As far as I know, Psi has not teased me in chat to get an update done.
Forge 12.17.0.1968
I am using my own server, run on my own desktop.

Psi seems to forget my levels. Every time I relog, I can't open the spell programmer; and when I press 'C' it says "Levels from previous versions have been found" since I played Psi in 1.8. But I had already done this, I had even made 4 or 5 spells before I relogged. It seems to be resetting me every time I relog, consistently. If you want a snapshot, I will put one up in the form of a reply.

**Comment by yrsegal** [comment]
I believe this is a sponge bug, not a psi one.

**Comment by Insufficient-Charge** [comment]
Ah, ok. I shall report it over there then! Thanks!
