### ISSUE TITLE
Question about Quark's Tome ability and Psi pickaxe effiency cap

### ISSUE THREAD

**Issue by utoc** [Vazkii/Psi#232]
Greetings,

Quark has these lovely ancient tomes that can be crafted with books to exceed the usual cap, ie, efficiency V becomes efficiency VI.  Combine this with a Vanilla pickaxe and normal stone behaves in a manner similar to netherrack.  My question was in regards to Psi's Psimetal Pickaxe.  A user today took the time to get an efficiency VI book, enchanted it but unfortunately did not see similar speed increases that you'd expect.  It looked as if the tool's efficiency was capped at V speed regardless if the enchantment were a higher level.

We're using Quark-beta-49 and Psi Psi-r1.0-37

Thanks so much for taking a moment!

**Comment by yrsegal** [comment]
This might be because the Psimetal Pickaxe mines at an iron speed.
