### ISSUE TITLE
Crashing with latest update

### ISSUE THREAD

**Issue by PandaFrog** [Vazkii/Psi#239]
When updating to the latest version of psi which is version 1.0-38 when i start my server i get a server loop.
[crash-2016-08-29_08.26.47-server.txt](https://github.com/Vazkii/Psi/files/441406/crash-2016-08-29_08.26.47-server.txt)

**Comment by yrsegal** [comment]
This is an issue with Psionic Upgrades, not psi. yrsegal/PSIonic-Upgrades#11
