### ISSUE TITLE
CAD in off hand, food in main hand, somewhat glitchy.

### ISSUE THREAD

**Issue by Math321** [Vazkii/Psi#245]
Right now, if you have a CAD in your off hand, and food in your main hand, and you try to eat, you ARE able to eat, which is good... But as soon as you're done eating, you start spamming whatever spell is on your CAD until you're done right clicking.

I'd rather be able to eat with a CAD in my offhand without it spamming the spell I have in my CAD when I'm done.

**Comment by williewillus** [comment]
kinda a vanilla problem to be fair.

splash pot in main hand, eat from off hand as soon as you're done you start spamming potions

**Comment by Math321** [comment]
Perhaps a fix for this behavior could be made a tiny mod in its own right, then, rather than a Psi-specific feature.
