### ISSUE TITLE
Allow copying spells out of Bullets?

### ISSUE THREAD

**Issue by konals** [Vazkii/Psi#25]
As far as I can tell, there isn't a way to retrieve a spell from in a bullet for further modification or viewing. A way to do that would be handy. Perhaps allowing a Spell Drive to copy the active spell out of a CAD or Psimetal tool in the right adjacent hotbar slot?

**Comment by yrsegal** [comment]
I think the reason for this is that that would effectively turn bullets into spell drives, allowing cheaper spell storage.

**Comment by konals** [comment]
There's not a huge point to Spell Drives as they are right now, anyway, since you could just Import/Export the 'code' for the spell.

**Comment by tkdberger** [comment]
You aren't missing anything, it's perfectly possible to have [a massive text document of spells.](http://pastebin.com/6Q5gA3DA)
