### ISSUE TITLE
Botania's Bifrost blocks and Psi's rainbow-colored Conjured Blocks aren't in sync, colorwise.

### ISSUE THREAD

**Issue by Math321** [Vazkii/Psi#251]
I know it's a bit OCD-ish to ask for this, but can you sync up the colors between Psi's rainbow-colored conjured blocks and Botania's Bifrost blocks, so they blend nicely with each other?

[Scrrenshot](http://prntscr.com/cij3ui)

**Comment by yrsegal** [comment]
This is not possible, as textures (the animation method for bifrost blocks) and world time (the animation method for the Full-Spectrum CAD Colorizer) can never be guaranteed to sync up.

**Comment by Math321** [comment]
Then how do those rainbow blocks from Natural Pledge sync up with Botania's bifrost blocks perfectly?

**Comment by Math321** [comment]
Oh. Wait. Dumb question. Natural Pledge probably does it with textures. Ignore me.

Is there a reason Psi doesn't do it with textures, like the blocks being made of particles or something?

**Comment by yrsegal** [comment]
Its color is always inherited from a Colorizer, which means it can't use a
texture.

I do it with textures in NP, yes.
