### ISSUE TITLE
Can't get past welcome message

### ISSUE THREAD

**Issue by shikyo13** [Vazkii/Psi#261]
I've created a CAD assembler and assembly, made a basic CAD and some psi dust. I got the level up message, but when I press C I still just get the welcome message and cannot seem to get past this. Sorry if I'm just being dumb. I'm running Psi-r1.0-40 .

**Comment by Vazkii** [comment]
I think I know why this is but I'm not at home to fix it. Can you try build
39? Should be fine there. Please don't close the issue even if it fixes it,
so it serves as a warning until I release an update.

**Comment by shikyo13** [comment]
Yes I will try that, thanks for the super fast response!

**Comment by shikyo13** [comment]
Build 39 does indeed work. Leaving this open as requested, and thank you again!

**Comment by bigbes** [comment]
Well, I'm also affected by this. Bug tracking systems are great :)

**Comment by akauble** [comment]
I'm still experiencing this on build 40.

**Comment by bigbes** [comment]
Thanks!
