### ISSUE TITLE
[r1.0-40] Potential Memory Leak?

### ISSUE THREAD

**Issue by Alaberti** [Vazkii/Psi#265]
I'm going to be honest; I'm not 100% sure how to report this. I'm seeing some pretty crazy memory use from what appear to be your FXWisp and FXSparkle particles.

![image](https://cloud.githubusercontent.com/assets/10929796/19254782/1d94a8ca-8f1d-11e6-9118-8952269f0f67.png)
![image](https://cloud.githubusercontent.com/assets/10929796/19254874/faf1d1c0-8f1d-11e6-8dbd-8cfe3fd85656.png)

How can I help you help me figure out what's happening here? This is a heap dump from a client.

**Comment by suirad** [comment]
After a quick review of a9f46a0, I don't see anywhere where the particle objects are explicitly dereferenced after use. I am not super familiar with the mod/modding internals, but it seems like those objects aren't expiring correctly, based on the profile above.
FXSparkle seems to have a 3 minute expiry time(seen [here](https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/client/fx/FXSparkle.java#L53)), which I cannot imagine to be justified for a single particle.
FXWisp also has a variable max age which could also be subject to extremely long gc times; seen [here](https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/client/fx/FXWisp.java#L55).

**Comment by Vazkii** [comment]
You're absolutely grasping at straws here @suirad. That is not in minutes, it's in ticks. All that expiring the particle does is remove the particle from the particle emitter queue, leaving it with no strong reference, and then it can be GC'd.

Aside from the references present in Minecraft's inner particle queue, the only other strong reference is kept in a queue inside each of the particles' classes, which is cleared every render tick.

I honestly have no idea what can be caused this.

**Comment by suirad** [comment]
Like mentioned, it was a surface level review. Only trying to assist you or
any other looking to debug. Although I wouldn't say my analysis isn't
completely unfounded as it seems *something* is happening to prevent
collection of those objects.

**Comment by Alaberti** [comment]
Removing every conjured block/light has fixed this issue; is there an option to prevent their use while this is investigated?

**Comment by Luke-Thompson** [comment]
I think there's a config to diable certain components. Correct me if I'm mistaken

**Comment by Alaberti** [comment]
@InjuredWolf Unfortunately, the PSI config only has 9 options in 1.10.2 and none of them disable conjured lights/blocks.

**Comment by Alaberti** [comment]
This bug is still present.

**Comment by yrsegal** [comment]
@Alaberti requesting another test?

**Comment by yrsegal** [comment]
No, it will be later today. You could build from source if you wanted, but we'll be ready for testing soon.

**Comment by Alaberti** [comment]
I got a crash with the following: Forge 14.23.5.2806, psi r1.1-65, autoreglib 1.3-24, completely fresh install, downloaded from curseforge. Crash report: https://pastebin.com/zGAudhg7

**Comment by Alaberti** [comment]
Thanks, rerunning the test now.

**Comment by Alaberti** [comment]
I don't know what you did, but this is significantly better - the rate of memory usage is now completely in-line with vanilla memory usage as opposed to crashing minecraft after about a half hour. I would consider this a fix.

**Comment by yrsegal** [comment]
So, going back over my changes to the code, and then several pieces of native Java code and JVM documentation, I found the reason it was happening.
I regret doing so.

It seems that, somehow, because the ArrayDeque was internally untyped (no diamond operator), it was creating arrays which were being held in memory in a nonstandard way due to how they were being cast and copied, causing them to... never be dereferenced. Ever.

Yep.

I'm just going to walk slowly away from that.
