### ISSUE TITLE
Leveling Bug

### ISSUE THREAD

**Issue by sanbbans** [Vazkii/Psi#266]
Hello, i just want to report a bug that i found, the problem is, after i make psidust and reach level 1, and while not holding the CAD, it does not display the tutorial level screen, instead, it displays the same "Welcome to PSI, the best programming magic/tech mod in this side of the universe." even though i got 1 level point. I am not sure if only i am having this problem, if this is a bug, please fix it.

Thanks. -sanbbans

**Comment by Vazkii** [comment]
This shouldn't happen in the latest version.

**Comment by ColdIce1** [comment]
@Vazkii Yes it does, reproduced it 4 times now.
