### ISSUE TITLE
Inconsistent behavior on exosuit leggings

### ISSUE THREAD

**Issue by kuzetsa** [Vazkii/Psi#271]
**Edited to clarify:**
This is a normal bullet loaded into a worn / equipped exosuit leggings. (*may not have been clear*)

---

```
{spellName:"Regenerate 5s-debug",uuidMost:7034941352036614435L,validSpell:1b,spellList:[0:{data:{key:"constantNumber",constantValue:"49"},x:0,y:2},1:{data:{key:"selectorTime"},x:0,y:3},2:{data:{params:{_target:2},key:"trickDie"},x:1,y:0},3:{data:{params:{_number2:4,_number1:2},key:"operatorDivide"},x:1,y:1},4:{data:{params:{_number2:3,_number3:0,_number1:2},key:"operatorSubtract"},x:1,y:2},5:{data:{params:{_number2:4,_number1:3},key:"operatorModulus"},x:1,y:3},6:{data:{key:"constantNumber",constantValue:"50"},x:2,y:1},7:{data:{key:"constantNumber",constantValue:"1"},x:2,y:2},8:{data:{key:"constantNumber",constantValue:"100"},x:2,y:3},9:{data:{params:{_number:0,_target:2},key:"trickDebug"},x:3,y:0},10:{data:{key:"selectorCaster"},x:3,y:1},11:{data:{key:"constantNumber",constantValue:"5"},x:3,y:3}],uuidLeast:-7936938896394337206L}
```

^ debug version (*zero cost to use this / no drain of any kind*)

```
{spellName:"Regenerate 5s",uuidMost:7034941352036614435L,validSpell:1b,spellList:[0:{data:{key:"constantNumber",constantValue:"49"},x:0,y:2},1:{data:{key:"selectorTime"},x:0,y:3},2:{data:{params:{_target:2},key:"trickDie"},x:1,y:0},3:{data:{params:{_number2:4,_number1:2},key:"operatorDivide"},x:1,y:1},4:{data:{params:{_number2:3,_number3:0,_number1:2},key:"operatorSubtract"},x:1,y:2},5:{data:{params:{_number2:4,_number1:3},key:"operatorModulus"},x:1,y:3},6:{data:{key:"constantNumber",constantValue:"50"},x:2,y:1},7:{data:{key:"constantNumber",constantValue:"1"},x:2,y:2},8:{data:{key:"constantNumber",constantValue:"100"},x:2,y:3},9:{data:{params:{_number:0,_target:2},key:"trickDebug"},x:3,y:0},10:{data:{key:"selectorCaster"},x:3,y:1},11:{data:{params:{_power:3,_time:2,_target:1},key:"trickRegeneration"},x:3,y:2},12:{data:{key:"constantNumber",constantValue:"5"},x:3,y:3}],uuidLeast:-7936938896394337206L}
```

This version has a constant drain (*has a cost every tick / never able to regenerate*) for psionic energy.

Among other issues (*likely related to constant drain*) the debug trick stops working.

This is counterintuitive / undocumented behavior.

Intent was for regeneration to be applied once every 100 ticks (*5 seconds*)

**Comment by kuzetsa** [comment]
**Please note:**

The debug variant just ouputs a debug message every 100 ticks (*expected behavior*)

The regular version (*intentional / as per wishes of mod author?*) has a cost **every** tick, This is regardless of debug trick and/or regenerate trick [not] executing.

**Comment by ccatlett2000** [comment]
Costs are determined by tricks in the spell, not tricks executed.
This is (I think) intended behavior).

**Comment by kuzetsa** [comment]
I'm inclined to assume this is a bug or balance oversight unless told otherwise.

**Comment by Boingboingsplat** [comment]
Yeah, spells always cost their full amount, whether or not the actually do anything. If you want an always on leggings spell, it has to cost lower than the psi regeneration rate. (About 20 energy/tick iirc)

**Comment by ccatlett2000** [comment]
Confirmed as intended in #82.

**Comment by kuzetsa** [comment]
As per #82 -- I don't have time to fork this mod, and don't feel like arguing with the maintainer/author about it so I'm closing the issue, apparently.
