### ISSUE TITLE
Particle spell crashes the game

### ISSUE THREAD

**Issue by Diggsey** [Vazkii/Psi#275]
Spell JSON:
```
{spellName:"Laser Pointer",uuidMost:-8027405289617011770L,validSpell:1b,spellList:[0:{data:{params:{_target:2},key:"operatorEntityPosition"},x:3,y:4},1:{data:{key:"selectorCaster"},x:3,y:5},2:{data:{key:"constantNumber",constantValue:"25"},x:4,y:3},3:{data:{params:{_distance:1,_ray:2,_time:4,_position:3},key:"psionup.particleTrail"},x:4,y:4},4:{data:{params:{_target:3},key:"operatorEntityLook"},x:4,y:5},5:{data:{key:"constantNumber",constantValue:"0"},x:5,y:4}],uuidLeast:-8914619771356197855L}
```

Brief look at the stack trace indicated it might be a division by zero error in the particle renderer.

**Comment by yrsegal** [comment]
It's mine, not V's. Goddamn it, I never expected someone to try to divide
by *zero*... maybe try *not* doing that until I fix it.

**Comment by Diggsey** [comment]
@yrsegal The spell just aims to cast a ray of particles from the caster in the view direction, it doesn't try to divide by zero.
