### ISSUE TITLE
[Feature Request] Trick: Remote Redstone

### ISSUE THREAD

**Issue by Ricket** [Vazkii/Psi#281]
I saw [this post on Reddit](https://www.reddit.com/r/feedthebeast/comments/5j0zm4/preview_of_my_new_mod_redstone_remote/) and it made me think "I could do that with my CAD!", then I realized I can't because Psi doesn't have a trick for redstone. It would be nice if there was such a trick, which takes a position and duration, and optional strength.

**Comment by ArukaAlter** [comment]
Psionic Upgrades has exactly this.

**Comment by Ricket** [comment]
From the mod description, it looks like it can summon a block of Redstone equivalent, but can it activate an existing Redstone device? Like in the video?

**Comment by ArukaAlter** [comment]
There are the Block and the Light variants of the Pulsar spell, they look like this conjured: http://i.imgur.com/Bk1Z2Tb.png
The remote does the same thing the Light Pulsar does, and you can even define time.

**Comment by yrsegal** [comment]
Pulsar tricks do exactly what you want, here. - PSIonic Upgrades dev

**Comment by Ricket** [comment]
Okay, thanks for clarifying!
