### ISSUE TITLE
Light Sensor.

### ISSUE THREAD

**Issue by sscards55** [Vazkii/Psi#291]
The description of the light sensor led me to believe the spell would be cast while the player is in low light. Not necessarily every tick just every once in a while. However the light sensor will only trigger when the player enters low light.

One example that comes to mind is :
The player has a spell that places a light block at their feet in their helmet. If a players enters a cave and the light sensor triggers while the player is in a non-solid block like Botania's Shimmering Mushrooms, the sensor will not trigger again until the player enter a bright area and re-enters a low light one.

I'm not sure if that behavior is intended or the description is suppose to be the right one.
Line [607](https://github.com/Vazkii/Psi/blob/master/src/main/resources/assets/psi/lang/en_US.lang#L607) by the way.

**Comment by quat1024** [comment]
Adjust your spell to use Trick: Break Block followed by Trick: Conjure Light

**Comment by sscards55** [comment]
I changed my spell already, but the issue is that the descriptions for the sensor says "is in darkness" but the actual trigger is "enter darkness."
