### ISSUE TITLE
No Drops

### ISSUE THREAD

**Issue by BrayamsRamos** [Vazkii/Psi#295]
I'm using the latest version of the mod (R1.1-44) on the required version of minecraft (1.11.2) and with the latest version of AutoRegLib (1.1-4).

After executing the break block spell on any block it works as intended replacing it with air, the problem is that there is no drop. I assumed it was a world update issue, so I decided to create a new world and test the same spell but the problem persisted.

Here a list of other mods I'm using along with Psi:
- Inventory Tweaks 1.62-dev-75
- JEI 4.2.3.222
- JourneyMap 1.11.2-5.4.3

Forge version: 13.20.0.2222

I also attach a screenshot of the spell and a log:

![2017-01-19_01 48 08](https://cloud.githubusercontent.com/assets/21320102/22096420/677d5c3c-dde9-11e6-81de-9d796e16cf90.png)

http://pastebin.com/cX4qvhxz

**Comment by BrayamsRamos** [comment]
It works with the pickaxe.

**Comment by thePalindrome** [comment]
Is this intended to work with just the cad?

The quest suggests making a "treecapitator" which implies that Break Block causes drops.

@BrayamsRamos I'd suggest reopening this, unless you've found something else that shows that Break Block should *not* drop

**Comment by BrayamsRamos** [comment]
@thePalindrome I used the Break Block trick first with the cad and the spell worked but with no drops. Then, I tried the spell with the Psi pickaxe and it worked perfectly. What is that "quest" that you mention?

**Comment by thePalindrome** [comment]
In the "Blockworks" tutorial (which gives you Break/Place Block) it suggests the following:

> Try making a spell that brings down an 8 block high column, so you can "Treecapitate."

Apart from the fact that this is pretty much the only tutorial you cannot complete with the basic cad (you don't have the potency to do a full 8 blocks, only about 5) the wording and intent make no sense if Break block destroys things.

**Comment by thePalindrome** [comment]
Reading the code at https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickBreakBlock.java#L75 and I know for a fact that it should be dropping blocks unless you are in creative. Now I'm really confused why this isn't working D:

**Comment by Vazkii** [comment]
You don't need the 8 blocks to level up, just to use the spell at all. It
not dropping blocks definitely seems like a bug. I'll get to it when I can.

**Comment by thePalindrome** [comment]
No pressure, as the bug states, the psi pickaxe works :P 

I'd whack at this myself, but I'm pretty scared of the post 1.7.10 dev environment (which is pretty much why I stopped modding)
