### ISSUE TITLE
issue in compiling

### ISSUE THREAD

**Issue by TheChronomancer** [Vazkii/Psi#3]
http://pastebin.com/2auKiaDM
i used git bash

**Comment by JRoffel** [comment]
This issue is far from correct, it does not even have a description...

We would need at least the following chunks of information in order to help you:
* errors received
* programs used
* description as in how to reproduce this ossue

**Comment by GirafiStudios** [comment]
You don't have a private.properties, since it's not uploaded to the repo by default, thereby the name "Private". There is a private.properties.example you can use as an example tho.
