### ISSUE TITLE
Break Block duping mobheads

### ISSUE THREAD

**Issue by OrcAndHat** [Vazkii/Psi#305]
I've been using a fairly standard Break Block Spell, When using the spell to break and pick up various monster heads (Wither Skeleton Skull and Zombie Head) it causes the block to drop two heads instead of one when broken. After encountering this bug and narrowing down the cause, I also tested it on normal skeleton skulls and creeper heads, which also end up getting duped when broken.

I tried to do the same to the Ender IO Enderman Head, but only a single head dropped when broken. I have not found any other blocks that dupe upon being broken.

The spell I'm using is the following:
{spellName:"Break Block",uuidMost:7723343255909909628L,validSpell:1b,spellList:[0:{data:{params:{_target:4},key:"operatorEntityPosition"},x:4,y:2},1:{data:{params:{_ray:4,_max:0,_position:1},key:"operatorVectorRaycast"},x:4,y:3},2:{data:{params:{_position:1},key:"trickBreakBlock"},x:4,y:4},3:{data:{key:"selectorCaster"},x:5,y:2},4:{data:{params:{_target:1},key:"operatorEntityLook"},x:5,y:3}],uuidLeast:-6749035396379831577L}

The Psi Gun:
Psi Metal CAD Assembly
Radiative CAD Core
Huge CAD Socket
Ultradense CAD Battery

**Comment by toastertim** [comment]
encountered this in latest 1.10.2 vers as well, on use with wither skulls

**Comment by SFort** [comment]
This also occurs with Portable Tanks (Thermal Expansion) So i think it is safe to assume it happens with many other items.
Botania version: r1.9-341

**Comment by IonicCerberus** [comment]
We have a mining world that has the entire world claimed by the wilderness which means that you cannot place or mine in that world unless you claim a section with a sponge plugin called "Grief Prevention". The Break Block spell can bypass the wilderness claim and duplicate any items in that world, including chests with its contents. 

Heres two pictures and a gif to see the damage:
https://gyazo.com/906770a4e3d19021004512fd8cb16ec6
https://gyazo.com/580ea332f0179316459c2939d6b78197
https://gyazo.com/52d7cfcfc6ef396780358718570e88b2
