### ISSUE TITLE
Trouble Seeing Text in Help Screen

### ISSUE THREAD

**Issue by RobertLSnead** [Vazkii/Psi#309]
Before you report an issue, make sure these boxes are checked.

- [X] Make sure you're not reporting something that was just fixed.
   Reviewed current issues!
- [X] Make sure you're not using an old version of Psi.
   Using ver. Psi-r1.0-42
- [X] Make sure you're not using Optifine or GLSL Shaders, if it's a rendering issue.
  Not sure this is a rendering issue.
- [X] Make sure you're using Java 8. Psi will not function in older versions.
   Running Java 8 :D

After you've done so, delete this template, and proceed with your issue report.

I am having trouble seeing some of the text in the help menu.
I have never used PSI before and am having issues understanding because, I can not read the text.

Snap Shot:
![image](https://cloud.githubusercontent.com/assets/5366796/23106677/eb3e6582-f6be-11e6-9f2f-2a59904e7e01.png)

**Comment by RobertLSnead** [comment]
You can see in the snap shot that the scroll bar is blocking the text.

**Comment by Vazkii** [comment]
Delete the fonts from your resource pack.

**Comment by RobertLSnead** [comment]
I took off the resource pack and I can read just fine.
It still seems it is cutting it pretty close though.
It would be nice if the mod kept a custom font for a resource pack.
Deleting the font from the pack causes issues else where ugh.

SnapShot:
![image](https://cloud.githubusercontent.com/assets/5366796/23142308/536d0c10-f789-11e6-93f2-3d313316d561.png)
