### ISSUE TITLE
Breaking CAD Assembler gives XP

### ISSUE THREAD

**Issue by Compegen** [Vazkii/Psi#314]
When breaking the CAD Assembler, it can give experience orbs (similar to rate of coal ore) allowing for possible infinite XP.

Using version r1.0-42 for 1.10.2

**Comment by Vazkii** [comment]
you what

**Comment by Compegen** [comment]
?

**Comment by Compegen** [comment]
Found issue. XP drops when mining with a copper pickaxe from Tinker's Construct (adds well-established modifier, which can give XP from any block)
