### ISSUE TITLE
Block Place Crash

### ISSUE THREAD

**Issue by Walaryne** [Vazkii/Psi#316]
I created a simple spell that places blocks at a range, and while placing blocks upon reaching the end of a stack and placing the final block, Minecraft crashes immediately to desktop.

https://pastebin.com/yUgPwGc8

**Comment by MentalMouse** [comment]
Ow.  Dude, please use pastebin.  (AFAIK Github doesn't do spoilers.)

**Comment by Walaryne** [comment]
A bit cleaner, hopefully.
I was half asleep when I put this here, so sorry!

**Comment by MentalMouse** [comment]
Thanks.  My own experience: I am also getting crashes from placing blocks, most recently with a simple bridge spell. It happens maybe one time in 6 or 10 from placing 8 blocks along a modified look vector.

**Comment by Dykam** [comment]
Adding one more [crash report](https://gist.github.com/Dykam/98e74e95dbc250a3f0342fb157c386f7).

**Comment by MentalMouse** [comment]
Dycam:  I'm not so sure about that, I'm fairly sure I've had crashes where I hadn't used up my stack of blocks.

**Comment by Walaryne** [comment]
I agree with Dykam here, I have had the same exact thing happening.

**Comment by MentalMouse** [comment]
Hmm.  If I've got, say, stone bricks in my hotbar for the spell, can the spell take from (and maybe exhaust) stone bricks from my main inventory instead?

**Comment by Dykam** [comment]
@MentalMouse That's the behavior which caused a problem for me. It takes it from the inventory first, and when the stack it is taking it from, empties (and it possibly has to take from the next stack), it causes an NPE.

**Comment by MentalMouse** [comment]
Ah, that would probably cover my situation.

**Comment by FiveEYZ** [comment]
another crash but from a server:
https://gist.github.com/FiveEYZ/e9db5b7c07030b81f0610fc471b15713

any news on this?
