### ISSUE TITLE
Newer build for 1.10.2?

### ISSUE THREAD

**Issue by MidnightsFX** [Vazkii/Psi#331]
Pretty much title. I came here to report the fixed 'psi:block/conjured' model error and noticed there are no 1.10.2 builds for the fixed version.

Any chance of a build for 1.10.2 would be awesome, but I understand if its not possible.

**Comment by Vazkii** [comment]
It's possible, but not something I'm interested in, as I prefer to support
the latest.

**Comment by MidnightsFX** [comment]
Thats fair, would you be opposed to me working towards building latest for 1.10.2?

**Comment by Vazkii** [comment]
Please read the psi license in the website.

**Comment by MidnightsFX** [comment]
Thanks, sorry I did not realize there was a license on the website. I'll close this.
