### ISSUE TITLE
Can no longer create spells with Beyond 1.6.1

### ISSUE THREAD

**Issue by HunterAshh** [Vazkii/Psi#334]
Server updated to Beyond 1.6.1. Since then spells will not save in the Spell Programmer. Spells seem to transfer to the bullet but it clears itself out right after so you are unable to place it in the CAD Assembler.

**Comment by raizosec** [comment]
same here. but only on a server. in single player i dont have the problem.

**Comment by raizosec** [comment]
issue was fixed for me after the update of sponge forge to build 2341

**Comment by HunterAshh** [comment]
Will give that a go. Thank you

**Comment by HunterAshh** [comment]
Yes that did correct it
