### ISSUE TITLE
Light texture is not rendering correctly

### ISSUE THREAD

**Issue by PessimisticBastard** [Vazkii/Psi#339]
<a href="http://imgur.com/PO9J4hP"><img src="http://i.imgur.com/PO9J4hP.png" title="source: imgur.com" /></a>

Unless there's been a texture change, I'm pretty sure the light isn't supposed to look like that. This happens with or without any resource pack.

**Comment by Infinoid** [comment]
Do conjured lights look correct for you in Psi-r1.1-55.jar?

**Comment by PessimisticBastard** [comment]
Yes, they appear to be textured correctly.

**Comment by Infinoid** [comment]
Thanks for confirming the fix.  I think this issue can be closed.
