### ISSUE TITLE
Arrows in Tooltip point the wrong direction.

### ISSUE THREAD

**Issue by MaPePeR** [Vazkii/Psi#34]
I think the Arrows in the tooltip point the wrong direction. For example:

```
Trick: Debug
<- None
 ->  Target [Any]
[->] Number [Number]
```

In my head i always put the arrows to the right of the Trick (basically eliminate the newlines), which then becomes:

```
Trick: Debug <- None 
Trick: Debug -> Target [Any]
Trick: Debug [->] Number [Number]
```
Which gives a totally wrong impression of the inputs and outputs of the Trick.

Maybe i just have to get used to it... or it is not intuitive.

EDIT: I know that it matches the arrow direction of C++, but in C++ there is a 'variable' which the arrows point at, which makes it more intuitive: `cout << "Hello"`, `cin >> aVariable`.

**Comment by Vazkii** [comment]
Non-issue.

**Comment by MaPePeR** [comment]
Could you elaborate, what you mean by "non issue"? Do you disagree, that this is not intuitive? or do you think its not important? 

Sure, it does not "break" the mod, but i think it adds unnecessary difficulty.

**Comment by yrsegal** [comment]
it's intuitive to me...
