### ISSUE TITLE
Light is wrong colour

### ISSUE THREAD

**Issue by GameSpriter** [Vazkii/Psi#340]
I'm having a similar issue to https://github.com/Vazkii/Psi/issues/339. I'm playing on a server and the light's colour seems to be incorrect as well. For instance: I have an orange colourizer in my CAD. All the effect particles are orange except the light. The light is either Pink, Magenta, or Purple, I can't quite tell. I had someone else cast it with their Light Blue colourizer and it came out Magenta or Purple.
![image](https://user-images.githubusercontent.com/10263532/26895911-17fe89a4-4b91-11e7-9e02-9887b29c890e.png)
Mine is on the right. His is on the left. Also, sorry for the rain.
[Mod version is r1.1-47]

**Comment by Infinoid** [comment]
Do conjured lights look correct for you in Psi-r1.1-55.jar?
