### ISSUE TITLE
[1.12] Crash with Beyond the Minecraft

### ISSUE THREAD

**Issue by Migmag789** [Vazkii/Psi#342]
Hi ! I'm developping my modpack, and pouf ! Crashes, and his cause is Psi. Please, can you fix this plz ?
[crash-2017-06-20_18.20.03-client.txt](https://github.com/Vazkii/Psi/files/1088886/crash-2017-06-20_18.20.03-client.txt)

**Comment by Migmag789** [comment]
New crash! 
[crash-2017-06-21_11.38.55-client.txt](https://github.com/Vazkii/Psi/files/1091062/crash-2017-06-21_11.38.55-client.txt)

**Comment by Vazkii** [comment]
It's the same crash. I'll have a look at it later.
