### ISSUE TITLE
[1.12] Crash at startup

### ISSUE THREAD

**Issue by Sirkku** [Vazkii/Psi#347]
Tried to run PSI on 1.12 with latest Forge; crashes on loading screen. 

I used the java based FML Installer, the "1.12 - 14.21.1.2387"
Used the latest versions to-this-date AutoRegLib-1.2-8 and Psi-r1.1-49
No additional modifications.

Crash Report: https://pastebin.com/AfNAcjL6
FML Log: https://pastebin.com/sdXcRd6d

The same error message is producible with quark (r1.2-97) instead of psi on this setup.

**Comment by Vazkii** [comment]
https://github.com/Vazkii/Quark/issues/482
