### ISSUE TITLE
[1.12] Poof! crash...

### ISSUE THREAD

**Issue by Migmag789** [Vazkii/Psi#348]
Hey ! Vazkii, there is a crash with AutoRegLib, Quark and PSI...
[crash-2017-06-29_17.29.50-client.txt](https://github.com/Vazkii/Psi/files/1112585/crash-2017-06-29_17.29.50-client.txt)

**Comment by Sirkku** [comment]
Does the issue persist with the new version of these mods? Elsewise it looks like https://github.com/Vazkii/Psi/issues/347
