### ISSUE TITLE
[1.12] Can't import any spells (Malformed String)

### ISSUE THREAD

**Issue by Novian3002** [Vazkii/Psi#349]
I can't import any spells from online, no matter which I try I always get the malformed string error. I am not the only one getting this error (some other person on a server have the same issue). I also am pretty sure I didn't copy any spaces or miss a bracket or stuff like that. 

Example of a malformed string: 
```
{spellName:"Conjure Light",uuidMost:-6360765995113168206L,validSpell:1b,spellList:[0:{data:{params:{_target:2},key:"connector"},x:1,y:2},1:{data:{params:{_target:2},key:"connector"},x:1,y:3},2:{data:{params:{_target:4},key:"connector"},x:1,y:4},3:{data:{params:{_target:3},key:"connector"},x:2,y:2},4:{data:{key:"selectorCaster"},x:2,y:3},5:{data:{params:{_target:1},key:"operatorEntityLook"},x:2,y:4},6:{data:{params:{_ray:3,_max:0,_position:2},key:"operatorVectorRaycast"},x:3,y:2},7:{data:{params:{_target:3},key:"operatorEntityPosition"},x:3,y:3},8:{data:{params:{_ray:3,_max:0,_position:1},key:"operatorVectorRaycastAxis"},x:3,y:4},9:{data:{params:{_target:3},key:"connector"},x:4,y:2},10:{data:{params:{_vector3:0,_vector2:1,_vector1:2},key:"operatorVectorSum"},x:4,y:3},11:{data:{params:{_target:3},key:"connector"},x:4,y:4},12:{data:{params:{_time:0,_position:3},key:"trickConjureLight"},x:5,y:3}],uuidLeast:-7084625235187991291L}
```

**Comment by Novian3002** [comment]
Update: Importing 1.12 made spells works, spells made in 1.11.2 don't work

**Comment by Eladkay** [comment]
I second this

**Comment by Drachlox** [comment]
I really wish this is just a bug. Losing backwards compability means i will have to find completely new spells, and that makes me a saaad panda.

**Comment by goofolph** [comment]
Not sure if this belong with this issue or as a new issue. I'm having an issue where I will export a string then try to immediately import it and it'll say it's malformed. Same for some of the other strings I've exported. 

Example of one I just made:

`{spellName:"Place Light",uuidMost:-4340840911731864888L,validSpell:1b,spellList:[{data:{params:{_target:4},key:"connector"},x:2,y:1},{data:{params:{_target:1},key:"connector"},x:2,y:2},{data:{params:{_target:1},key:"operatorEntityLook"},x:2,y:3},{data:{params:{_target:1},key:"connector"},x:2,y:4},{data:{params:{_target:1},key:"connector"},x:2,y:5},{data:{params:{_target:4},key:"connector"},x:3,y:1},{data:{params:{_target:4},key:"connector"},x:3,y:2},{data:{params:{_ray:3,_max:0,_position:1},key:"operatorVectorRaycastAxis"},x:3,y:3},{data:{params:{_target:3},key:"connector"},x:3,y:5},{data:{key:"selectorCaster"},x:4,y:1},{data:{params:{_target:1},key:"operatorEntityPosition"},x:4,y:2},{data:{params:{_vector3:0,_vector2:4,_vector1:3},key:"operatorVectorSum"},x:4,y:3},{data:{params:{_time:0,_position:1},key:"trickConjureLight"},x:4,y:4},{data:{params:{_target:3},key:"connector"},x:4,y:5},{data:{params:{_target:3},key:"connector"},x:5,y:2},{data:{params:{_ray:2,_max:0,_position:1},key:"operatorVectorRaycast"},x:5,y:3},{data:{params:{_target:2},key:"connector"},x:5,y:4},{data:{params:{_target:3},key:"connector"},x:5,y:5}],uuidLeast:-9044122062267778114L}`
