### ISSUE TITLE
Recipe for copying spells on Bullets to Spell Drives dupes the Spell Drives.

### ISSUE THREAD

**Issue by konals** [Vazkii/Psi#36]
![image](https://cloud.githubusercontent.com/assets/2679610/13037113/e57d9a36-d33e-11e5-96e1-96b711b81782.png)

**Comment by yrsegal** [comment]
dammit, container items

**Comment by Vazkii** [comment]
Ah yes, this will dupe the drive if it already has something on it. Didn't think of that.
