### ISSUE TITLE
[MC 1.12.2] Psi r1.1-57 crashes on dedicated server

### ISSUE THREAD

**Issue by sandalle** [Vazkii/Psi#371]
After updating from Psi r1.1-56 to r1.1-57 on my Minecraft 1.12.2 modpack running Forge 1.12.2-14.23.0.2515, I get this crash: [crash-2017-10-24_15.30.00-server.txt](https://github.com/Vazkii/Psi/files/1412716/crash-2017-10-24_15.30.00-server.txt)

I did not try it on the client.

**Comment by ubergeek77** [comment]
Yep, happens to me as well. I just ran into this issue today after trying to update. I had to roll back to r1.1-56 in order to boot my server again.

**Comment by mblob** [comment]
Same here, rolling-back to 1.56 solved the problem.

**Comment by Vazkii** [comment]
Oof. I thought that was tested. I'll fix it later today.

**Comment by Foxgreat** [comment]
Got crash, waiting to fix it)

[crash-2017-10-25_20.32.36-server.txt](https://github.com/Vazkii/Psi/files/1414950/crash-2017-10-25_20.32.36-server.txt)

**Comment by sandalle** [comment]
Psi r1.1-58 loads on both client and server for me, thank you for the quick fix @Vazkii . :)
