### ISSUE TITLE
Slow falls still deal large dmg/kill

### ISSUE THREAD

**Issue by coolman1324** [Vazkii/Psi#375]
When using tricks which can slow ones fall, such as add motion do nothing to help negate fall dmg

heres my basic spell:
{spellName:"Add Motion",uuidMost:7087621840040509788L,validSpell:1b,spellList:[{data:{key:"constantNumber",constantValue:".25"},x:3,y:3},{data:{key:"selectorCaster"},x:4,y:2},{data:{params:{_direction:4,_speed:3,_target:1},key:"trickAddMotion"},x:4,y:3},{data:{params:{_x:0,_y:4,_z:0},key:"operatorVectorConstruct"},x:5,y:3},{data:{key:"constantNumber",constantValue:"1"},x:6,y:3}],uuidLeast:-5293915898338595390L}

I used it on the pants
It seems to just be based off of maximum hieght to ground contact point, as if you fell at nomral speeds

**Comment by Tamaized** [comment]
That is vanilla, it deals damage based on fall height, not motion.
