### ISSUE TITLE
Black CAD Colourizer recipe missing

### ISSUE THREAD

**Issue by Tristaric** [Vazkii/Psi#38]
I was just messing around, seeing all the recipes for the items, and realized when I tried to see the recipe for the black colourizer... it wouldn't switch away from the previous recipe. So I escaped out of the recipe menu in JEI, and tried to see the black colourizer's recipe again.. and... nothing.

Oh, and I tried crafting it myself with a predicted recipe while making this report, no luck
http://i.imgur.com/OHJiGle.png

**Comment by yrsegal** [comment]
This is due to a typo in dyes. " Black" should be replaced to "Black"

https://github.com/Vazkii/Psi/blob/9edd922f4c41a0844ccea4bfcf8985e7584c3bc1/src/main/java/vazkii/psi/common/crafting/ModCraftingRecipes.java#L123

**Comment by Tristaric** [comment]
k
