### ISSUE TITLE
[Request] Sound Suppressor

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Psi#380]
Similar to the Error Suppressor, except it stops the CAD from making a sound as it is used.

**Comment by Darinth** [comment]
Please for the love of all things unholy give me some method of turning off the CAD sound... I actually entirely disabled character noises because of this. Sorry.

**Comment by alpharou** [comment]
+1. Yeah... The DOINK sound really hunts me at night... Don't get me wrong, it sounds cool and fitting... but honestly I don't use spells all that much just because of the tediousness of the sound effect.
