### ISSUE TITLE
Mass Exodus completely fails if a single target is immune

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Psi#384]
#It gives an error message in the chat saying that an entity is either immune or a boss and the spell completely fails.

Why doesn't it just skip the immune entity?

**Comment by GLugia** [comment]
Spells target any entity at all. Including those that might be immune such as bosses. I haven't heard of anything about Mass Exodus completely failing the moment it targets an immune entity. Just add an error suppression to the spell and it should work just fine.

**Comment by Zsashas** [comment]
I have the target for the spell set to add the caster to a list of nearby entities (forget which list type I used). If I get too close to a boss, the spell refuses to work at all. Even if it isn't that close, since the Ender Dragon apparently has a massive hitbox even beyond what's visible.
