### ISSUE TITLE
[Compat] PSI Combat Addons

### ISSUE THREAD

**Issue by Zsashas** [Vazkii/Psi#385]
So apparently, since you can only level up so many times with PSI, if you have the Combat Addons mod, you'll end up having to choose between lessons from that or from PSI. If there is already a way to give a player additional level points, then please inform me of that way.

**Comment by Jason-c-o** [comment]
This would be up to the creator of that addon to give you a point when you use a certain piece from his sets, just like normal Psi does.

**Comment by Zsashas** [comment]
I figured.

**Comment by Zsashas** [comment]
There is one thing that this mod could do to help: have the final lesson give a level point, making it possible to learn the addon lessons after completing the main ones.
