### ISSUE TITLE
[1.12.2 crash] Crash on Psi-r1.1.59

### ISSUE THREAD

**Issue by Leosky** [Vazkii/Psi#386]
crash log : https://gist.github.com/Leosky/f07ec27480081f0ab4416fdaa512082a

When i use the psi key when having a simple iron cad without anything else.

**Comment by Leosky** [comment]
in fact it craft always when i open the cad wheel

**Comment by Leosky** [comment]
after few testing its related to the key. I'm on a belgian keyboard, PSI was bound to the key right of the left shift key.

**Comment by CarpeNecopinum** [comment]
Same issue here, had PSI bound to the `ö`-key (right of L on german keyboards) which triggered the crash. Rebound to C and everything is working again.
