### ISSUE TITLE
Spell detonator only works in the upward southeast direction

### ISSUE THREAD

**Issue by quat1024** [Vazkii/Psi#388]
Psi r1.1-59, AutoRegLib 1.3-15, Forge 14.23.1.2598

Spell detonators only work on charge spells that are higher in the X or Z coordinate than the caster.

Steps to reproduce:
1. Make a circle out of Charge spells and stand in the middle. (In this picture, North is facing up.)
![image](https://user-images.githubusercontent.com/2068021/35132878-663d475c-fc9b-11e7-8fa5-066d94698174.png)

2. Use the Spell Detonator.
![image](https://user-images.githubusercontent.com/2068021/35132889-7116d62a-fc9b-11e7-9ba6-3681f2b5187d.png)

**Comment by yrsegal** [comment]
E X P A N D

https://github.com/Vazkii/Psi/blob/0954426ec0aad4111102d586fb957fe496b9f697/src/main/java/vazkii/psi/common/spell/operator/entity/PieceOperatorFocusedEntity.java
https://github.com/Vazkii/Psi/blob/88a0df68abac0ce472d07aa5f8339a2b5192867f/src/main/java/vazkii/psi/common/entity/EntitySpellMine.java
https://github.com/Vazkii/Psi/blob/9c4f1754706f4ada16eb42eafe699206924b184a/src/main/java/vazkii/psi/common/item/ItemDetonator.java

**Comment by Dynacord** [comment]
Did a couple of tests, the error lies in ItemDetonator.java, line 34. It seems that playerIn.getEntityBoundingBox().expand(32, 32, 32)) is not centered on the player, put uses the player coordinates has origin coordiates. Can't go further in, as I am not a java, or minecraft code expert.

Here's some screenshots of the bug tho

![2018-03-30_02 54 57](https://user-images.githubusercontent.com/15387304/38105009-dcde14d4-33c5-11e8-9140-2bd5901433fb.png)
![2018-03-30_02 55 04](https://user-images.githubusercontent.com/15387304/38105010-dd0a0580-33c5-11e8-81ce-a92e73e34eab.png)
![2018-03-30_02 55 09](https://user-images.githubusercontent.com/15387304/38105011-dd33e274-33c5-11e8-8826-efc597340d8a.png)
![2018-03-30_02 55 16](https://user-images.githubusercontent.com/15387304/38105012-dd5d402e-33c5-11e8-9e1e-98c8e2a2a46a.png)

**Comment by SnazzGass** [comment]
Its not very clear in the title, but this also includes the y coordinate. Any charge below the player will not detonate either.
