### ISSUE TITLE
Crash on game start

### ISSUE THREAD

**Issue by Sbeagin** [Vazkii/Psi#39]
I am using beta 13 of the mod and version 11.15.1.1744 of forge for Minecraft 1.8.9. I am using vanilla forge and I have no other mods installed. The game crashed in the pre-initialization phase, I believe. FML Log: http://pastebin.com/tvvuCKr7.

**Comment by yrsegal** [comment]
Java 8 is required; update that and this will be fixed.

**Comment by Sbeagin** [comment]
I have java 8 installed on my pc. When I type "java -version" into command prompt it says "java version '1.8.0_51'". But your right, minecraft does seem to be using java 7 for some reason... Any suggestions?

**Comment by yrsegal** [comment]
See if multimc (I think that's what you're using) has an option for that

**Comment by Sbeagin** [comment]
Thank you! I didn't think of that... I just assumed that MultiMC would just use the newest version.
