### ISSUE TITLE
Add motion doesn't affect players

### ISSUE THREAD

**Issue by jrbaca** [Vazkii/Psi#394]
Using add motion on other players doesn't affect them.

forge-1.12.2-14.23.2.2611
AutoRegLib-1.3-15
CodeChickenLib-1.12.2-3.1.6.339-universal
jei_1.12.2-4.8.5.147
NotEnoughItems-1.12.2-2.4.1.233-universal
OptiFine_1.12.2_HD_U_C9
Psi-r1.1-59

Example:
{spellName:"Debug",uuidMost:5280997559766107577L,validSpell:1b,spellList:[{data:{key:"selectorCaster"},x:3,y:3},{data:{key:"constantNumber",constantValue:"5"},x:3,y:4},{data:{params:{_target:3},key:"operatorEntityPosition"},x:4,y:3},{data:{params:{_position:1,_radius:3},key:"selectorNearbyLiving"},x:4,y:4},{data:{key:"constantNumber",constantValue:"100"},x:4,y:6},{data:{params:{_target:3},key:"connector"},x:5,y:3},{data:{params:{_target:3,_position:1},key:"operatorClosestToPoint"},x:5,y:4},{data:{params:{_direction:2,_speed:4,_target:1},key:"trickAddMotion"},x:5,y:5},{data:{params:{_x:3,_y:2,_z:4},key:"operatorVectorConstruct"},x:5,y:6},{data:{key:"constantNumber",constantValue:"100"},x:5,y:7},{data:{params:{_number:0,_target:3},key:"trickDebug"},x:6,y:4},{data:{key:"constantNumber",constantValue:"3"},x:6,y:5},{data:{key:"constantNumber",constantValue:"100"},x:6,y:6}],uuidLeast:-5417820284430383442L}

**Comment by cryocubed** [comment]
Mass exodus also does not work. It appears as though spells cannot target other players on a server.

**Comment by yrsegal** [comment]
`velocityChanged` is never set in [this function](https://github.com/Vazkii/Psi/blob/master/src/main/java/vazkii/psi/common/spell/trick/entity/PieceTrickAddMotion.java#L69-L104) for the entity. That's the fix for this.
