### ISSUE TITLE
[1.12.2] Secondary Operators not giving level up.

### ISSUE THREAD

**Issue by Raserhead** [Vazkii/Psi#396]
Using Psi version r1.1-59, Minecraft forge 14.23.2.2641. Which I believe are the latest versions at this time, on a modded server.
Not using Optifine or Bukkit/Spigot variants of forge.

Reached the secondary operators, created a spell that used the required spell piece, didn't receive the level up to unlock the next section. Tried repeating, making a different spell and re-logging but nothing made a difference. If there's something I haven't read and this is intended, than I apologize. Otherwise, this is quite an annoying bug.

Nothing appears in the general forge log, debug log or local log output.

Is there some way to edit player data for some quickfix or am I stuck?

**Comment by Psifour** [comment]
To make diagnosis a bit easier can you please provide the spell you are attempting to use?
Also a screenshot of your menu showing secondary operators selected.

Those two bits of information should eliminate the chance that it is user error and provide useful diagnostic information.

**Comment by Raserhead** [comment]
Just got back to this and was taking the screenshots to show the pages and spell, when for the hell of it I remade and tried the spell again, and it worked. I guess the server just needed to be restarted 6-10 times as I was fixing some other issue with a broken mod, even though I already restarted before.

Sorry for wasting your time I guess.

**Comment by garbast** [comment]
I was able to get the next level with

{spellName:"Debug",uuidMost:-8817459692684620212L,validSpell:1b,spellList:[{data:{key:"constantNumber",constantValue:"2"},x:4,y:2},{data:{params:{_number:1},key:"operatorSquare"},x:4,y:3},{data:{params:{_number:1,_target:2},key:"trickDebug"},x:4,y:4},{data:{key:"selectorCaster"},x:4,y:5}],uuidLeast:-5556507037629473567L}
