### ISSUE TITLE
Locked out of spell casting

### ISSUE THREAD

**Issue by Vorquel** [Vazkii/Psi#4]
Mods Installed:
FastLeafDecay-1.8-1.6
InventoryTweaks-1.60-beta-30
jei_1.8.9-2.25.11.150
journeymap-1.8.8-5.1.3-unlimited
Psi-beta-11
ToolsOnTheGo-1.8.9.1.2.1
VeinMiner-1.8.9_0.31.2.unknown

After I got psi metal infusion, I made a psimetal cad, with overclocked core and signalling socket, and suddenly I couldn't cast spells at all. My 11th level rolls back to unspent on the c menu, and I can still select spells on my cad, but the psi meter is gone and right clicking with either cad has no effect. The problem remains after reloading the world and restarting the game. Starting a new world seems to fix the problem for the new world, allowing me to reload all levels.

**Comment by Vazkii** [comment]
Do you still have your old CAD? You can only have one.

**Comment by Vorquel** [comment]
That was it. May I suggest some visual cue to make it more obvious that multiple CADs is unacceptable? Having it 90% of the way down the tl;dr tutorial is a bit hidden.

**Comment by yrsegal** [comment]
Perhaps have a cracked psi bar if you have two CADS?

**Comment by PsiGuy60** [comment]
The Mahouka explanation for non-dual-wieldable CAD's is that it causes resonance waves that causes your magic ability to effectively jam up. Maybe do something thematically with that, like red "waves" in the PSI bar, to indicate that you won't be able to cast spells with multiple CAD's?
