### ISSUE TITLE
CAD in off-hand uses stats from the main hand

### ISSUE THREAD

**Issue by Kachajal** [Vazkii/Psi#406]
For example, Break Block won't break stone if you don't have a pick equipped in your main hand. Enchantments also seem to work - Looting works with Explosion in a normal spell bullet, I haven't tested it extensively but presumably so does Fortune, the ability to break obsidian, etc. 

It'd be useful if someone could confirm, I didn't test this very extensively.

**Comment by Math321** [comment]
I haven't messed with enchantments, but I have noticed that Break Block uses the harvest level of whatever your main hand is holding. If you've got a diamond pick, then you can harvest obsidian. If you've got a wood pick, you can't harvest diamond ore. If your hand is empty, you can harvest dirt and sand, but not stone.

Break Block isn't the only Trick that cares about your harvest level, by the way. Collapse Block and Move Block do as well.

**Comment by Kachajal** [comment]
As a follow up, I used this glitch a bunch more. Fortune/silk touch do not actually carry over to the CAD - only the harvest level does. 

It does allow you to break obsidian instantly if you hold a diamond pick in your main hand.

Looting does work, but it's a separate thing completely - that's just how the enchantment works in vanilla, the same way you will gain the looting effect if you switch to a looting sword before your arrow kills something. So I would say that part is fine, or at least not an issue of Psi.

This behavior also has the side effect of making it so that using the relevant tricks on armor also works off of the harvest level of whatever you're holding, which is quite annoying.
