### ISSUE TITLE
Seemingly random crashes

### ISSUE THREAD

**Issue by Darth-Pikachu** [Vazkii/Psi#417]
So we were trying to figure out what was wrong with Kamefrede's Random Psideas addon, until eventually I tried it without the mod, and it took quite a bit longer for it to crash. In the end, it did end up crashing. I thought removing Thaumcraft was the fix. Later, however, I tested it with just Psi and AutoRegLib, and the crash persisted. There doesn't seem to be any specific thing triggering the crash, other than that there Psi bar kind of spazzes out, which I apparently can't screenshot, since it's moving around every frame.

Here's the entire log:
https://paste.ee/p/qwBd9

**Comment by Kamefrede** [comment]
User was able to replicate the issue with a smaller set of mods https://paste.ee/p/16UPl (will add a mirror later in case this expires)

**Comment by Math321** [comment]
Here's a paste that won't expire in 4 weeks like that one. https://pastebin.com/sG9uFs62
