### ISSUE TITLE
[Bug] Loopcast skipping the 2nd cast.

### ISSUE THREAD

**Issue by Darth-Pikachu** [Vazkii/Psi#423]
For some reason, Loopcast bullet skips the second cast entirely...sometimes. It's not all the time, but it's most of the time it seems,
 I have two images showing both cases happening:
https://imgur.com/a/WQWxyUs

The spell I used to test:
https://imgur.com/ZQ34E2C

**Comment by Vazkii** [comment]
Closing as it's probably the same as #409

**Comment by snydej** [comment]
I can confirm that this bug has not been fixed. I'm running Psi 1.16-97 as part of ATM6. The screenshot shows my debug spell and the chat output from me casting the spell twice. Every time I switch spells the first cast runs correctly and subsequent casts shows the bug.

![psi_loopcast_bug](https://user-images.githubusercontent.com/2817309/158900913-77111c6c-24b8-4a29-a935-6dd32898d6b8.png)
