### ISSUE TITLE
Losing psi energy 

### ISSUE THREAD

**Issue by Kuraen** [Vazkii/Psi#425]
Sorry but i dont find something related to this anywhere so i dont know if it is a feature or a bug. The thing is that when i get damage for something, my psi energy goes down. Sometimes, if i am sorrounded by creatures i cant use the psi caster because it stop the psi regeneration too. If someone can say something about this it will help.

**Comment by YaibaToKen** [comment]
Check your config as it's something you can change iirc

**Comment by Kuraen** [comment]
Maybe im idiot but i dont find nothing about that in mod options in the main menu or en in the folder of minecraft

**Comment by YaibaToKen** [comment]
Could have sworn there was an option for it. You are indeed supposed to love psi energy when getting damaged though.

**Comment by Kuraen** [comment]
ok, i notices something new, some times i dont know exactly why i lost psi energy even with nothing equiped or activated, this is weird
