### ISSUE TITLE
[Request] Some selectors that might be helpfull

### ISSUE THREAD

**Issue by mandujib** [Vazkii/Psi#426]
List : Casters
Creates list of nearby players, that has psi lv more than one. (Same as other list creators, but players only)

Trick : Psionic Link
Creates psi link, where recharge speed is shared with the entity given, and also psi pool is shared untill the link is broken. If psi is drained of this link, both players suffer from psi drain damage. Gets entity as input, and makes error if that is not psi enabled player. Also, breaks link if entity given already has psi link.

Trick : Particle & Particle+
Works simmilar to block conjuration, where first one creates one particle and the latter creating multiple. Gets one vector, one vector as optional, and one numerical value. First being the position of particle, second being the movement of the particle. Third one is particle life. If the multiple version is not available, make it real low since it is just visual thing.

**Comment by gdavid04** [comment]
Psionic link should work for any mob, giving small regen bonus when it isn't a caster.
