### ISSUE TITLE
If there is an empty space below the position given to Torrent as an input, Torrent places the water there instead.

### ISSUE THREAD

**Issue by sharenohana** [Vazkii/Psi#44]
I replaced Torrent with Debug to check, and the vectors themselves aren't wrong. Here's the spell I was using.

{spellName:"Water Bucket",uuidMost:2400712205254935835L,validSpell:1b,spellList:[0:{spellPosX:2,spellData:{spellKey:"selectorCaster",params:{}},spellPosY:3},1:{spellPosX:2,spellData:{spellKey:"operatorEntityLook",params:{psi.spellparam.target:1}},spellPosY:4},2:{spellPosX:2,spellData:{spellKey:"connector",params:{psi.spellparam.target:1}},spellPosY:5},3:{spellPosX:3,spellData:{spellKey:"operatorEntityPosition",params:{psi.spellparam.target:3}},spellPosY:3},4:{spellPosX:3,spellData:{spellKey:"operatorVectorRaycastAxis",params:{psi.spellparam.ray:3,psi.spellparam.max:0,psi.spellparam.position:1}},spellPosY:4},5:{spellPosX:3,spellData:{spellKey:"connector",params:{psi.spellparam.target:3}},spellPosY:5},6:{spellPosX:3,spellData:{spellKey:"connector",params:{psi.spellparam.target:1}},spellPosY:6},7:{spellPosX:4,spellData:{spellKey:"connector",params:{psi.spellparam.target:3}},spellPosY:3},8:{spellPosX:4,spellData:{spellKey:"operatorVectorSum",params:{psi.spellparam.vector1:3,psi.spellparam.vector2:4,psi.spellparam.vector3:0}},spellPosY:4},9:{spellPosX:4,spellData:{spellKey:"trickTorrent",params:{psi.spellparam.position:1}},spellPosY:5},10:{spellPosX:4,spellData:{spellKey:"connector",params:{psi.spellparam.target:3}},spellPosY:6},11:{spellPosX:5,spellData:{spellKey:"connector",params:{psi.spellparam.target:3}},spellPosY:3},12:{spellPosX:5,spellData:{spellKey:"operatorVectorRaycast",params:{psi.spellparam.ray:2,psi.spellparam.max:0,psi.spellparam.position:1}},spellPosY:4},13:{spellPosX:5,spellData:{spellKey:"connector",params:{psi.spellparam.target:2}},spellPosY:5},14:{spellPosX:5,spellData:{spellKey:"connector",params:{psi.spellparam.target:3}},spellPosY:6}],uuidLeast:-5854559433899590161L}

**Comment by Vazkii** [comment]
Intended behaviour to offset rounding errors in projectiles.
