### ISSUE TITLE
Inventory desync with CAD items

### ISSUE THREAD

**Issue by Hubry** [Vazkii/Psi#446]
Moving CAD items around sometimes causes a visual desync, where you can see 2 CADs in different places or one in a wrong position in the inventory. It is more common when shift-clicking items in the player inventory or using a sorting mod like InvTweaks.
Clicking on one of the affected slots corrects the desync, but it is quite annoying.

Using Psi 1.1-59, Forge 14.23.5.2772.

**Comment by yrsegal** [comment]
May have been fixed by edac4cf08830f4e7a5ab31c6b5842af879db34e3
