### ISSUE TITLE
Psimetal pickaxe ceased being able to mine cobalt/ardite

### ISSUE THREAD

**Issue by ItsTheKais** [Vazkii/Psi#449]
Prior to r1.1-60, the psimetal pickaxe was able to mine cobalt and ardite ore. In r1.1-60 and 61, the psimetal pickaxe slowly destroys blocks of that level instead.

* Psi r1.1-61
* AutoRegLib 1.3-21
* Forge 14.23.5.2772

**Comment by Kamefrede** [comment]
That is intended behaviour as the Psimetal tools were supposed to have a mining level of diamond. But, prior to r1.1-60 they weren't registered as such.
