### ISSUE TITLE
Error When Jumping

### ISSUE THREAD

**Issue by RoyaII** [Vazkii/Psi#457]
https://pastebin.com/Q0wW1w7Z

Just what it says on the tin.  I have some serious doubts that it's Psi causing this (because I haven't updated it), but that snippet of my server's log is the only kind of information I have, and it mentions Psi jump spell triggers.  Which is funny because I'm not even wearing Psimetal boots, much less using a jump-trigger spell.

I don't CDT or get any sort of log, I get "A fatal error has occurred, this connection is terminated".

EDIT:  This only seems to happen on the server, though I still can't imagine why; it's essentially a clone of my own instance, minus Optifine.

OTHER EDIT:  Tested both with and without Optifine; no error on the client log, only on the server's.

OTHERER EDIT:  It's definitely a problem with Psi, since removing it from the server fixed the issue.

**Comment by Vazkii** [comment]
https://github.com/Vazkii/AutoRegLib/issues/21
