### ISSUE TITLE
Psi energy taken after spell was casted?

### ISSUE THREAD

**Issue by bloop428** [Vazkii/Psi#46]
I was trying to make a 3x3 mining spell when I noticed that some psi energy was being taken even after I broke the blocks.

Spell:
![e0arlyx](https://cloud.githubusercontent.com/assets/6138413/13063768/2c0c1088-d400-11e5-9ddd-32f3e38b09e6.png)

Effect and psi energy being taken:
(I can't get the bug to repeat, it seems about 600 psi is just randomly taken away when I switch between the pickaxe and another item.)

**Comment by konals** [comment]
That's not a bug, the pickaxe will drain some Psi energy to repair itself if you don't have it in your hand.

**Comment by bloop428** [comment]
Oh yes, I forgot about the repairing. Thanks for reminding me!
