### ISSUE TITLE
Crash on 1.67 Psi 1.12.2 when I launch world

### ISSUE THREAD

**Issue by Shaawnn** [Vazkii/Psi#469]
https://paste.ubuntu.com/p/MkXcrRzwQ5/   --    crash report

Not very knowledgable in any of this, but I posted on the minecraft forum and I was told the crash was due to PSI, and I should contact the dev. If I was pointed the wrong way feel free to close this, but I appreciate the help nonetheless.

**Comment by FoxMcloud5655** [comment]
Totally unrelated to your issue, but you're setting the values for memory twice:
```
-Xmx7168m -Xms256m -XX:PermSize=256m -XX:+UseG1GC -Xmx7G -Xms7G
```
Just a heads-up.
