### ISSUE TITLE
Psi Meter goes down when using Sacrificial Dagger

### ISSUE THREAD

**Issue by eslachance** [Vazkii/Psi#47]
When I use the blood magic Sacrificial Dagger in front of an altar, my Psi energy goes down by exactly 160 (which I'm not sure, but sounds like the amount of LP injected in a Tier 0 altar).

**Comment by DaedalusGame** [comment]
taking damage from anything reduces your psi energy slightly apparantly because pvp raisins?

**Comment by yrsegal** [comment]
Either way, this is intended behavior.

**Comment by eslachance** [comment]
Good to know!
