### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by bogointeractive** [Vazkii/Psi#470]
Before you report an issue, make sure these boxes are checked.

- [x] Make sure you're not reporting something that was just fixed.
- [x] Make sure you're not using an old version of Psi.
- [x] Make sure you're not using Optifine or GLSL Shaders, if it's a rendering issue.
- [x] Make sure you're using Java 8. Psi will not function in older versions.

After you've done so, delete this template, and proceed with your issue report.

I just downloaded the latest version. I got a forge Mod loader missing registry entries. it is minecrat:items:
psi:conjured

I am not sure if it got left out?

**Comment by yrsegal** [comment]
This is intended.

**Comment by Vazkii** [comment]
Keeping it open so people see it.

**Comment by yrsegal** [comment]
This is being closed as the remapper hides the warning.
