### ISSUE TITLE
Unable to level up in psi

### ISSUE THREAD

**Issue by Sunekaer** [Vazkii/Psi#472]
Issue: When I use the debug spell to complete the tutorial and reach level 2 to continue the mod, it just doesn't level up and stucks in level 1 
tried using the lastest version (1.1-69) and the bug is still happening
Fortunately with the new command /psi-learn you are able to learn the 2º mission and keep making progress through the mod normally, it seems to only be bugged the first mission

https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/129

**Comment by yrsegal** [comment]
Possible fix: Try learning the spell group again. It might have been unselected, due to the way the update worked.

**Comment by yrsegal** [comment]
@Sunekaer requesting followup?

**Comment by Sunekaer** [comment]
Havent had any reports about the issue since
