### ISSUE TITLE
Rendering Issue in inventory with Focusing Plate Armor

### ISSUE THREAD

**Issue by NullDragon** [Vazkii/Psi#473]
Hard minecraft crash when viewing inventory(and thus looking at player) while wearing psi armor. Unsure where the issue is exactly, other than either in the helmet, leggings, or boots. Loaded mods should be in the crashlogs, if you need any more information I can try and answer.

Problem was resolved for the moment by removing the armor via the Rod Constructor GUI, 

EDIT: Also, issue happened in version 69, which our server recently updated to. We had no issues at all with the mod in version 63, which I believe was the last version our server used.

[crash-2019-01-14_23.57.43-client.txt](https://github.com/Vazkii/Psi/files/2758106/crash-2019-01-14_23.57.43-client.txt)
[crash-2019-01-15_00.03.38-client.txt](https://github.com/Vazkii/Psi/files/2758107/crash-2019-01-15_00.03.38-client.txt)
[crash-2019-01-14_23.53.02-client.txt](https://github.com/Vazkii/Psi/files/2758108/crash-2019-01-14_23.53.02-client.txt)

**Comment by yrsegal** [comment]
https://github.com/wiiv/MagicalPsi/issues/10
