### ISSUE TITLE
As of Stoneblock 2 1.4 MC 1.12.2, 

### ISSUE THREAD

**Issue by Solverbolt** [Vazkii/Psi#479]
PsiDust is now completely uncraftable, player is stuck at level 0 permanently No bypass commands work.

Tried every available suggestion, and still nothing. Also noticed that apparently every time someone as else posted a similar problem on here, its closed immediately, which makes me believe that this mod should be removed from Stoneblock in the future. 

I will be forwarding the recommendation to all Modpack developers. Not even going to ask for help from the staff here,  As I have had it with most of the Mod Developers who are github these days and their inability to act with any form of decorum or actually attempting to resolve issues. Do not bother responding, as I am going to take an immediate screenshot for my records, and will spend my now limitless amount of available time to getting certain mod developers (if you can call them that) removed.

**Comment by yrsegal** [comment]
wew lad
