### ISSUE TITLE
loopcast cancel bug

### ISSUE THREAD

**Issue by SnazzGass** [Vazkii/Psi#480]
The loopcast bullet gets canceled after only 2 casts if you use this spell:

![image](https://user-images.githubusercontent.com/45057060/52540267-9c97ea00-2d3c-11e9-9a35-3dca2b8aca98.png)

This bug seems to be present in all loopcast spells that change a save vector to a unique value every time they iterate.

**Comment by yrsegal** [comment]
I think I know what's going on... and I wish I didn't
