### ISSUE TITLE
Tile Mislabeling

### ISSUE THREAD

**Issue by SnazzGass** [Vazkii/Psi#487]
![2019-03-07_21 40 59](https://user-images.githubusercontent.com/45057060/54010017-f44e2900-4121-11e9-8eec-dd070d832589.png)
My mouse is hovering over the number constant, not the vector construct; This ain't it chief!

The label should be of the tile you are hovering over, not the one you have selected.

**Comment by Kamefrede** [comment]
Fixed in 4806a14
