### ISSUE TITLE
Programmer Lag

### ISSUE THREAD

**Issue by SnazzGass** [Vazkii/Psi#488]
I noticed that spell programmers are causing massive FPS drops when I look at them
![2019-03-07_22 02 10](https://user-images.githubusercontent.com/45057060/54010776-f960a780-4124-11e9-9224-dea33093fb30.png)
While I'm not looking at them, I'm getting 80 -100 fps, while i look at them, its 15 - 25.

**Comment by yrsegal** [comment]
This... is not trivial to solve. I'd have to scrap all of the rendering code, and put in *massive* infrastructure for atlasing.

**Comment by LemADEC** [comment]
You can use the TextureStitchEvent.Pre event to register your textures in the atlas and avoid constantly reloading.

**Comment by yrsegal** [comment]
I know what would be required, but that's not the issue... it's much more complicated than that

**Comment by williewillus** [comment]
fixed in 1.15 (at least to the best of our ability)
renders 128 programmers all with complex spells at 60fps on a 1070
