### ISSUE TITLE
Player Motion Bug

### ISSUE THREAD

**Issue by SnazzGass** [Vazkii/Psi#490]
Player motion bug strikes again!

This bug applies to all motion tricks:
-mass exodus
-add motion
-mass add motion

there seems to be a little bit of drag applied when you cast a motion spell targeting yourself. This is most noticeable on leggings spells like [this one](https://imgur.com/k307Lev).
Its a simple moonwalk spell, but it seems to prevent you from moving quickly in the x and z directions. 

Through some testing, I've noticed that this bug also applies in the direction that you are applying motion towards. This bug is not limited to legging spells.

**Comment by yrsegal** [comment]
So, to add to your testing, this *only* affects your player input, and not other things applying speed. This is... odd, but I think I know what's going on.
