### ISSUE TITLE
Box title and description not showing up

### ISSUE THREAD

**Issue by Archmage11** [Vazkii/Psi#491]
On the latest version of forge and the mod, and when hovering over boxes for the spell programmer, the titles and descriptions don't show up, only when replacing a previous box. (The selected box was being hovered over with the mouse.)
![2019-03-08_15 29 02](https://user-images.githubusercontent.com/22826430/54054263-ba2f6680-41b7-11e9-9927-d9972cfd5b1e.png)
![2019-03-08_15 29 10](https://user-images.githubusercontent.com/22826430/54054264-bac7fd00-41b7-11e9-97a2-b20166a0f79c.png)

**Comment by Archmage11** [comment]
Just did some more testing, this bug is new to the latest version. I believe it is related to #487.

**Comment by Archmage11** [comment]
I've found this is a bug rendering when the mouse is over the box, implemented in the "Allow addons to hook into comment and tooltip render" commit. Rendering only works when the box is selected.

**Comment by Kamefrede** [comment]
Fixed in 4806a14
