### ISSUE TITLE
Level points persistency

### ISSUE THREAD

**Issue by Feztacular** [Vazkii/Psi#493]
Loading a new world and clicking the check mark on "Psi has found save data from previous world" it seemingly gives me my level points back, but if I try to learn the tutorial it drops to zero.
If any more info is needed, I can give a mod list and stuff

**Comment by wuzzard** [comment]
I am also having this issue.  Its seems that no matter how many different approaches I try, the import fails to give me my levels.  Is there another workaround so we don't have to keep running through these tutorials over and over again?

**Comment by yrsegal** [comment]
Hrm, this is my fault, due to the way I solved previous issues. I can fix this.
