### ISSUE TITLE
Psi crashed and I don't know what to do.

### ISSUE THREAD

**Issue by JadedJewel** [Vazkii/Psi#497]
I've tried taking out other mods to see what would happen and nothing would work. (I'm new to this so please be easy)

[crash-2019-04-15_23.34.31-client.txt](https://github.com/Vazkii/Psi/files/3079890/crash-2019-04-15_23.34.31-client.txt)

**Comment by JadedJewel** [comment]
I don't really know what I'm supposed to do or how to use this github so please be easy

**Comment by yrsegal** [comment]
Please update AutoRegLib.

Also, for future reference, it would be ideal if crashes were uploaded to a site like [pastebin](https://pastebin.com) or [gist](https://gist.github.com).

**Comment by JadedJewel** [comment]
Thank you and sorry for that.

**Comment by JadedJewel** [comment]
Thank you, sorry about that.
