### ISSUE TITLE
The Modulo Operator doesn't work

### ISSUE THREAD

**Issue by WilhelmW** [Vazkii/Psi#498]
Mod version: r1.1-74
AutoRegLib version: 1.3-26

The modulo operator always returns the first number

Example:
{spellName:"Debug",uuidMost:-3142906757231709L,validSpell:1b,spellList:[{data:{key:"constantNumber",constantValue:"10"},x:4,y:3},{data:{params:{_number2:2,_number1:1},key:"operatorModulus"},x:4,y:4},{data:{key:"constantNumber",constantValue:"10"},x:4,y:5},{data:{params:{_number:0,_target:3},key:"trickDebug"},x:5,y:4}],uuidLeast:-7551875155270756888L}

Returns: 10
Should return: 0

**Comment by Kamefrede** [comment]
Fixed!
