### ISSUE TITLE
Crash when calculating vector to nearest animal in exosuit leggings [r1.1-75]

### ISSUE THREAD

**Issue by bg95** [Vazkii/Psi#501]
I was writing a spell that outputs (with Trick: Debug) the vector from the caster to the nearest animal. When I put it in exosuit leggings and equip them, the game crashes either immediately or after outputting debug messages for a while. I guess it crashes when Minecraft saves the world.

Steps to reproduce: 1. Put the following spell in a spell bullet 2. Put the bullet into exosuit leggings 3. Equip the leggings 4. Wander around for a while and wait the game to crash

I was running Psi-r1.1-75, forge 1.12.2-14.23.5.2836

The spell is here:
![2019-04-29_18 01 55](https://user-images.githubusercontent.com/5005937/56890010-cf838b80-6aaa-11e9-93a2-5028db8f5d92.png)

{spellName:"Debug",uuidMost:-60113132898071130L,validSpell:1b,spellList:[{data:{params:{_number:0,_target:4},key:"trickDebug"},x:3,y:2},{data:{key:"selectorCaster"},x:3,y:3},{data:{key:"constantNumber",constantValue:"10"},x:3,y:4},{data:{params:{_vector3:0,_vector2:2,_vector1:4},key:"operatorVectorSubtract"},x:4,y:2},{data:{params:{_target:3},key:"operatorEntityPosition"},x:4,y:3},{data:{params:{_position:1,_radius:3},key:"selectorNearbyAnimals"},x:4,y:4},{data:{params:{_target:2},key:"operatorEntityPosition"},x:5,y:2},{data:{params:{_target:2,_position:3},key:"operatorClosestToPoint"},x:5,y:3},{data:{params:{_target:3},key:"connector"},x:5,y:4}],uuidLeast:-6983783113233740710L}

The crash report is here:
[crash-2019-04-29_18.02.11-server.txt](https://github.com/Vazkii/Psi/files/3126911/crash-2019-04-29_18.02.11-server.txt)

**Comment by Kamefrede** [comment]
Fixed in 3c2aace
