### ISSUE TITLE
Format Errors on various items

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Vazkii/Psi#503]
It appears that a lot of items in Psi have java format error messages on their shift-info.
The items affected are:
CAD Assemblies
CAD Cores
CAD Sockets
CAD Batteries
CAD Colorizers
Spell Bullets
Psimetal tools and armor

Psi r1.1-75
Forge 14.23.5.2836

**Comment by Kamefrede** [comment]
Fixed in ccf2f24
