### ISSUE TITLE
NPE ticking entity 1.1-75

### ISSUE THREAD

**Issue by kreezxil** [Vazkii/Psi#504]
https://paste.ubuntu.com/p/2HssWkJ53G/

**Comment by kreezxil** [comment]
for a dedicated server

**Comment by kreezxil** [comment]
I don't know what the player(s) was(were) doing.

**Comment by kreezxil** [comment]
rolling down to 1.1-75 didn't seem to help, got a very similar crash with my dedicated server.

http://paste.ubuntu.com/p/wjJZJvbXhh/

**Comment by triacontakai** [comment]
Got the same issue on an Enigmatica 2 1.66 dedicated server:
https://pastebin.com/sZEmdDSJ

**Comment by Kamefrede** [comment]
> https://paste.ubuntu.com/p/2HssWkJ53G/
Misleading title since you're running version 75, try updating and see if it still crashes




> Got the same issue on an Enigmatica 2 1.66 dedicated server after one of my players ran a spell:
> https://pastebin.com/sZEmdDSJ

This has been fixed in psi 76, please update.

**Comment by kreezxil** [comment]
Nice catch, I must've typoed the title, i'll correct that. and update.
