### ISSUE TITLE
Network-related error kicks players from dedicated servers

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Vazkii/Psi#514]
This has happened several times, and I haven't been able to discern a pattern. So far it's only happened when multiple people are online.

Here's the exact message that appears in server chat when it happens: https://gist.github.com/TheDeviantCrafter/ca408cb4216d228d5e68e3946a95a021

Here's the entire log:
https://gist.github.com/TheDeviantCrafter/16b95493a7ea5fb9979756b277a2e764

**Comment by TheDeviantCrafter** [comment]
This appears to happen whenever one of my players takes damage with a CAD in their inventory. It has happened when other players are online, but it seems to disconnect everyone whenever any player encounters the issue.

Here is that player's playerdata file: https://www.dropbox.com/s/42aq3skcp662zwa/ea7f4dcc-de95-4e0f-884d-9618d327a275.dat?dl=0

**Comment by Rithsagea** [comment]
Note: the cad having an unstable battery from random psideas seems to prompt this issue

**Comment by Rithsagea** [comment]
If you take damage with a cad that has the unstable battery, you only get kicked after you jump. you can do literally anything, but jumping causes you to be kicked for the reason "A fatal error has occurred, this connection is terminated"

**Comment by Rithsagea** [comment]
This issue also occurs with the shielded cad battery (also from random psideas)

**Comment by Hubry** [comment]
Seems like this is purely on Psideas side, they are trying to send a Psi packet on LibLib's channel where it's not recognized.

**Comment by TheDeviantCrafter** [comment]
Closed. Please continue the discussion on the Random PSIdeas issue linked above.
