### ISSUE TITLE
Combat Magic: Missing Psi Rendere Helper

### ISSUE THREAD

**Issue by StempunkDev** [Vazkii/Psi#518]
Hello I dont know if this is Psi related or if i need to report this to the creator of Psi: Combat Magic
Specs: 

- Psi-r1.1-77
- rpsideas-2.4.2
- Psi Addons 1.1.05 (Combat Magic)

The Game crashes after a cast of a spell from Combat magic

The Error states that the Class Pointer is null and the Class is not existing.
I checked that and it ist true.

So i asked myself if it is a Psi relatet issue. If not please tell me what that class did and i will fix the other mod, if it is open source, myself.

Sincerely Leonard Krusch

P.S.: My English skills may be a little rusty
**Crashreport:**
[crash-2019-07-03_15.45.24-client.txt](https://github.com/Vazkii/Psi/files/3355313/crash-2019-07-03_15.45.24-client.txt)

**Comment by yrsegal** [comment]
Psi is not at all at fault. Combat magic is not well coded.

**Comment by StempunkDev** [comment]
Than may i ask you, what dose the class do then and where is the functionality now?

**Comment by yrsegal** [comment]
It helps rendering, and I believe it was removed as it was unused.

**Comment by StempunkDev** [comment]
Thanks :D 

So i basicly need to write to the author of the other mod to either change the way spells are rendered or patch in the missing class.

**Comment by yrsegal** [comment]
Or just report it to them...

**Comment by StempunkDev** [comment]
Than i guess ill do that 
Thanks a lot
