### ISSUE TITLE
Place Block Always Placing North

### ISSUE THREAD

**Issue by oliverrook** [Vazkii/Psi#52]
Ok, so, I made a program that I called "bridge". I've been programming for almost 10 years now, so I know what to look for in stuff like this. I did find several things. However, after about two to three hours of using this mod, something strange happened. I am using beta 13 of the mod. The program I made places a block at the caster, and uses the players look and position to raycast from the player to a space up to 10 blocks away. I had been creating spells for a while at this point, on my creative world, though I did switch back and forth between creative and survival several times. I had created the spell using a break block spell I had made called "troll hole", which used a raycast to create a hole two blocks deep at the point where it hit, thus the "troll" part, as I intended it to be a hole that the player couldn't climb out of easily. The spell worked perfectly, so I reused the raycast I had made in the spell to create the before mentioned spell. This was about two hours after I had made the "troll" spell. However, when I cast it, I noticed a very peculiar bug. No matter which direction I cast the spell, or what block I pointed it at, the spell always placed the blocks going north, only occasionally taking into account the x position, though y was always unaffected (y was the only part of the vector I modified, so that it would place at the feet of the caster, rather than their face). After several castings of the spell, eventually blocks stopped being placed, though were still taken from my hotbar. Unlike an invisible block glitch (like in vanilla minecraft), however, I was still allowed free movement where ever the blocks would have been placed (I checked in all directions just to be sure).

EDIT: I would have uploaded a screenshot, but when I came back into my world a few hours later, none of the blocks seemed to be placed anymore, and the spell seemed to just do nothing at that point, plus I had already removed the block I had made it with to see if it was a placement issue.

**Comment by sharenohana** [comment]
Please at least post a clipboard export of your spell so it can be reproduced. Also, you don't have the latest version, so you should probably update to beta 14.

**Comment by Vazkii** [comment]
Please repost this so it looks like a bug report and not a paragraph of creepypasta.
