### ISSUE TITLE
1 Tick Conjured blocks have no hitbox or particles

### ISSUE THREAD

**Issue by SnazzGass** [Vazkii/Psi#521]
Title Says it all; If you conjure a block and set it to 1 tick, there is no hitbox or particles, if you are casting every tick on leggings, the conjured block acts like a ghost block; you can hit it with a raycast, but you cant walk through it.

**Comment by Kamefrede** [comment]
The hitbox part is fixed, but the particle part is intended.
Conjured blocks tick randomly so there's a chance it doesn't show up, although now that chance is rather low.
