### ISSUE TITLE
Griefing with Psi

### ISSUE THREAD

**Issue by Raycoms** [Vazkii/Psi#528]
Hi, I'm one of the developers of the Minecolonies mods and we got recently some reports that your mod can be used to circumvent our protection system.

While your mod hooks in the case of break block in the forge event system, none of the following options I can block easily.

https://github.com/Vazkii/Psi/blob/fbc40838658d41ea8293198f4fd2795d90b4f9fd/src/main/java/vazkii/psi/common/spell/trick/PieceTrickTorrent.java

https://github.com/Vazkii/Psi/blob/fbc40838658d41ea8293198f4fd2795d90b4f9fd/src/main/java/vazkii/psi/common/spell/trick/PieceTrickSmite.java

https://github.com/Vazkii/Psi/blob/fbc40838658d41ea8293198f4fd2795d90b4f9fd/src/main/java/vazkii/psi/common/spell/trick/block/PieceTrickPlaceBlock.java

**Comment by Kamefrede** [comment]
Fixed in a2dfe8a.

**Comment by immijimmi** [comment]
Hi, this doesn't appear to be fixed for 1.12.2 - is it possible to apply to that version as well?
