### ISSUE TITLE
Game crash, ParticleRenderDispatcher error

### ISSUE THREAD

**Issue by Sticcia** [Vazkii/Psi#529]
Playing All The Mods 3, game crashes with no "crash report" but a log is available:
[hs_err_pid18400.log](https://github.com/Vazkii/Psi/files/3667549/hs_err_pid18400.log)
Line 79 makes me think it's a Psi related issue, reason why I'm posting this here:
`J 72476 C1 vazkii.psi.client.fx.ParticleRenderDispatcher.onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V (104 bytes) @ 0x000000000bcdb56c [0x000000000bcd9820+0x1d4c]`
Crash is pretty random, often happens when I load the world or when I sort a chest or inventory.
I have not played with Psi itself yet, I would love to though so I wish to not remove the mod completely.
Is there a way to disable particles for Psi?

**Comment by Kamefrede** [comment]
Yes, set the particle limiter to zero in the config.
