### ISSUE TITLE
Allow taking multiple inputs from the same side

### ISSUE THREAD

**Issue by ThomasRules2000** [Vazkii/Psi#53]
In some of my spells, I use vector constructs, where 2 of the values I want to be the same. However, I can't place these constructs into a space with only 2 places for inputs, as the vector construct can't take multiple of the same input from the same side.

**Comment by Vazkii** [comment]
This breaks one of the fundamental principles of Psi, which is to allow for a spell to be recreated given a single screenshot.

**Comment by ThomasRules2000** [comment]
Well, you fixed it with the construct thing anyway, so thanks
