### ISSUE TITLE
Psi crashing on load - java.lang.NoClassDefFoundError: vazkii/arl/item/ItemModShovel

### ISSUE THREAD

**Issue by Th4nat0s1s** [Vazkii/Psi#530]
https://pastebin.com/mj9qrKsC

java.lang.NoClassDefFoundError: vazkii/arl/item/ItemModShovel

Getting this log while trying to load Psi, just added the Random Psideas mod with dependencies.

Tried updating to newest version of FML, also tried redoing download for  Psi r1.1-77 and tried r1.1-76.

Any direction I can take with this issue would be much appreciated.

**Comment by Th4nat0s1s** [comment]
After further testing, I tried removing all of random psideas with dependencies  and just had psi r1.1-77 and it is still crashing for me

https://pastebin.com/AJeRatpJ

Seems to be the same issue: Caused by: java.lang.NoClassDefFoundError: vazkii/arl/item/ItemModShovel

**Comment by Kamefrede** [comment]
update AutoRegLib

**Comment by Th4nat0s1s** [comment]
Yup, that did it, but how did you know? Im asking cause I need to get better at troubleshooting my own problems.1

**Comment by yrsegal** [comment]
Because the issue was related to a missing ARL class.
