### ISSUE TITLE
"Something prevented you from casting that spell" & missing "itemModShovel"

### ISSUE THREAD

**Issue by jgilmore** [Vazkii/Psi#531]
I'm sorry for the unhelpful messages. I would supply more details if I had any. On that note, good programming tools (and a programming tool is what, in a sense, psi is) give good error messages. The above error message is NOT good. Please give more descriptive error messages!

To recreate: Start game, create cad, load a spell bullet with the simplest possible valid spell (debug self) and attempt to cast it.

In fact, EVERY SPELL I attempt to cast gives the same error message. I tried some I'd downloaded (in creative mode, obviously) and got the same message. I tried (again, in creative) creating some (very slightly) more advanced spells. All got the same message.

I'm on 1.12.2, psi Psi-r1.1-62.jar. Upgrade to .77 you say?
Crash!
Caused by: java.lang.NoClassDefFoundError: vazkii/arl/item/ItemModShovel

how about .76? Nope, same. Maybe a dependancy fixes it? update AutoRegLib? Nope.

In conclusion, recent versions of PSI crash and the older one can't cast spells.

Sorry for lack of details, I'd debug this further but I'm not really familiar enough with Java to make the attempt in a reasonable time frame.

I do have a number of other mods. Full list is:
ae2stuff-0.7.0.4-mc1.12.2.jar
AkashicTome-1.2-10.jar
angelRingToBauble-1.12-0.3.1.50+d4e654e.jar
appliedenergistics2-rv5-stable-11.jar
astralsorcery-1.12.2-1.9.4.jar
AutoRegLib-1.3-20.jar
badwithernocookiereloaded-1.12.2-3.1.14.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar
BloodMagic-1.12.2-2.3.3-101.jar
Botania+r1.10-362.jar
CodeChickenLib-1.12.2-3.2.0.345-universal.jar
CoFHCore-1.12.2-4.5.2.19-universal.jar
CoFHWorld-1.12.2-1.3.0.6-universal.jar
CookingForBlockheads_1.12.2-6.4.65.jar
CraftTweaker2-1.12-4.1.11.jar
CustomOreGen-1.12-1.8.1.jar
DummyCoreUnofficial-2.4.112.5.jar
EnderCore-1.12.2-0.5.41.jar
EnderIO-1.12.2-5.0.35.jar
extrautils2-1.12-1.9.4.jar
ExtremeReactors-1.12.2-0.4.5.49.jar
forestry_1.12.2-5.8.1.322.jar
furniture-5.13.0-1.12.2.jar
gravestone-1.10.1.jar
Guide-API-1.12-2.1.6-61.jar
InventoryTweaks-1.63.jar
jei_1.12.2-4.12.1.217.jar
LibEx-1.12.2-1.0.8.jar
MagicBees-1.12.2-3.1.10.jar
Mantle-1.12-1.3.2.24.jar
mcjtylib-1.12-3.0.5.jar
mystcraft-1.12.2-0.13.6.00.jar
mysticallib-1.12.2-1.3.7.jar
MysticWorld-1.12.2-1.4.4.jar
OptiFine_1.12.2_HD_U_E2.jar
Pam's+HarvestCraft+1.12.2zf.jar
Patchouli-1.0-20.jar
ProjectE-1.12-PE1.3.1B.jar
Psi-r1.1-76.jar
randompatches-1.12.2-1.18.2.1.jar
RedstoneFlux-1.12-2.0.2.3-universal.jar
roots-2-0.104.jar
Ruins-1.12.2.jar
Tainted-Magic-r7.82.jar
Thaumcraft-1.12.2-6.1.BETA25.jar
thaumicbases-3.2.265.4r-BBF.jar
ThaumicEquivalence-1.12.2-1.0.5.jar
ThaumicJEI-1.12.2-1.5.3-20.jar
ThermalDynamics-1.12.2-2.5.1.14-universal.jar
ThermalExpansion-1.12.2-5.5.0.29-universal.jar
ThermalFoundation-1.12.2-2.5.0.19-universal.jar
Treecapitator-1.12-at_0.9a.jar
twilightforest-1.12.2-3.8.689-universal.jar
WIT-1.12-1.0.24-43.jar
Xaeros_Minimap_1.18_Forge_1.12.jar
zerocore-1.12-0.1.2.2.jar

**Comment by Kamefrede** [comment]
Bruh
You're 12 versions behind on ARL just use ARL 1.3-32 and PSI 77
