### ISSUE TITLE
trick: place block places at wrong coordinates

### ISSUE THREAD

**Issue by Behem07h** [Vazkii/Psi#534]
i'm giving a trick:place block the vector [789.1, 22.00, 1116]
and psi is placing a block at [789,  21, 1115]
/setblock command places a block at [789, 22, 1116] if given the coordinates [789.1, 22.00, 1116]

How to recreate: Set saved vector 3 to the vector of a known block in the world. put [this spell](https://imgur.com/r53CBlQ) into a normal spell bullet, stand near the block and activate the spell bullet. The coordinates of the block placed will be off by 1 on the y and z coordinates. (note: a block next to cad is required)

**Comment by SnazzGass** [comment]
This actually relates to the other issue you opened. When psi shortens a axis of a vector, it rounds it off. So it can sometimes look like psi isn't lining up vectors correctly. Im guessing that the z axis of that vector is between 1115.5 and 1116. so when it gets shortened to a max of 5 displayed characters per axis, it gets rounded up and displayed as 1116.
![2019-11-20_22 07 33](https://user-images.githubusercontent.com/45057060/69312152-08b85000-0be3-11ea-96ac-cf3e213911ff.png)

**Comment by Kamefrede** [comment]
Works as intended
