### ISSUE TITLE
Vectors do not increase past 4 digits

### ISSUE THREAD

**Issue by Behem07h** [Vazkii/Psi#535]
when doing a vector sum of  [800.1, 20.00, 1137] and [0.400, 0.500, 0.500], the output is [800.5, 20.50, 1137] instead of [800.5, 20.50, 1137.5].

This means that spells that make use of vectors become inaccurate or completely break as the player travels further from [0,0,0] 

How to reproduce: Using vector construct, construct the vectors [800.1, 20.00, 1137] and [0.400, 0.500, 0.500]. Use vector sum to find the sum of the two vectors, and use a debug trick to output this to chat.

**Comment by SnazzGass** [comment]
actually, the vector does contain accurate data, It just doesn't show more than 5 characters per axis. In your example, if you try extracting the z axis from the vector and debugging that, you will get 1137.5

**Comment by Kamefrede** [comment]
Invalid issue.
