### ISSUE TITLE
[request] enable direct spell piece inputs to be reused

### ISSUE THREAD

**Issue by transfarmer** [Vazkii/Psi#538]
Sometimes I have to connect multiple inputs of a spell piece to the same other spell piece, which can be achieved only by using connectors for a second connection. It would be useful if I could instead directly link the second piece to both of the first piece's inputs.

**Comment by SnazzGass** [comment]
Unfortunately, Vazkii already stated that he isn't going to implement this.

**Comment by Kamefrede** [comment]
This is not something that Vazkii feels to be thematical with the mod, however any addon developer is welcome to add this.
