### ISSUE TITLE
Selector: Block Broken returns null vector if block is outside of vanilla reach distance.

### ISSUE THREAD

**Issue by Behem07h** [Vazkii/Psi#539]
Selector: block broken returns a null vector if the block broken is outside of a vanilla player's reach distance

Steps to reproduce:
1. put this spell: https://imgur.com/3Ylwj3h in a normal spell bullet, in a psimetal pickaxe.
2. Select the spell in the pickaxe
3. equip botania's ring of far reach, make sure to have something to supply mana in your inventory (e.g mana tablet)
4. use the psimetal pickaxe to break a block that is more than 4 blocks away from the player (4 blocks is the maximum reach distance of a player in survival mode, in vanilla minecraft)
5. the spell should give the error "ERROR: Spell Operation Vector is non existent or null. Error Position [4, 4]."
6. Break a block that is within the reach distance of a vanilla player. 
7. The spell should send the vector of the block that was broken

**Comment by Kamefrede** [comment]
Doesn't seem to be an issue anymore in 1.15
