### ISSUE TITLE
Client Side Spell Charges

### ISSUE THREAD

**Issue by SnazzGass** [Vazkii/Psi#543]
Using the mine, charge, or grenade bullet will create server side spell charge entity and a client side spell charge entity.

![2019-12-09_20 14 03](https://user-images.githubusercontent.com/45057060/70494535-7cea6300-1ac0-11ea-8fe9-d03452152c26.png)

the client side spell charge disappears if you unload the chunk or relog.

This means that its much harder to conceal mine spell bullets and also it doubles the amount of particles you need to render.

**Comment by Kamefrede** [comment]
Fixed.
