### ISSUE TITLE
Spell Charges sticking to blocks

### ISSUE THREAD

**Issue by SnazzGass** [Vazkii/Psi#544]
I don't know if this is intentional behavior or not, but its inconsistent, so I assume it's a bug.

If you shoot a spell charge at the -x, -y, or -z side of a block, it will stick to the bottom of the block. 

![2019-12-09_20 24 44](https://user-images.githubusercontent.com/45057060/70494922-f6368580-1ac1-11ea-97ca-f0a97563cda8.png)

If you shoot a spell charge at the +x or +z side of a block, it falls down.

Additionally, it seems that if the charge is sticking to a block, the focal point is within that block

**Comment by Kamefrede** [comment]
Fixed in #571
