### ISSUE TITLE
[Request] Botania Mana Usage

### ISSUE THREAD

**Issue by drhaber** [Vazkii/Psi#545]
If and when PSI gets updated to the next MC version it would be cool if a config option existed so that PSI's Mana came from Botania and required a mana tablet/ring to be able to cast the various spells one creates.

**Comment by Kamefrede** [comment]
Unfortunately, this will not be present in the mod since we want to preserve as much backwards compatibility as possible with spells.
You can suggest this to Random PSIdeas or Psio.
