### ISSUE TITLE
The SpongeForge desync

### ISSUE THREAD

**Issue by Smolk14** [Vazkii/Psi#552]
If psi is run on a spongeforge server then cads will "dance" in your hand and the energy bar will not sync correctly between the server and client. Now im reporting it here because i tracked the orgin of the bug to this commit: https://github.com/Vazkii/Psi/commit/fbb49ceca536472bbf028eb7c41a1a331fdaf385

Versions before said commit work fine

also interestingly the strange behavior provides no trace in logs 

if needed i can provide further information on the subject just need to know what i should check

**Comment by ErenBlack** [comment]
+1 to this, good work finding the comment.

its a serious issue that makes psi _ALMOST_ unplayable, and is and issue within psi itself, not sponge. Ive never seen any other mod like this do it, so.


on a side note, any way to disable that "dancing" (bobbing?) animation in your hand to where it would be at least a LITTLE playable?

**Comment by Smolk14** [comment]
The "dancing" animation is i think a part of the item NBT changing and a vanilla or forge feature so unfortunatly i doubt it can be disabled. Still this is a gamebreaking bug and needs to be fixed. (Though PSI develompent seems to be focused on 1.15.2 for now so im starting to lose hope)

**Comment by RobinNightWing** [comment]
Any hope this will be fixed ?

**Comment by Kamefrede** [comment]
This can be solved by downgrading Psi to r1.1-70. 
If eventually spongeforge updates to 1.16/1.15 and this bug still persists I will try and look into it and if a fix is found I'll backport it to 1.12.
That being said, if anyone from the Sponge team wants to reach out, I'll gladly cooperate with them in order to find a fix.

**Comment by Smolk14** [comment]
I see, thanks for responding
Well i can try to talk to one of my  friends who sometimes codes mc mods maybe they can find a fix
If they where to find a way to fix it would it be ok for some kind of pull request or something like that?

**Comment by Kamefrede** [comment]
Sure thing!

**Comment by Tekkitmaster27** [comment]
Was the 1.12 patch done 4 days ago be related to this bug?

**Comment by Kamefrede** [comment]
No

**Comment by ShoukakuChuuCC** [comment]
> This can be solved by downgrading Psi to r1.1-70.
> If eventually spongeforge updates to 1.16/1.15 and this bug still persists I will try and look into it and if a fix is found I'll backport it to 1.12.
> That being said, if anyone from the Sponge team wants to reach out, I'll gladly cooperate with them in order to find a fix.

Hello, I downgraded psi to r1.1-70, but the problem still persists...
SpongeForge Version:1.12.2-2838-7.3.0
ForgeServer Version:1.12.2 - 14.23.5.2854
