### ISSUE TITLE
Big Ol' Bug Report

### ISSUE THREAD

**Issue by Feztacular** [Vazkii/Psi#553]
For the latest Psi Beta (1.15)
(This is my first time doing this so if I make a mistake sorry)

-The hovering display that's usually atop the Spell Programmer is missing
-Entering and then reentering the GUI for the Spell Programmer makes Target icons look abnormal (this is true for any of these icons for any spell piece as far as I can tell)
![image](https://user-images.githubusercontent.com/42902634/76972533-b838d100-68fc-11ea-8ad4-b04e8100e66a.png)
-Pressing ESC in a programmer doesn't work until you click in or outside the GUI
-Adding a Trick to a spell no longer names the spell after that trick, though this may be intentional
-The search region for spell pieces in the Spell Programmer isn't automatically selected, though this may be intentional
-All Spell Bullets descriptions (SHIFT) lack localization
![image](https://user-images.githubusercontent.com/42902634/76974261-fc2cd580-68fe-11ea-9e50-3b988a2e19b4.png)

-Using a Projectile Spell Bullet instantly crashes the game
-Using a Grenade Spell Bullet instantly crashes the game and seems to crash the game every subsequent time you try to load it
-Using a Charge Spell Bullet instantly crashes the game and seems to crash the game every subsequent time you try to load it
-Using a Mine Spell Bullet instantly crashes the game and seems to crash the game every subsequent time you try to load it
-Circle Spell Bullets lack the rendered circle when cast

**Comment by EvelynnRose** [comment]
this is op, I posted this on my friends account, and I dunno how to get rid of it, but if I respond it will be on this account

**Comment by Kamefrede** [comment]
Forgot to close, already fixed.
