### ISSUE TITLE
Black screen after aquiring the CAD

### ISSUE THREAD

**Issue by tabdelbari** [Vazkii/Psi#579]
The screen goes black without errors still can hear the player can move, and it remains the same even after restarting the game (creative mod).

**Comment by Kamefrede** [comment]
Log, Psi version, Forge version and what other mods are you using?

**Comment by tabdelbari** [comment]
I use TLauncher 2.69 with Minecraft Forge 1.15.2.
- Psi version : Psi r1.2-79
- other mods: [Bountiful_3.1.1, jei_6.0.0..4, Kottle_1.5.2, tl_skin_cape_forge_1.10, Xaeros_Minimap_20.11.0_Forge]
[debug.log](https://github.com/Vazkii/Psi/files/4629348/debug.log)
[latest.log](https://github.com/Vazkii/Psi/files/4629350/latest.log)

**Comment by Kamefrede** [comment]
In the psi-client.toml file in your configs folder set useShaders to false.
I think it might be a shaders issue.

**Comment by tabdelbari** [comment]
sorry but the problem still occurs even after setting _"Use Shaders" =false_ (in the psi.cfg file, I don't have psi-client.toml). 
are there any dependencies should I download OR try to remove?
Thanks.

**Comment by Kamefrede** [comment]
How do you not have a psi-client.toml file? Psi or any forge mod for that matter, does not use .cfg files on 1.15.2

**Comment by tabdelbari** [comment]
I installed the game from scratch and still have the problem.

**Comment by tabdelbari** [comment]
I can't find the psi-client file under config .minecraft/config folder.
once I get the CAD in inventory the screen goes black, and apparently there are no exceptions in the logs.

**Comment by BlueAgent** [comment]
Had a similar problem with the configs (both common and client) not being generated for some reason. Fixed in https://github.com/Vazkii/Psi/pull/593 so once that change is released you can try disabling shaders.

**Comment by tabdelbari** [comment]
THANK you all, I tried the last release and I managed to find the psi-client.toml file, the following change:
useShaders = false
and it WORKS!
