### ISSUE TITLE
Trick: Place Block not working with Block Broken in Tools. Beta-14

### ISSUE THREAD

**Issue by Wojbie** [Vazkii/Psi#58]
I have stumbled on this one when playing with casting tools.
I attempted to recreate the replacing tools from other mods by placing block when block was broken.
I have run into situation where even when provided with correct vector from break block  the place block will not place block. Screenshot of spell and code for it below. IF provided with vector from different source the place works normally taking block from right of the tool.

![Image of Spell](http://i.imgur.com/Al5Swnp.png)

{spellName:"Replacee",uuidMost:4892725656397105230L,validSpell:1b,spellList:[0:{spellPosX:3,spellData:{spellKey:"selectorBlockBroken",params:{}},spellPosY:3},1:{spellPosX:3,spellData:{spellKey:"selectorBlockBroken",params:{}},spellPosY:4},2:{spellPosX:4,spellData:{spellKey:"trickDebug",params:{psi.spellparam.number:0,psi.spellparam.target:3}},spellPosY:3},3:{spellPosX:4,spellData:{spellKey:"trickPlaceBlock",params:{psi.spellparam.position:3}},spellPosY:4}],uuidLeast:-6067502198600022787L}

**Comment by Vazkii** [comment]
The tools' cast happens before the block is removed from the world, so you won't have space there to put it. Next release you will be able to do it by using a delay.
