### ISSUE TITLE
1.15.2 - Psi causing Neat healthbars to be at mob's feet

### ISSUE THREAD

**Issue by Partonetrain** [Vazkii/Psi#581]
Psi r1.2-79
Neat 1.6-21

![image](https://user-images.githubusercontent.com/19861808/81976326-fe08d180-95ed-11ea-932b-e69b1898d636.png)

No idea how or why this is happening. Tested with only Forge + Neat, works fine, adding Psi causes this.

**Comment by williewillus** [comment]
it's probably a matrixstack leaking somewhere

**Comment by Partonetrain** [comment]
Indeed, this is a Neat issue.
https://github.com/Vazkii/Neat/issues/52
