### ISSUE TITLE
1.15.2 - Circle spells not working

### ISSUE THREAD

**Issue by BlazingV** [Vazkii/Psi#582]
I was using Psi in 1.15.2 with other mods and I wanted to make a circle bullet spell that smelted ores. I cast it but it was really cheap for a circle spell and it did nothing. I used different spells but to no avail. The same spells worked in a normal spell bullet.

For testing, I only had Psi (+AutoRegLib and Patchouli) on and tested this in a fresh world, but the circle spells still didn't work.

Versions
Forge: 31.1.88
Psi: r1.2-79
AutoRegLib: 1.5-40
Patchouli: 1.2-33

Smelting spell:
Image https://imgur.com/dbCy1x7
Code https://pastebin.com/bzZBz1Gy

**Comment by Alwinfy** [comment]
…did you actually load it into a Circle Spell Bullet and cast it from that?

**Comment by BlazingV** [comment]
> 
> 
> …did you actually load it into a Circle Spell Bullet and cast it from that?

Yes.

**Comment by Dudblockman** [comment]
This applies to all spell bullet types aside from basic spell bullets. This seems to have surfaced after #577. Spell bullets do not return true when castableFromSocket() is called.
