### ISSUE TITLE
Operator: Add To List's optional list does not work

### ISSUE THREAD

**Issue by chilfang** [Vazkii/Psi#588]
Using PSI version r1.2-80, Patchouli and nothing else

[Caster + Add to list](https://imgur.com/XgtPL3V)
[Focused Entity + Add to list](https://imgur.com/oJcNE0h)

The C+AL doesn't even seem to fire whether it's loopcast or normal bullet (It does fire when a list is given)
The FE+AL appears to crash whenever it's used (successfully) unless it's given a list 

[Here is a crash report from using it on a boat](https://github.com/Vazkii/Psi/files/4646457/crash-2020-05-18_12.55.54-server.txt)
[Here is a crash report from using it on a zombie](https://github.com/Vazkii/Psi/files/4646462/crash-2020-05-18_13.00.10-server.txt)

**Comment by Alwinfy** [comment]
My bad; didn't patch this logic when I overhauled EntityListWrapper. Fix incoming
