### ISSUE TITLE
1.15.2 Trick:Overgrow destroys CAD in SP

### ISSUE THREAD

**Issue by Robertdebrus** [Vazkii/Psi#590]
Using the Overgrow trick linked in Singleplayer destroys the CAD 
https://imgur.com/ztGg2qL
Steps to reproduce (Using Psi r1.2.83 and Patchouli-1.15.2-1.2-33 on forge-31.2.1) 
1. Use any CAD 
2. Use spell on a plant (Tested with wheat) 
3 Watch as your CAD and everything on it vanishes

**Comment by Robertdebrus** [comment]
Tested Circle, Loopcast, and Projectile bullets destroyed the CAD even in creative

**Comment by Kamefrede** [comment]
Psi currently does not play well with forge versions above 31.2.0

**Comment by Robertdebrus** [comment]
Everything else I've tried works well

**Comment by Kamefrede** [comment]
The majority of the broken stuff is in multiplayer right now
I'm looking into it right now

**Comment by Robertdebrus** [comment]
Ah, okay, I didn't try it much in multiplayer before I found the bug. Is it something where I shouldn't use it in MP, or it just doesn't work?

**Comment by Kamefrede** [comment]
It just doesn't work in general, it _probably_ won't crash your game.

**Comment by Robertdebrus** [comment]
Okay

**Comment by Kamefrede** [comment]
Fixed in 4373b69

**Comment by Gayanfalor** [comment]
> Fixed in [4373b69](https://github.com/Vazkii/Psi/commit/4373b693bff2eaa1f5aa5e1dbd14f320c47d00a1)

hi so its fixed in 2.82?  Thanks i looked in closed thread as i was going to open new one i'm sad i lost my psigun too with all my bullets. i play  ATM 5

**Comment by Kamefrede** [comment]
Yes it's fixed in version 82
