### ISSUE TITLE
1.15.2 Rendering Bug: Projectiles and other particles don't show

### ISSUE THREAD

**Issue by brianSites** [Vazkii/Psi#595]
I am playing in the 1.15 version and have not changed any settings with the exception of sounds. I have found that the particles from firing projectile bullets and conjured lights don't appear on the screen. I found that they always happen after I gave myself night vision using a spell.

Update: I realized that this isn't about me giving myself night vision. In fact, I have found it always happens after 20 minutes of playing.

**Comment by Kamefrede** [comment]
Should be fixed in the latest release
