### ISSUE TITLE
Closest to Point Ruins Everything

### ISSUE THREAD

**Issue by SpitefulFox** [Vazkii/Psi#60]
Fired spell.  Things borked.

http://pastebin.com/L2vxnjtf

CAD was shift-casted while I was looking at a fence, if that helps?

Projectile spell grabs closest to Focus location and throws them.

**Comment by Turmfalke2** [comment]
does not appear to happen everytime, but it is still pretty frequent.

**Comment by SpitefulFox** [comment]
The spell I used:

{spellName:"Pin to the Sky",uuidMost:-9164004733095490837L,validSpell:1b,spellList:[0:{spellPosX:0,spellData:{spellKey:"constantNumber",params:{},constantValue:"0"},spellPosY:5},1:{spellPosX:1,spellData:{spellKey:"constantNumber",params:{},constantValue:"1"},spellPosY:4},2:{spellPosX:1,spellData:{spellKey:"operatorSum",params:{psi.spellparam.number2:3,psi.spellparam.number3:0,psi.spellparam.number1:1}},spellPosY:5},3:{spellPosX:2,spellData:{spellKey:"constantNumber",params:{},constantValue:"0"},spellPosY:4},4:{spellPosX:2,spellData:{spellKey:"operatorVectorConstruct",params:{psi.spellparam.z:2,psi.spellparam.y:3,psi.spellparam.x:1}},spellPosY:5},5:{spellPosX:2,spellData:{spellKey:"constantNumber",params:{},constantValue:"0"},spellPosY:6},6:{spellPosX:3,spellData:{spellKey:"selectorFocalPoint",params:{}},spellPosY:2},7:{spellPosX:3,spellData:{spellKey:"operatorEntityPosition",params:{psi.spellparam.target:1}},spellPosY:3},8:{spellPosX:3,spellData:{spellKey:"operatorClosestToPoint",params:{psi.spellparam.position:1,psi.spellparam.target:4}},spellPosY:4},9:{spellPosX:3,spellData:{spellKey:"trickAddMotion",params:{psi.spellparam.direction:3,psi.spellparam.speed:2,psi.spellparam.target:1}},spellPosY:5},10:{spellPosX:3,spellData:{spellKey:"constantNumber",params:{},constantValue:"10"},spellPosY:6},11:{spellPosX:4,spellData:{spellKey:"connector",params:{psi.spellparam.target:3}},spellPosY:3},12:{spellPosX:4,spellData:{spellKey:"selectorNearbyLiving",params:{psi.spellparam.radius:4,psi.spellparam.position:1}},spellPosY:4},13:{spellPosX:5,spellData:{spellKey:"constantNumber",params:{},constantValue:"2"},spellPosY:4},14:{spellPosX:6,spellData:{spellKey:"errorSuppressor",params:{}},spellPosY:1}],uuidLeast:-7682834057365545674L}
