### ISSUE TITLE
Tutorial translation problem

### ISSUE THREAD

**Issue by VitoDeng** [Vazkii/Psi#603]
I am using simplified Chinese language, translations of all items are displayed normally. But all the text in the tutorial book is displayed in English

**Comment by Kamefrede** [comment]
The only language available right now for the tutorials is English.

**Comment by VitoDeng** [comment]
> 目前，教程中唯一可用的语言是英语。
Thanks for telling me, I thought it was a problem with my computer. Hope there will be more language available in the future XD

**Comment by VitoDeng** [comment]
> The only language available right now for the tutorials is English.

Thanks for telling me, I thought it was a problem with my computer. Hope there will be more language available in the future XD
