### ISSUE TITLE
Eidos Changelog weird maximum

### ISSUE THREAD

**Issue by Math321** [Vazkii/Psi#613]
Eidos Changelog errors if you input a value higher than 599. Combined with issue #612 , this means that 598 different positions are readable. Once #612 is fixed, can this be changed to 601 different positions, from 0 to 600?

**Comment by Kamefrede** [comment]
fixed, now you get the intended 600 different positions( 0(inclusive) to 600(exclusive), doesn't make sense for it to be 601
