### ISSUE TITLE
Constant: Number pieces appear blank when viewed from behind.

### ISSUE THREAD

**Issue by Math321** [Vazkii/Psi#614]
Constant: Number pieces appear blank when viewed from the back side of the Spell Programmer's in-world render. They appear to be the only pieces which act this way.

Front example: https://prnt.sc/ttymss
Back example: https://prnt.sc/ttymk3

**Comment by Kamefrede** [comment]
This a byproduct of the number piece not being a static texture but rather a blank texture with the number drawn on top.
