### ISSUE TITLE
Font rendering in Encyclopedia Pisonica illegible at certain GUI scales

### ISSUE THREAD

**Issue by tehbeard** [Vazkii/Psi#616]
Running: r1.2-82

At GUI Scale: 3 in the video options menu, text becomes difficult to read, due to the varying widths on the strokes of the font.
It seems to render fine, (although to small at 2, and the rest of the GUI is too large at 4) at other GUI scale levels.

This is on a 1920x1080 display.

![2020-08-05_18 39 20](https://user-images.githubusercontent.com/734177/89446049-e56f0a00-d74b-11ea-9ae9-1e1c2b770062.png)

**Comment by Alwinfy** [comment]
Issue with [Patchouli](https://github.com/Vazkii/Patchouli/); you can try reporting upstream but it's not a very easy fix

**Comment by tehbeard** [comment]
@Alwinfy Missed a GUI scale option in the book on the start page that is independent of the rest of the GUI. Closing ticket as this resolves the issue for me.
