### ISSUE TITLE
Trick: Place Block will not place certain blocks

### ISSUE THREAD

**Issue by SnazzGass** [Vazkii/Psi#621]
Saw [ this reddit post](https://www.reddit.com/r/psispellcompendium/comments/ic3ywb/place_block_doesnt_place_carved_pumpkin/) and I decided to see if any other blocks can't be placed with trick: place block. I found a bunch.

![thing](https://user-images.githubusercontent.com/45057060/90586294-b1540a00-e18b-11ea-9325-40a0920d4608.png)

I didn't have room for all the variants, so I only included one of each type of block. also I may have missed some blocks

**Comment by SnazzGass** [comment]
Additionally, it seems If you try to place these blocks after a some delay using trick: sleep, the game crashes.

![image](https://user-images.githubusercontent.com/45057060/90587357-085ade80-e18e-11ea-9dc5-b741cf26cc58.png)

**Comment by Kamefrede** [comment]
fixed
