### ISSUE TITLE
Psimetal Bow Crashes game and corrupts the world file

### ISSUE THREAD

**Issue by TGMouse** [Vazkii/Psi#624]
I recently noticed that when I try to use the Psimetal Bow in Creative, as I attempt to put it in my inventory my client crashes. I then attempt to reload the save file and the files are corrupt. I've attached the crash report.
[crash-2020-09-02_20.38.01-server.txt](https://github.com/Vazkii/Psi/files/5165946/crash-2020-09-02_20.38.01-server.txt)

**Comment by Kamefrede** [comment]
https://github.com/Dudblockman/Psipherals
Wrong place to post the issue.

**Comment by TGMouse** [comment]
I didn't realize it was Psipherals that added that. thanks!
