### ISSUE TITLE
crash to desktop when using the "upload to imgur" shortcut (1.12)

### ISSUE THREAD

**Issue by supremedutchgamer** [Vazkii/Psi#625]
[crash-2020-09-27_02.50.39-client.txt](https://github.com/Vazkii/Psi/files/5287567/crash-2020-09-27_02.50.39-client.txt)

whenever i attempt to use ctrl+shift+alt+g to export a spell to imgur, the game crashes out completely. running the following on 1.12:

forge 14.23.5.2854
psi r1.1 78.1
rpsideas 2.4.2
psionic peripherals 1.1.0
shadowfacts' forgelin 1.8.4
librarianlib 4.21
autoreglib 1.3-32

**Comment by Kamefrede** [comment]
Not a bug.
Update your java.

**Comment by supremedutchgamer** [comment]
java updated to 1.8.0 261-b12, issue persists.
