### ISSUE TITLE
crash to desktop with imgur function (1.12)

### ISSUE THREAD

**Issue by supremedutchgamer** [Vazkii/Psi#626]
[crash-2020-09-30_04.24.05-client.txt](https://github.com/Vazkii/Psi/files/5302916/crash-2020-09-30_04.24.05-client.txt)

updated copy of #625 

used the suggested fix (updating java), which did not work. issue persists with java 1.8.0 ver 261, also tried openJDK to no avail.

updated all mods to the newest version available on curseforge (via twitch), used the JVM argument `-version:1.8+` to get minecraft to use my computer's main java version instead of the one bundled with twitch. and looked around online for potential fixes.

**Comment by Kamefrede** [comment]
fixed
