### ISSUE TITLE
Ivory infusion crash

### ISSUE THREAD

**Issue by davethwave** [Vazkii/Psi#628]
I'm not sure if it's due to a bad mod interaction or of the mod itself but when I tried to infuse some ivory for the first time in the end the server crashed for atm6. Even as I make this report it seems like the server is stuck in some kind of crash loop.

PSI 1.16.3-85

**Comment by davethwave** [comment]
Seems like it was something related to woot, tested infusion singleplayer and it didn't crash anything.

**Comment by davethwave** [comment]
I take it back, tried doing it again and it indeed did crash the server.

**Comment by Kamefrede** [comment]
fixed in build 86
