### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Wolfven** [Vazkii/Psi#630]
# Version Information
Forge version: 34.1.24
Psi version: 1.16-86

# Further Information
Link to crash log: https://gist.github.com/Wolfven/5551b1465b9d30e927e37225c37dad3d
Steps to reproduce:
1. Place Spell Programer
2. Open it

What I expected to happen: Open Spell Programmer

What happened instead: Client Crash to Desktop

**Comment by Kamefrede** [comment]
fixed in release 87
