### ISSUE TITLE
Broken usage of ObfuscationReflectionHelper

### ISSUE THREAD

**Issue by malte0811** [Vazkii/Psi#631]
https://github.com/Vazkii/Psi/blob/14b3a866ffca67dcfac02fcde73cc764d38590e2/src/main/java/vazkii/psi/client/core/proxy/ClientProxy.java#L98
`ObfuscationReflectionHelper#getPrivateValue` needs the [unmapped/SRG name](https://github.com/MinecraftForge/MinecraftForge/blob/74f9ef838a53acb1e7d3d09622b604d96cf02221/src/main/java/net/minecraftforge/fml/common/ObfuscationReflectionHelper.java#L75), not the mapped name. Noticed the error in the client log on ForgeCraft 1.

**Comment by Kamefrede** [comment]
I'm surprised it only blew up now, a temporary fix has been released, but a move to mixin is probably happening
