### ISSUE TITLE
Right-clicking any item with a right-click function (such as the Ars Nouveau spellbook) halts psi regen.

### ISSUE THREAD

**Issue by dmtRoyal** [Vazkii/Psi#632]
# Version Information
Forge version:  34.1.25
Psi version:  1.16-87

# Further Information
Link to crash log: N/A
Steps to reproduce:
1.  Cast mad tech wizard spells
2.  Use a firework rocket/spellbook/funny rat mod poop ore nuggie
3.  Suffer

What I expected to happen:
- Psi should regen as normal

What happened instead:
- yaint

**Comment by Kamefrede** [comment]
Can't replicate in dev
