### ISSUE TITLE
Crash on opening programmer

### ISSUE THREAD

**Issue by krazykatboy** [Vazkii/Psi#633]
Game crashed after I attempted to open the spell programmer.

Context:

- This was the first ever attempt in the game to open it. 
- Multiple spell programmers were placed while in creative mode, but was accessing it in survival mode.
- CAD was in hotbar but was not currently held item.
- GUI scale was at 3, force unicode on.
- Crash report attached.

[crash-2020-10-24_08.39.26-client.txt](https://github.com/Vazkii/Psi/files/5432891/crash-2020-10-24_08.39.26-client.txt)

**Comment by Kamefrede** [comment]
Update psi.
