### ISSUE TITLE
Enhancement Request: Recipe to wipe spell drive

### ISSUE THREAD

**Issue by TotalHamman** [Vazkii/Psi#64]
Enhancement Request: Recipe to wipe spell drive.  

Possible ideas:
Place in crafting grid to wipe
Craft with Psi Dust to wipe

**Comment by PsiGuy60** [comment]
I think there is already a way to wipe them by shift-right clicking them.

However, I do want to weigh in and say a similar thing for Spell Bullets would be nice.

**Comment by yrsegal** [comment]
Placing in crafting grid makes no sense, as they have a container item. That'll be a dupe no matter what.

**Comment by TotalHamman** [comment]
I was unaware of the shift-click on anything other block to wipe.  Sorry for the unnecessary suggestion.
