### ISSUE TITLE
[Bug] Right-clicking on redstone with a CAD does not cast the selected bullet

### ISSUE THREAD

**Issue by qrss** [Vazkii/Psi#640]
# Version Information
Forge version: forge-34.1.35
Psi version: 1.16-87

Right-clicking on redstone with a CAD selected (for example with a mining spell) just does the action that makes redstone emit particles. The spell is not cast. This makes mining using Psi a bit annoying.

In 1.12 the spell would have activated as expected.

**Comment by qrss** [comment]
I noticed that Shift + right-click works.

**Comment by Kamefrede** [comment]
Wont fix. Changing this behaviour would imply that you can accidentally grief yourself if you right click a container with a CAD in hand.

**Comment by qrss** [comment]
Well, I reported this, because in 1.12 the behavior was different.

I guess something must have changed internally. Perhaps this is a forge bug.

**Comment by qrss** [comment]
All right, I tested Vanilla 1.12 behavior against Vanilla 1.16 behavior in right-clicking redstone with a flint and steel.

In 1.12 the flint and steel started a fire.
In 1.16 it did not.

So this is indeed a Vanilla change. Sorry about the report.

**Comment by qrss** [comment]
This seems to be a bug in Vanilla.

https://bugs.mojang.com/browse/MC-189029
