### ISSUE TITLE
CAD casting (right click) animated incorrectly (plays use animation)

### ISSUE THREAD

**Issue by sleepyKitsune** [Vazkii/Psi#645]
# Version Information
Forge version: 34.1.42
Psi version: Psi 1.16-88

Was able to reproduce in a fresh instance with just Psi & AutoReglib.

**What I expected to happen:**
 Cad have minor recoil but stay upright.
**What happened instead:**
Turn forward & face down then pull back up.

**Comment by Kamefrede** [comment]
Forgot to close this but has been fixed.
