### ISSUE TITLE
Trick: Place Block does not update inventory slot when used

### ISSUE THREAD

**Issue by Tinster101** [Vazkii/Psi#65]
When using [this](http://i.imgur.com/mH5JibT.png?1) spell, the inventory slot that contains the blocks being placed does not update, as shown by [this](http://imgur.com/a/v2riH) gallery.  
The slot only updates when clicked on in the inventory or when you try to place the block.

**Comment by PsiGuy60** [comment]
Didn't Vazkii already post a commit to fix this?
