### ISSUE TITLE
[1.16.4] PSI + Apotheosis caused "Mod loading error has occurred" on server, maybe client too?

### ISSUE THREAD

**Issue by Gbergz** [Vazkii/Psi#652]
# Version Information
Forge version: 35.1.28
Psi version: 1.16-88
Apotheosis version: 4.4.1

# Further Information
Link to crash log: https://hatebin.com/arygcnnoph
Steps to reproduce:
1. Start server w/ Apotheosis & Psi
2. Wait.
3. "Server crashes." (Mod loading error has occurred)"
(Note that this only happens like 40-50% of the time. Sometimes it starts up just fine.)

**What I expected to happen:**
Server boots up fine 100% of the time.

**What happened instead:**
Server sometimes crashes when starting up.

# Additional Info:
This issue was reported on the Apotheosis github, but the cause is supposedly this mod.
Looking at the stacktrace:
```at vazkii.psi.api.material.PsimetalToolMaterial.func_200924_f(PsimetalToolMaterial.java:44) ~[psi:1.16-88] {re:classloading}```

**This issue:** https://github.com/Shadows-of-Fire/Apotheosis/issues/290

**Comment by Kamefrede** [comment]
it's already fixed, the build containing the fix just hasn't been uploaded yet
it do it later today

**Comment by Gbergz** [comment]
Thats great news! Thanks.

**Comment by Kamefrede** [comment]
https://www.curseforge.com/minecraft/mc-mods/psi/files/3160313
