### ISSUE TITLE
Importing old spells (while using addons) leds to a malformed string with null-pointer exception

### ISSUE THREAD

**Issue by jaquobia** [Vazkii/Psi#656]
# Version Information
Forge version: 1.16.4-35.1.37
Psi version: 1.16-90

# Further Information
Steps to reproduce:
Attempt to import an old spell, one I tried using: https://imgur.com/Cz1x0Xe

What I expected to happen:
-imports the spell

What happened instead:
![image](https://user-images.githubusercontent.com/16600393/104996846-987ba900-59f6-11eb-9b0d-e786dfcc483e.png)

**Comment by ATH1909** [comment]
Correct me if I'm wrong, but aren't the Elytra-related tricks exclusive to the Psideas addon?
https://github.com/Kamefrede/rpsideas/wiki/Spell-Pieces

**Comment by jaquobia** [comment]
You are right, but psi is okay with that, and just imports what it can. But more information has been found that including add-ons (specifically psionic-peripherals) actually causes imports to break, which is something behem07h discovered. However, its only been tested with psionic peripherals, so I'm not sure if all add-ons causes this or only this mod.

**Comment by ATH1909** [comment]
> You are right, but psi is okay with that, and just imports what it can. But more information has been found that including add-ons (specifically psionic-peripherals) actually causes imports to break, which is something behem07h discovered. However, its only been tested with psionic peripherals, so I'm not sure if all add-ons causes this or only this mod.

You might want to edit the title of this issue report to more accurately reflect the actual problem here, then.

**Comment by Hubry** [comment]
Can you use [this build](https://ci.blamejared.com/view/Vazkii/job/Psi/job/master/lastSuccessfulBuild/artifact/build/libs/Psi%201.16-89.320.jar) and post the stack trace that appears in the log after import?

**Comment by jaquobia** [comment]
This is the exception that appears in the log
https://pastebin.com/JUgP6hRj

**Comment by Kamefrede** [comment]
fixed in version 91
