### ISSUE TITLE
Error catcher always returns null

### ISSUE THREAD

**Issue by TechEpic** [Vazkii/Psi#657]
# Version Information
Forge version: 35.1.37
Psi version: CurseForge reports 1.16.4-90, uploading a spell reports 1.16.4-88

# Further Information
Link to crash log: N/A
Steps to reproduce:
1. Open a spell programmer
2. Use this spell: https://imgur.com/ISff3Fk (or similar)
3. Try to use the spell, see the null. I used an ivory CAD, if it makes a difference.

What I expected to happen:
The number '1' to be outputted.

What happened instead:
The value 'null' was outputted.

**Comment by TechEpic** [comment]
Still haven't figured out how to use it, but it's clearly not meant to output anything, so the logical conclusion is that I am dumb.

**Comment by gdavid04** [comment]
The error catcher replaces the output of the target piece on error, the error catcher itself has no output.
Also there's a bug which can cause error catcher to replace the output value with null before Psi 1.16-94.

**Comment by Kamefrede** [comment]
Please refrain from necroing issues, thanks.
