### ISSUE TITLE
Add a way to clear the spell in the programmer?

### ISSUE THREAD

**Issue by ewanm89** [Vazkii/Psi#66]
Basically it would be good to have a way to clear the grid. From what I can tell, currently one has to delete everything manually (total PITA on a more complex spell) or break and replace the programmer block itself.

**Comment by Vazkii** [comment]
Ctrl-shift-del

**Comment by ewanm89** [comment]
Nice, that should probably be mentioned in the one of the first 3 tutorials then.

**Comment by kusiak** [comment]
That hotkey doesn't work for me on a mac, can anyone confirm that I'm not just a dummy and it doesn't really work on mac?

**Comment by yrsegal** [comment]
Works for me on Mac.

**Comment by Vazkii** [comment]
On mac it'd be Cmd-Shift-Del.

**Comment by kusiak** [comment]
Confirmed works, Del on mac is fn+backspace, thanks

**Comment by yrsegal** [comment]
it also does it with delete in new versions iirc.
