### ISSUE TITLE
Unable to load Bullet into cad from tutorial

### ISSUE THREAD

**Issue by NinjaDanny87** [Vazkii/Psi#660]
# Version Information
Forge version: **35.1.37**
Psi version: **1.16-91**

# Further Information
Steps to reproduce:
1. Create CAD Assembler 
2. Create CAD
3. Create "Debug" Bullet
4. Load CAD into Assembler
5. _TRY_ to load "Debug" into CAD = **FAIL**

What I expected to happen:
The leftmost boxes below the CAD slot _should open_, and I should be able to place a bullet inside one of the available slots.

What happened instead:
The leftmost boxes below the CAD slot **DO NOT** open up when placing a CAD inside that slot.

# Other Notes
Further testing in creative mode yields the same results. Unable to continue playing with mod due to issues loading bullets.

**Comment by Kamefrede** [comment]
Did you make a cad with a socket?
