### ISSUE TITLE
[Feature Request] leveling up-ish

### ISSUE THREAD

**Issue by blackwing12344** [Vazkii/Psi#662]
Now that you got rid of the leveling system, can you make some other way to increase psi storage and regen?

**Comment by Hubry** [comment]
Leveling wasn't tied to maximum psi storage for about 2 years - release 1.1-60 (Nov 2018) made everyone start with 5000.

**Comment by blackwing12344** [comment]
Ok,  fair enough, but still. Is it possible for you to add something to increase psi storage and energy?

**Comment by Kamefrede** [comment]
It's possible for add-ons to increase the maximum psi amount and psi regeneration  (Psio does the latter). There are no plans at this moment to add this to the base mod.
