### ISSUE TITLE
Client crash on try to put a Spell Driver into CAD Assembler

### ISSUE THREAD

**Issue by frank89722** [Vazkii/Psi#666]
# Version Information
Forge version: 36.0.15
Psi version: 1.16-91

# Further Information
Link to crash log: https://gist.github.com/frank89722/8f1c2e2126a2297ae91a8883f7fdf232
1. Put a Casting Assistant Device in a CAD Assembler
2. Put the Spell Drive in like the screenshot below
3. Client crash

![image](https://user-images.githubusercontent.com/10683361/107769962-ae6d5700-6d73-11eb-9382-b0db4b4c0587.png)

**Comment by alpharou** [comment]
can confirm,

forge 36.0.46
psi 1.16-91

crash when you try to insert any item in that slots

**Comment by Nydid** [comment]
> 
> 
> can confirm,
> 
> forge 36.0.46
> psi 1.16-91
> 
> crash when you try to insert any item in that slots

Can confirm as well
