### ISSUE TITLE
Crash with Psi circle spell bullet

### ISSUE THREAD

**Issue by TheGreatCatAdorer** [Vazkii/Psi#667]
# Version Information
Forge version: 36.0.1
Psi version: 1.16-91

I created a circle spell to throw enemies 60 blocks into the air on an Ebony CAD.  When the spell was cast, the game crashed without a crashlog.

[latest.log](https://github.com/Vazkii/Psi/files/6030971/latest.log)

**Comment by TheGreatCatAdorer** [comment]
It failed only when next to a Create moving contraption.

**Comment by TheGreatCatAdorer** [comment]
Did it again with a different spell.

**Comment by TheGreatCatAdorer** [comment]
Only Circle spells cast within a Create Contraption crash the game.

**Comment by Auxority** [comment]
Can confirm this bug.

**Comment by DestroyerMCE** [comment]
It is likely caused by the spell trying to move the contraption. the contraption doesn't like this, so it kills the game

**Comment by Auxority** [comment]
> It is likely caused by the spell trying to move the contraption. the contraption doesn't like this, so it kills the game
The spell I used was a smelting spell though, it just looks for nearby smeltables.
It is still weird that this causes such behaviour.

**Comment by Kamefrede** [comment]
I don't see anything in the log posted by the OP, could someone who experienced this bug post a log for both server and client?

**Comment by gjerm** [comment]
I experience this bug specifically with any circle spell within a Create contraption. Sadly no client log but server log in this issue:

https://github.com/Creators-of-Create/Create/issues/1018

**Comment by archonxgames** [comment]
Can confirm this issue still persists, I have a server that is currently experiencing this problem. I can send server log files if you guys need.

**Comment by Ouroel** [comment]
Steps to replicate:

1). press F3 + B
2). make any create contraption
3). while inside, type /summon psi:spell_circle

**Comment by Ouroel** [comment]
Fixed as of latest version

Closed
