### ISSUE TITLE
Leveling crashes me

### ISSUE THREAD

**Issue by Direcub10** [Vazkii/Psi#67]
I just started the mod for the first time with no prior knowledge other than seeing DW20 struggle with hos vectors in his vids. The mod looked cool so i found a 1.8.9 pack on curse with it and started playing with it. After i gained my first level i crashed so i thought it was something with making psidust. after restarting MC i got to level 2 and crashed agian. My only explanation is that leveling is crashing me. Idk y or what im doing wrong so i need help. I really enjoy the mod and hope this can be fixed so i can get back to it,
Finally heres the crashlog http://pastebin.com/jibetdUq

**Comment by yrsegal** [comment]
what is your level key bound to?

**Comment by Direcub10** [comment]
Button 4 on my mouse right behind scroll wheel

**Comment by Vazkii** [comment]
Already fixed with 15, just change it to a keyboard key for now.
