### ISSUE TITLE
Bug with Die Trick and Debug trick

### ISSUE THREAD

**Issue by MindCaged** [Vazkii/Psi#671]
Running:
Minecraft 1.16.4
Psi 1.16-91

I'm trying to fix an old spell that's now broken since Sequence Tricks now treat a 0 length vector as a 1 length vector(I've actually found multiple spells this new behavior breaks). And I was trying to use Debug trick to figure out why it's not working, but it seems like if there's a Die trick triggered anywhere in the spell it also suppresses any debug output, even if the debug trick occurs above and to the left of the die trick.

Edit: Hmm, it might be a problem with the Gamma function, maybe I am misunderstanding Gamma, but from the tooltip I thought it subtracted 1 from the input, so I tried to do Sneak Status > Gamma > Die, and it doesn't seem to work.

**Comment by ElNico56** [comment]
Gamma does (x-1)! Not (x-1), ! Is an actual mathematical function, factorial

**Comment by MindCaged** [comment]
Ah, I didn't see that part. I wasn't familiar with the function. I only saw the X-1 in the tooltip. I do kinda wonder what gamma is used for.
