### ISSUE TITLE
Psi conjuration causes OpenGL errors

### ISSUE THREAD

**Issue by DestroyerMCE** [Vazkii/Psi#674]
I am using Psi 1.16.5 91 and Optifine 1.16.5 HD U G7, as I cant run modern modded without it.
How to reproduce:
1. Conjure a block or light
2. witness water disappear
will try with older optifine versions

**Comment by Kamefrede** [comment]
Unfortunately, as Optifine is a closed-source mod there's really not much I can do to fix this issue(since I don't know what Optifine is doing and how to work around it). 
Please open an issue in the Optifine issue tracker instead, it more easily be fixed on their side.
