### ISSUE TITLE
Crash to desktop when attaching sensor to armor.

### ISSUE THREAD

**Issue by bluffparktroop21** [Vazkii/Psi#684]
# Version Information
Forge version: forge-1.16.5-36.0.35-client.jar
Psi version: Psi 1.16-91.jar 

# Further Information
Link to crash log: https://pastebin.com/72Wp194d
Steps to reproduce:
1. Place any Psi armor in the CAD assembler
2. Attempt to put a sensor in the slot

What I expected to happen: The sensor to attach to the item and the game to stay live.

What happened instead: Game crashes to desktop.

**Comment by Kamefrede** [comment]
Update to Psi 92.
Also, you don't attach a sensor via the CAD assembler, it's a crafting table recipe.
