### ISSUE TITLE
Psi+1.16-92 did you intent to add the +

### ISSUE THREAD

**Issue by IamStig** [Vazkii/Psi#688]
There is no known "bug" but the version name seems odd, just an fyi

# Version Information
Forge version:unimportant
Psi version: Psi+1.16-92

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. First step
2. Second step
3. etc...

What I expected to happen:

What happened instead:

**Comment by BlueAgent** [comment]
Might be Curseforge replacing spaces with `+`.

**Comment by Kamefrede** [comment]
It's a curseforge thing
