### ISSUE TITLE
Vector Rotate is misaligned(?)

### ISSUE THREAD

**Issue by blaynemm** [Vazkii/Psi#691]
# Version Information
Forge version: 36.1.4
Psi version: 1.16-92

# Further Information
Steps to reproduce:
Trick: Debug at the rotation of the axial look of caster by 360* along the y-axis

I expected Trick: Debug at both the axial look and the rotation to be the same

What happened instead:
Debug printed [0, 0, 1] targeting axial
Debug printed [0.95892, 0, -0.28369] targeting the rotation.

At least I do hope this is a bug and not just me failing to understand vector rotations

**Comment by Dudblockman** [comment]
Angles are done in radians, these values are consistent with using 360 degrees instead of 2pi radians.

**Comment by blaynemm** [comment]
> Angles are done in radians, these values are consistent with using 360 degrees instead of 2pi radians.

I really oughtta have paid more attention when studying radians in highs school.
