### ISSUE TITLE
Psi Spin Chamber trick does not work on armor

### ISSUE THREAD

**Issue by DeFazer** [Vazkii/Psi#695]
If the Spin Chamber trick is included in a spell bullet in a piece of psimetal armor, trying to invoke it throws an exception rather than switches spellbullets within the armor. I don't believe that's the intended effect.
The exception goes like so: 
"**psi.spellerror.cad_casting.only
Error Position: [5, 7].**".

# Version Information
Forge version: 36.1.0
Psi version: 1.16-92

# Further Information
Steps to reproduce:
1. Put two spell bullets in a piece of armor
2. Assign a spell to one of the bullets that includes the Spin Chamber trick.
3. Invoke the spell (exact method depends on the piece) and watch the exception happen.

What I expected to happen:
Once the spell is executed, the piece of armor selects the other bullet, as per Spin Chamber trick.

What happened instead:
It threw an exception on me! How rude.

**Comment by Kamefrede** [comment]
This is intended behavior.

**Comment by DeFazer** [comment]
...oh. Sorry, my bad. 
_Why_ is it the intended behavior, then, if I may ask? This limitation feels quite artificial and is very surprising.

**Comment by Kamefrede** [comment]
Honestly, no idea. At this point I don't even remember.
Keeping this open so I can change it

**Comment by gdavid04** [comment]
It works in 1.16-94

**Comment by DeFazer** [comment]
(Feel free to close it now, by the way! The issue has been resolved in the new version. And thanks again for keeping an eye on this! :3)
