### ISSUE TITLE
Entity Position of Players are Inconsistent

### ISSUE THREAD

**Issue by blaynemm** [Vazkii/Psi#703]
Forge version: 36.1.13
Psi version: 1.16-94

The output of Operator: Entity Position returns the position of every entities foot block except for players.
This makes for no ~~possible~~ easy way to provide consistent effects for both mobs and players.

**Comment by gdavid04** [comment]
In my opinion a separate Selector: Entity Eye Position in addition to Selector: Entity Position that return the eye and foot positions respectively could be a good solution.

**Comment by Kamefrede** [comment]
See my comment in #704
