### ISSUE TITLE
Log(0) = NaN, instead of negative infinity like it should be

### ISSUE THREAD

**Issue by Math321** [Vazkii/Psi#712]
# Version Information
Forge version: 36.1.16
Psi version: 94

What I expected to happen:
Log(0) = negative infinity
This is how it used to work in Psi, and the principle by which the "sneak-log-die" technique worked. This is also the answer to the equation that Java and Wolfram Alpha go with.

What happened instead:
Log(0) = NaN

**Comment by Dudblockman** [comment]
NaN and Infinity are no longer valid values for psi pieces.
