### ISSUE TITLE
Crash after opening gui

### ISSUE THREAD

**Issue by dc7431** [Vazkii/Psi#713]
Hi I play an Minecraft Modpack with my frieds and my Minecraft just crasht after i touched the button to open the gui.
I am using the newest version here is the crash log:
https://gist.github.com/dc7431/6a91d843c761d3917feea3ca25c0480a

**Comment by dc7431** [comment]
I am also using the newest version Random PSIdeas

**Comment by dc7431** [comment]
Found the bug it crashed because i had Hitboxes enabled

**Comment by gdavid04** [comment]
It shouldn't crash with show hitboxes enabled.
