### ISSUE TITLE
[Request] Spell Backup Server

### ISSUE THREAD

**Issue by squirrelkiller** [Vazkii/Psi#72]
I find myself needing to store quite a number of spells, Like I think I have around a gold chest from the Iron Chests mod mostly full of spells I want to actually keep on bullets and drives.

SO around the point I crafted the iron to gold upgrade I found myself looking for a more effective storage method, only to learn one does not exist so I feel this needs to be fixed.

The idea isn't complicated, just a block that can hold up to say 32 spells and copy them to bullets or drives. These spells can be added by right-clicking the block with a spell drive. A GUI can allow the selection and deletion of spells stored in the block.

For a proto-recipe:

D = Dark Psimetal Plate
F = Dark Psimetal Flow Plate
S = Spell Programmer
T = Spell Storage Drives

DFD
TST
DFD

A rapid reduction to base cost of materials:

5 gold
3 Redstone
2 Glowstone dust
6 Iron

Psi Energy is basically free so I am not counting that in the crafting cost.

**Comment by Vazkii** [comment]
A double chest can hold on to 54.
