### ISSUE TITLE
[MINOR HELP] Multiplying vectors

### ISSUE THREAD

**Issue by GameSlayar** [Vazkii/Psi#74]
Perhaps I'm just being a derp, but I can't find any way to multiply two vectors together.
The cross-product doesn't give me what I need. 

Example:
Vector A = 1,0,0
Vector B = -5,0,6

I need a function that will output Vector C = -5,0,0
```
(-5 * 1 = -5)
(0 * 0  =  0)
(6 * 0  =  0)
```

Is there something I missed or is this currently not possible?

**Comment by Vazkii** [comment]
Vector Project will do what you want.
