### ISSUE TITLE
Crash shortly after importing spell from clipboard

### ISSUE THREAD

**Issue by NoahNMorton** [Vazkii/Psi#75]
After importing a spell from clipboard into the spell programmer, I got a crash.

Mods installed are: Neat, Forge 1756, JEI, JEI Addons, MmmMmmMmm, and PSI Beta 14.

The spell: http://pastebin.com/kj8md1ht

The Crash log: http://pastebin.com/kQdtertr

The spell was originally copied from a text editor, if that matters.

Steps to replicate:

1. Launch MC.
2. Join/Create a world.
3. Place a spell programmer.
4. Select the button to import from clipboard, with the above spell in clipboard.
5. Crash.

**Comment by yrsegal** [comment]
I only got the crash after attempting to input a number.
