### ISSUE TITLE
Trick Smelt deletes some of items when repeatedly cast at stacks. Beta-15

### ISSUE THREAD

**Issue by Wojbie** [Vazkii/Psi#80]
When repeatedly (or loop/circle) casting trick smelt on a stack of iron ore some of the ore is used up but never drops as ingots.

From 6 tests i have done using circle spell (to ensure 20 casts) 64 iron turned into:

1. 19 iron 26 ore left.
2. 15 iron 38 ore left.
3. 13 iron 38 ore left.
4. 18 iron 31 ore left.
5. 20 iron 24 ore left.
6. 15 iron 37 ore left.

Spell i used:

{spellName:"Smelt",uuidMost:-4283247256322552132L,validSpell:1b,spellList:[0:{spellPosX:1,spellData:{spellKey:"operatorEntityPosition",params:{psi.spellparam.target:2}},spellPosY:3},1:{spellPosX:1,spellData:{spellKey:"selectorCaster",params:{}},spellPosY:4},2:{spellPosX:2,spellData:{spellKey:"constantNumber",params:{},constantValue:"2"},spellPosY:1},3:{spellPosX:2,spellData:{spellKey:"selectorNearbyItems",params:{psi.spellparam.radius:1,psi.spellparam.position:2}},spellPosY:2},4:{spellPosX:2,spellData:{spellKey:"operatorVectorRaycast",params:{psi.spellparam.ray:2,psi.spellparam.max:0,psi.spellparam.position:3}},spellPosY:3},5:{spellPosX:2,spellData:{spellKey:"operatorEntityLook",params:{psi.spellparam.target:3}},spellPosY:4},6:{spellPosX:3,spellData:{spellKey:"trickSmeltItem",params:{psi.spellparam.target:2}},spellPosY:1},7:{spellPosX:3,spellData:{spellKey:"operatorClosestToPoint",params:{psi.spellparam.position:2,psi.spellparam.target:3}},spellPosY:2},8:{spellPosX:3,spellData:{spellKey:"connector",params:{psi.spellparam.target:3}},spellPosY:3}],uuidLeast:-6353845555178067524L}

**Comment by Vazkii** [comment]
Oops wrong issue.
