### ISSUE TITLE
Spells that die without doing anything else still cost energy.

### ISSUE THREAD

**Issue by PsiGuy60** [Vazkii/Psi#82]
In the latest Beta version, spells that don't actually execute (have Trick:Die in the top left corner with a Target that amounts to 0) still cost energy.

This has been verified by placing the following spell in a regular spell bullet and casting it:

{spellName:"Do Bugger All",uuidMost:8832667643944519395L,validSpell:1b,spellList:[0:{spellPosX:0,spellData:{spellKey:"trickDie",params:{psi.spellparam.target:4}},spellPosY:0},1:{spellPosX:1,spellData:{spellKey:"constantNumber",params:{},constantValue:"0"},spellPosY:0},2:{spellPosX:1,spellData:{spellKey:"constantNumber",params:{},constantValue:"1"},spellPosY:1},3:{spellPosX:2,spellData:{spellKey:"trickFireResistance",params:{psi.spellparam.time:3,psi.spellparam.target:4}},spellPosY:1},4:{spellPosX:3,spellData:{spellKey:"selectorCaster",params:{}},spellPosY:1}],uuidLeast:-4644239141369285417L}

You will not get the Fire Resistance buff, but you will lose mana with every casting.

**Comment by Vazkii** [comment]
Intended.

**Comment by PsiGuy60** [comment]
So there being no real way to stop the Exosuit Leggings from draining mana with any spell inserted, is that intended behavior too?

**Comment by PsiGuy60** [comment]
So then you'd just have to find a spell that's sustainable when cast every single tick (which markedly does not include any of the buffs)?

**Comment by Wojbie** [comment]
Well you can always use battery if you want buff in leggings but that will keep you at 0 energy all the time and you are limited to size of battery for spell power on cast.

**Comment by GreyMario** [comment]
The behavior of Exosuit Leggings means that any spell bullet inserted will block regeneration and drain your power to 0. This makes them completely infeasible for any kind of reasonable use; if Die prevented consumption of power from tricks not yet cast, Exosuit Leggings would have potential uses.

**Comment by yrsegal** [comment]
That's not true, spells below 25 psi are safe to legs cast.

**Comment by GreyMario** [comment]
Show me a spell below 25 PSI that is _most reasonably_ slotted into an Exosuit Leggings, as opposed to _anywhere else_.

**Comment by yrsegal** [comment]
Explode the nearest entity with power 0.001.

**Comment by GreyMario** [comment]
Show me how to construct this spell with a psi cost below 25 on the current version.

**Comment by yrsegal** [comment]
https://www.reddit.com/r/psispellcompendium/comments/4sl52f/vaporization_or_area_mist_dispersion/?st=IT6HREI8&sh=67e19cd6

**Comment by GreyMario** [comment]
[Hahahahahaha no.](https://imgur.com/lkFH2Z8)

**Comment by yrsegal** [comment]
Strange. Add motion to the player, then? Gravity lesseners are a good legs
spell.

**Comment by GreyMario** [comment]
This makes the existence of Trick: Jump Boost redundant and also has this very undesirable result of not nullifying fall damage properly. It's not something I would want to have on all the time because of that.
