### ISSUE TITLE
CTD using Air Sigil from Blood Magic (PSI related stack trace) (Psi Beta-15, BloodMagic 1.8.9-2.0.0-18, Forge 1.8.9 11.15.1.1757)

### ISSUE THREAD

**Issue by Croebh** [Vazkii/Psi#84]
#### Issue Description:
I was using my air sigil in order to fly straight up, when suddenly I crashed. It's entirely possible its a conflict with my other mods, but it was specifically a blood magic item that caused it. This was on SMP.
I know that this occurred whilst using another mods item, but the stack trace mentions Psi, so I wasn't sure if it had anything to do with psi as well. I wasn't using anything psi related, but I did have a CAD on me at the time.

#### What happens:

Crashed to desktop, server errored but stayed up

http://pastebin.com/HH2zFHYy

____
#### Affected Versions (Do *not* use "latest"):

- Psi - Beta-15
- BloodMagic: 1.8.9-2.0.0-18
- Minecraft: 1.8.9 - SMP
- Forge: 1.8.9 11.15.1.1757 - SMP

**Comment by Croebh** [comment]
Completely unrelated to the issue at hand, but I noticed that wayoftimes github has a template for users when they post issues. Might be handy if you had one as well, to help users provide the proper information.

**Comment by Wojbie** [comment]
Acording to http://psi.vazkii.us/faq.php we are supposed to use this page template:
http://vazkii.us/br101/

**Comment by Croebh** [comment]
That's actually an awesome site (quit being so smart Vazkii!) 

Not necessarily a template, however. It does go over how to write a proper bug report, but doesn't help you organize it in a readable fashion, such as the headers, including a section for what version, etc.

On wayoftimes github, right when you open an issue, and go to type in your bug report, you are provided with the template already in place, you just need to provide your information in the designated sections.

**Comment by KindarConrath** [comment]
Had the exact same crash when falling out of the world in the End, same mods.
