### ISSUE TITLE
Various visual bugs with psimetal armor. Beta-15, Latest Forge

### ISSUE THREAD

**Issue by CakeLancelot** [Vazkii/Psi#85]
There are some visual bugs with psimetal armor:
1. Helmet faces wrong way on armor stand (always faces south, never rotates): 
https://gyazo.com/b30c8e3317bb015aab1f74047b8762fc.png.
2. Psimetal exosuit chestplate is animated when on armor stand: 
https://i.gyazo.com/c42b3e553d31eb42b202eb73051be35b.gif
3. 2nd Skin layer overlaps in some cases, circled in red. (may be more sections like this, but my minecraft skin doesn't use the entire area): 
https://gyazo.com/ad819d8fab6605f794c4a0b6f06be93c.png
https://gyazo.com/6d3c50b61a9c5834fc3e7c1efe6ca704.png

Again, this seems to be a purely visual bug, the mod itself works fine.

**Comment by yrsegal** [comment]
part 1 is a forge bug.

part 2 may be fixed in latest forge?

part 3 is just some model adjustment @wiiv

**Comment by Sunconure11** [comment]
Found another visual issue, while trying to slowly build a 1.8 build of my pack, though it is likely related to the others:

https://www.dropbox.com/s/yvxfzsq5qwalm6v/Screenshot%202016-03-03%2010.52.41.png?dl=0
