### ISSUE TITLE
Conjured blocks don't show black particles. Beta-15

### ISSUE THREAD

**Issue by Wojbie** [Vazkii/Psi#86]
When creating conjured blocks using black gray and light gray colors the color of black seems to be replaced with see-trough.  Here is visual showcase of what i mean.

Colors in showcase are in order: lime, white, black, lightGray, gray

![Day](http://i.imgur.com/qqCGX6z.png)
![Night](http://i.imgur.com/857isdp.png)

I also admit i like the almost invisible effect that it causes with blocks but it don't seem to be intended on black.

EDIT: It seems its in all stuff that uses colors. So you have almost invisible projectiles, mines and charges using black color.

**Comment by Vazkii** [comment]
Intended.
