### ISSUE TITLE
Feature: Spell Bullet: Line

### ISSUE THREAD

**Issue by Berstarke** [Vazkii/Psi#87]
This type of spell bullet would work like this: In order to use this Bullet, the player would shoot twice, preferably in different locations. This first projectile would stay where it lands, as a "standby shot". The spell would trigger only after the player shoots the second time. The positions of the two projectiles would form a vector, with a proper Selector for... well, selecting. Another new selector would be the "Selector: Standby shot", which would work exactly like the Focal Point, but for the standby shot.

If the player fires the standby shot and proceeds to do something the mod is not happy with (changing spells, dying, moving too far, etc.), this projectile would just be canceled. All the current other rules would apply (such as the max distance and so on). For problems like how to handle the Selector: Focal Point, just have the second shot be treated as the "real" one.

This would allow for some interesting applications, such as spells for building walls or bridges, or creating a barrier between you and an enemy, and so on. One can argue that it is already possible to create such spells, but I believe that being able to create vectors like this would open some unique uses. For example, moving entities reachable by the standby shot towards the second shot, or things like that. Plus, it would be a very elegant way to create highly specific vectors, like when you are building.

**Comment by Vazkii** [comment]
This is a good idea, but I got a better twist on it. Closing for now.
