### ISSUE TITLE
Light sensor on helmet is not firing the spell when under open sky. Beta-16

### ISSUE THREAD

**Issue by Wojbie** [Vazkii/Psi#90]
I made auto-light spell for helmet and i noticed that while it works in caves it does not work on surface even if in darkness.
The cost of casting is taken and the particles effect connected to casting do spawn but the debug don't run and the light is not conjured.
I have run test that confirms that this spell did work as correctly under Beta-15 so its my own guess it may be connected to [this commit](https://github.com/Vazkii/Psi/commit/aac0f78d67471eb03594343a4afa4f2d37427e65)

Spell i used to debug this:
{spellName:"LightPerm",uuidMost:5411918951527761662L,validSpell:1b,spellList:[0:{spellPosX:2,spellData:{spellKey:"trickDebug",params:{psi.spellparam.number:0,psi.spellparam.target:4}},spellPosY:3},1:{spellPosX:3,spellData:{spellKey:"selectorCaster",params:{}},spellPosY:2},2:{spellPosX:3,spellData:{spellKey:"operatorEntityPosition",params:{psi.spellparam.target:1}},spellPosY:3},3:{spellPosX:4,spellData:{spellKey:"trickConjureLight",params:{psi.spellparam.time:0,psi.spellparam.position:3}},spellPosY:3}],uuidLeast:-8098449893448392581L}

**Comment by Wojbie** [comment]
In Beta-17 its now activating in full sunlight in places where during night it would be dark. It seems to have got over-fixed in other direction.

**Comment by Vazkii** [comment]
That works.  ¯\_(ツ)_/¯

**Comment by Wojbie** [comment]
Soo... 
Intended or wontfix? 
:smiley: 
Cause i am leaving light behind me during day everywhere like i am reverse pac-man or something.
