### ISSUE TITLE
Block bounds for conjured lights only visually appear to be small

### ISSUE THREAD

**Issue by yrsegal** [Vazkii/Psi#91]
looking in the empty space around a conjured light acts like you're looking at the light itself.

**Comment by Vazkii** [comment]
That's block states for you.

**Comment by yrsegal** [comment]
dammit, block states

**Comment by Ricket** [comment]
Is this also why you can punch anywhere in the block containing a conjured light and it puts out the light? So that's unable to be fixed? Or should I open an issue for it? It's fairly inconvenient that you can so easily break the lights, unlike torches.

**Comment by williewillus** [comment]
world raytracing for breaking collision is based on `Block.getBoundingBox` however Vaz has only overridden `Block.getSelectedBoundingBox` which is client only.

So the block's true bounds for breaking is the full block but it displays the smaller one.

**Comment by Ricket** [comment]
Soo... Can we fix this then? Maybe @williewillus you could put out a pull request even?

Bonus points if we could make the light favor a side inside the block... Then they would be just like torches, which would be awesome.

**Comment by Ricket** [comment]
Was playing with Psi for the first time in a long time tonight and hit this issue again. Just thought I'd bump it, again. Please at least reopen this issue since it is indeed an issue and is fixable...

**Comment by Hund** [comment]
This is a really annoying issue. :/

**Comment by juliand665** [comment]
I fixed this in #399!

[Proof :p](https://youtu.be/_xdlTxM3vtQ)

Thanks @williewillus for the pointer to the issue.
