### ISSUE TITLE
spell combination causes ticking tile entity

### ISSUE THREAD

**Issue by Sanaradain** [Vazkii/Psi#92]
Using the follow spell will cause a ticking tile entity error and the server will crash and continue to crash until you delete the tile entity:

**Bullet Type:** Projectile
**Spell:**
{spellName:"Wither Shot",uuidMost:2265479176460060427L,validSpell:1b,spellList:[0:{spellPosX:2,spellData:{spellKey:"selectorFocalPoint",params:{}},spellPosY:3},1:{spellPosX:3,spellData:{spellKey:"operatorFocusedEntity",params:{psi.spellparam.target:3}},spellPosY:3},2:{spellPosX:4,spellData:{spellKey:"constantNumber",params:{},constantValue:"1"},spellPosY:2},3:{spellPosX:4,spellData:{spellKey:"trickWither",params:{psi.spellparam.time:2,psi.spellparam.power:1,psi.spellparam.target:3}},spellPosY:3},4:{spellPosX:4,spellData:{spellKey:"constantNumber",params:{},constantValue:"2"},spellPosY:4}],uuidLeast:-7159187827430677625L}

**Crash log:**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.82.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 2/22/16 7:48 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at vazkii.psi.api.internal.Vector3.<init>(Vector3.java:62)
	at vazkii.psi.common.spell.operator.vector.PieceOperatorVectorRaycast.raycast(PieceOperatorVectorRaycast.java:70)
	at vazkii.psi.common.spell.operator.entity.PieceOperatorFocusedEntity.getEntityLookedAt(PieceOperatorFocusedEntity.java:60)
	at vazkii.psi.common.spell.operator.entity.PieceOperatorFocusedEntity.execute(PieceOperatorFocusedEntity.java:48)
	at vazkii.psi.api.spell.CompiledSpell$Action.execute(CompiledSpell.java:95)
	at vazkii.psi.api.spell.CompiledSpell.execute(CompiledSpell.java:51)
	at vazkii.psi.api.spell.CompiledSpell.safeExecute(CompiledSpell.java:70)
	at vazkii.psi.common.entity.EntitySpellProjectile.cast(EntitySpellProjectile.java:211)
	at vazkii.psi.common.entity.EntitySpellProjectile.cast(EntitySpellProjectile.java:187)
	at vazkii.psi.common.entity.EntitySpellProjectile.func_70184_a(EntitySpellProjectile.java:183)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:204)
	at vazkii.psi.common.entity.EntitySpellProjectile.func_70071_h_(EntitySpellProjectile.java:128)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699)
	at net.minecraft.world.World.func_72870_g(World.java:1831)
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at vazkii.psi.api.internal.Vector3.<init>(Vector3.java:62)
	at vazkii.psi.common.spell.operator.vector.PieceOperatorVectorRaycast.raycast(PieceOperatorVectorRaycast.java:70)
	at vazkii.psi.common.spell.operator.entity.PieceOperatorFocusedEntity.getEntityLookedAt(PieceOperatorFocusedEntity.java:60)
	at vazkii.psi.common.spell.operator.entity.PieceOperatorFocusedEntity.execute(PieceOperatorFocusedEntity.java:48)
	at vazkii.psi.api.spell.CompiledSpell$Action.execute(CompiledSpell.java:95)
	at vazkii.psi.api.spell.CompiledSpell.execute(CompiledSpell.java:51)
	at vazkii.psi.api.spell.CompiledSpell.safeExecute(CompiledSpell.java:70)
	at vazkii.psi.common.entity.EntitySpellProjectile.cast(EntitySpellProjectile.java:211)
	at vazkii.psi.common.entity.EntitySpellProjectile.cast(EntitySpellProjectile.java:187)
	at vazkii.psi.common.entity.EntitySpellProjectile.func_70184_a(EntitySpellProjectile.java:183)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(SourceFile:204)
	at vazkii.psi.common.entity.EntitySpellProjectile.func_70071_h_(EntitySpellProjectile.java:128)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699)
	at net.minecraft.world.World.func_72870_g(World.java:1831)

-- Entity being ticked --
Details:
	Entity Type: Psi.psi:spellProjectile (vazkii.psi.common.entity.EntitySpellProjectile)
	Entity ID: 2828
	Entity Name: entity.Psi.psi:spellProjectile.name
	Entity's Exact location: 233.13, 82.46, 989.45
	Entity's Block location: 233.00,82.00,989.00 - World: (233,82,989), Chunk: (at 9,5,13 in 14,61; contains blocks 224,0,976 to 239,255,991), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: -1.85, -1.00, 0.47
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['sanaradain'/2827, l='world', x=238.83, y=84.00, z=988.18]]
	Chunk stats: ServerChunkCache: 1067 Drop: 0
	Level seed: -4241746115136290137
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: -28.00,64.00,256.00 - World: (-28,64,256), Chunk: (at 4,4,0 in -2,16; contains blocks -32,0,256 to -17,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3452190 game time, 2919767 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 27753 (now: false), thunder time: 111556 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.8.0_72, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4307232656 bytes (4107 MB) / 5195169792 bytes (4954 MB) up to 5195169792 bytes (4954 MB)
	JVM Flags: 3 total; -Xmx5120M -Xms5120M -Xss2M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP 9.19 Powered by Forge 11.15.1.1757 71 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (custom.jar) 
	UCHIJAAAA	Forge{11.15.1.1757} [Minecraft Forge] (custom.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	aura{591} [Aura Cascade] (AuraCascade-591.jar) 
	UCHIJAAAA	bagginses{2.1.5b} [Bagginses] (Bagginses-1.8.9-2.1.5b.jar) 
	UCHIJAAAA	BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
	UCHIJAAAA	BloodMagic{1.8.9-2.0.0-253-ss} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-253-ss.jar) 
	UCHIJAAAA	bookshelfapi{2.3.2} [Bookshelf] (Bookshelf-1.8.9-2.3.2.jar) 
	UCHIJAAAA	Thaumcraft{5.1.6} [Thaumcraft] (Thaumcraft-1.8.9-5.1.6.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania.r1.8-248-MC1.8-0.6.1.jar) 
	UCHIJAAAA	BuildCraft|Core{7.2.0-pre12} [BuildCraft] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.2.0-pre12} [BC Transport] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.2.0-pre12} [BC Energy] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.2.0-pre12} [BC Factory] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.2.0-pre12} [BC Silicon] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.2.0-pre12} [BC Robotics] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.2.0-pre12} [BC Builders] (buildcraft-7.2.0-pre12.jar) 
	UCHIJAAAA	buildingbrickscompatvanilla{1.8.9-1.3.2} [Building Bricks Vanilla Compat] (BuildingBricks-1.8.9-1.3.2.jar) 
	UCHIJAAAA	buildingbricks{1.8.9-1.3.2} [Building Bricks] (BuildingBricks-1.8.9-1.3.2.jar) 
	UCHIJAAAA	Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
	UCHIJAAAA	mcmultipart{1.0.7} [MCMultiPart] (MCMultiPart-1.0.7-universal.jar) 
	UCHIJAAAA	CharsetLib{0.2.1} [‽] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	CharsetTweaks{0.2.1} [*] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	CharsetWires{0.2.1} [+] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	CharsetAudio{0.2.1} [♫] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	CharsetStorage{0.2.1} [#] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	CharsetPipes{0.2.1} [|] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	CharsetGates{0.2.1} [&] (Charset-0.2.1-945baf5589832f727c42cf77.jar) 
	UCHIJAAAA	chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6.jar) 
	UCHIJAAAA	chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.11.jar) 
	UCHIJAAAA	compasscoords{1.8.9-0.2.6} [Compass Co-ords] (CompassCoords-1.8.9-0.2.6.jar) 
	UCHIJAAAA	ComputerCraft{1.78} [ComputerCraft] (ComputerCraft1.78.jar) 
	UCHIJAAAA	craftingtweaks{3.0.51} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.51.jar) 
	UCHIJAAAA	crafttweaker{3.0.0} [crafttweaker] (CraftTweaker-Customized-1.8.8-3.0.1.jar) 
	UCHIJAAAA	dsurround{2.0.4.10} [Dynamic Surroundings] (DynamicSurroundings-1.8.9-2.0.4.10.jar) 
	UCHIJAAAA	ShetiPhianCore{3.1.0} [ShetiPhian-Core] (ShetiPhianCore-1.8.9-3.1.0.jar) 
	UCHIJAAAA	EnderTanks{1.2.1} [EnderTanks] (EnderTanks-1.8.9-1.2.1.jar) 
	UCHIJAAAA	ezstorage{1.0} [EZ Storage] (ezstorage-1.8.9-1.2.4.jar) 
	UCHIJAAAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.8.9-v1.7} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.7.jar) 
	UCHIJAAAA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJAAAA	FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
	UCHIJAAAA	FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
	UCHIJAAAA	furnus{1.7} [Furnus] (Furnus-1.8.9-1.7.jar) 
	UCHIJAAAA	graves{1.8.9-b41-universal} [Graves Mod] (graves-1.8.9-b41-universal.jar) 
	UCHIJAAAA	hopperducts{1.4.6} [Hopper Ducts] (hopperducts-mc1.8.8-1.4.6.jar) 
	UCHIJAAAA	k4lib{1.8.9-1.0.16} [K4Lib] (k4lib-1.8.9-1.0.16-universal.jar) 
	UCHIJAAAA	HydCraft{1.8.9-3.1.65} [Hydraulicraft] (HydCraft-1.8.9-3.1.65-universal.jar) 
	UCHIJAAAA	IGWMod{1.2.4-4} [In-Game wiki Mod] (IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
	UCHIJAAAA	intangible{0.0.23} [Intangible] (intangible-1.8.9-0.0.23.jar) 
	UCHIJAAAA	inventorysorter{0.7.4+26} [Simple Inventory sorting] (inventorysorter-1.8.9-0.7.4+26.jar) 
	UCHIJAAAA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJAAAA	JEI{2.28.2.166} [Just Enough Items] (jei_1.8.9-2.28.2.166.jar) 
	UCHIJAAAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UCHIJAAAA	mantle{1.8.9-0.8.jenkins92} [Mantle] (Mantle-1.8.9-0.8.jar) 
	UCHIJAAAA	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UCHIJAAAA	Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar) 
	UCHIJAAAA	neotech{2.3.7} [NeoTech] (NeoTech-1.8.9-2.3.7.jar) 
	UCHIJAAAA	fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
	UCHIJAAAA	playerrugs{0.0.1} [Player Rugs] (PlayerRugs-1.8.8-1.2.0.jar) 
	UCHIJAAAA	PneumaticCraft{1.13.7-11} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.7-11-universal.jar) 
	UCHIJAAAA	progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
	UCHIJAAAA	Psi{beta-16} [Psi] (Psi-beta-16.jar) 
	UCHIJAAAA	RandomThings{3.6.2} [Random Things] (RandomThings-MC1.8.9-3.6.2.jar) 
	UCHIJAAAA	rftools{4.22beta25} [RFTools] (rftools-1.8.9-4.22beta25.jar) 
	UCHIJAAAA	simpleretrogen{2.2.2+3} [Simple Retrogen] (simpleretrogen-1.8.9-2.2.2+3.jar) 
	UCHIJAAAA	StorageDrawers{1.8.9-2.4.1} [Storage Drawers] (StorageDrawers-1.8.9-2.4.1.jar) 
	UCHIJAAAA	tconstruct{1.8.9-2.1.0.jenkins101} [Tinkers' Construct] (TConstruct-1.8.9-2.1.0.jar) 
	UCHIJAAAA	thaumicinfusion{4.82} [Thaumic Infusion] (ThaumicInfusion-1.8.9-4.82.jar) 
	UCHIJAAAA	wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
	Loaded coremods (and transformers): 
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
  lumien.randomthings.asm.ClassTransformer
thaumicinfusion (ThaumicInfusion-1.8.9-4.82.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 60; [EntityPlayerMP['sanaradain'/2827, l='world', x=238.83, y=84.00, z=988.18]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Vazkii** [comment]
Fixed with https://github.com/Vazkii/Psi/commit/2af07a0a7ab015a6eb77d8743c93679ef72b1116.
Use Selector: Attacked Entity next time.
