### ISSUE TITLE
Crash on startup (Beta-17, Both Latest and Recommended Forge)

### ISSUE THREAD

**Issue by ultiomos** [Vazkii/Psi#93]
I loaded the game from the vanilla launcher, with JEI and Psi as the only files in my mods folder. (Psi is v17) The mod loader gets through the "Constructing Mods" step, but fails at "Initializing Phase 1". The game loads up fine with just JEI.

Crash Log : http://pastebin.com/gZQnzidB

**Comment by Vazkii** [comment]
Get java 8.
