### ISSUE TITLE
Fall damage

### ISSUE THREAD

**Issue by Zipybug14** [Vazkii/Psi#95]
Given that Minecraft calculates fall damage by how many blocks you have fallen, not your impact velocity, even a spell which gently deposits the player on the ground will cause fall damage as if they fell at full speed from the max height of the fall.  Moving up in Minecraft will reset your height, so drop height can be inconsistent when tested.

To reproduce: build a spell which adds motion in +y based on -y speed.  Jump from a tall height.

I'm not 100% sure what the fix is, but possibly changing so that entities affected by psi (or all entities affected by fall damage) will set the number of blocks fallen based on the y speed at impact.

**Comment by PsiGuy60** [comment]
I think there are already conditions under which fall damage is negated. Also a lot of people seem to use Add Motion to cause fall damage in enemies.

**Comment by NoahNMorton** [comment]
I believe Vazkii means that if the spell results in you gaining altitude, your fall damage will be reset to the location you were at when you went up. Which means that in order to completely avoid fall damage, you would have to gain altitude <3 blocks from the ground. That's my interpretation.

**Comment by TehBigA** [comment]
Yes I've been having this exact issue. I made a fly spell that sends me forward and slightly up. If I fall for say 20 blocks then slow myself down and gently touch the ground. I take full damage as if I just fell 20 blocks. Other flying mods seem to avoid this some how so I hope you can fix it.

**Comment by yrsegal** [comment]
Other flying mods change a tag on the player that prevents you from taking fall damage at all.

**Comment by yrsegal** [comment]
The Air sigil is probably the best place to look for this.
