### ISSUE TITLE
Conjuring a block in the same place as an existing conjured block overwrites that time value

### ISSUE THREAD

**Issue by yrsegal** [Vazkii/Psi#96]

**Comment by yrsegal** [comment]
I can't reproduce it reliably.

**Comment by Wojbie** [comment]
Can you describe it better? What are you expecting what happens? Does the end time is from first block or from 2nd one? This report is kinda confusing.

**Comment by yrsegal** [comment]
The end time is from the second one. Basically, my rainbow road spell is
leaving holes in my conjured floors.

**Comment by NoahNMorton** [comment]
I too have experienced this (issue?). Conjuring a block with a time at the exact same location as an existing conj. block with a time, the new block's time value becomes that of the old, eg. A 3 second block overwriting a 10 second block, thus the block disappears after 3 seconds, with no visual change at the overwrite. Not sure if intended behaviour or not, however.

**Comment by Zipybug14** [comment]
I think this behavior is intended, although it may be improved by making the expiry time the longest cast, such that if you cast a block with a duration of 10s, wait 5s, then cast an 8s one, the block will have the color of the second block and end 13s after the first cast.

**Comment by yrsegal** [comment]
What my problem with it is is that the behavior is uncertain. If it never
or always overwrote time I'd be happy.
