### ISSUE TITLE
Exo-suit Helmet with Light Sensor Does not Detect Sunlight

### ISSUE THREAD

**Issue by xlstadal** [Vazkii/Psi#97]
Psi Beta-18
The light sensor only detects light from light sources in the world (e.g. torches, lava, glowstone, nitor) but fails to recognize sunlight as a light source.  When outside on a perfectly lit day, if you walk away from a light source the daylight sensor will trigger, even though it is midday.  This, coupled with a conjure light trick means that you will constantly be conjuring lights as you walk around and leave your previous light source's sphere of influence until you run out of mana.  
On the reverse side of this, if you equip this spell in a dark area, no where near light sources, the spell will not trigger until you enter and then leave again the sphere of influence of another light source in the world.

**Comment by yrsegal** [comment]
:(

**Comment by xlstadal** [comment]
Labels this as "wontfix."
... [f90aea9](https://github.com/Vazkii/Psi/commit/f90aea9f0e7952e47cd04bc77f991c08f4425c34) ...
Fixes anyway.

**Comment by yrsegal** [comment]
I fixed it, she didn't want to fix it herself. (Pasted code on stream). It
took a lot of digging to figure out what to do.
