### ISSUE TITLE
Can't see spell pieces descriptions.

### ISSUE THREAD

**Issue by FreedomIII** [Vazkii/Psi#99]
Spell pieces descriptions aren't visible in the tutorial menu or the Spell Programming grid, multiplayer, LAN Server.
(Cannot see spell errors too.)
![57179bfcf37926cda507c96cd6127b72](https://cloud.githubusercontent.com/assets/17465456/13308568/10172eda-db53-11e5-9fa3-84212b09422a.png)

**Comment by Vazkii** [comment]
Optifine? Anything weird in your mods list? I can't reproduce this.

**Comment by FreedomIII** [comment]
Sorry for not saying anything  about the modlist in the issue.

Full modlist: 
Optifine
Just Enough Items
Buildcraft beta (last build)
Intangible (last build)
Iron Chests
Psi (last build)

Optifine may be the source of the problem. If that were the case, sorry for bothering you with this.

**Comment by Vazkii** [comment]
Try it without optifine.

**Comment by yrsegal** [comment]
@FreedomIII, have you tried it again without optifine?

**Comment by FreedomIII** [comment]
Yes, I tried it, will test again with each mod in beta-19

**Comment by yrsegal** [comment]
what was the result?

**Comment by FreedomIII** [comment]
Hi, tested in current build, forgot one of the mods in the modlist. Disabling MapWriter-1.8.9-2.3.13 seems to solve the problem. Thanks and sorry for not giving a full mod list.
